import { useState,type ReactNode } from "react";
import { CalendarDays,Chrome,Copy,Ellipsis,Eye,EyeOff,KeyRound,Mail,PlugZap,RefreshCw,Settings2,Unplug } from "lucide-react";
import type { ConnectionAccount,ConnectionCapability,ConnectionDiagnosticSnapshot,ConnectionProvider } from "@nexo/shared";
import { Accordion } from "../../components/ui/Accordion";
import { IconButton } from "../../components/ui/IconButton";
import { InlineNotice } from "../../components/ui/InlineNotice";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { Tooltip } from "../../components/ui/Tooltip";
import { useConnections } from "./hooks/useConnections";

const capabilities:ConnectionCapability[]=["email.read","email.send","email.modify","calendar.read","calendar.write"];
const labels:Record<ConnectionCapability,string>={"email.read":"Ler e-mails","email.send":"Enviar e-mails","email.modify":"Alterar e-mails","calendar.read":"Ler agenda","calendar.write":"Alterar agenda"};
const scopes:Record<ConnectionCapability,string>={"email.read":"https://www.googleapis.com/auth/gmail.readonly","email.send":"https://www.googleapis.com/auth/gmail.send","email.modify":"https://www.googleapis.com/auth/gmail.modify","calendar.read":"https://www.googleapis.com/auth/calendar.readonly","calendar.write":"https://www.googleapis.com/auth/calendar"};

export function ConnectionsPage(){
  const model=useConnections();const[googleSecret,setGoogleSecret]=useState(""),[showSecret,setShowSecret]=useState(false),[openOAuth,setOpenOAuth]=useState<string|undefined>(),[selected,setSelected]=useState<Record<ConnectionProvider,ConnectionCapability[]>>({google:["email.read"],microsoft:["email.read","calendar.read"]});
  const connected=model.accounts.filter(account=>account.status==="connected"||account.status==="degraded").length,problems=model.accounts.filter(account=>!["connected","degraded"].includes(account.status)).length;
  return <div className="connectionsPage"><header className="connectionsHeader"><div><h1>Conexões</h1><p>Conecte os serviços que o Nexo pode usar.</p></div><div className="connectionsSummary"><span>{connected} conectados</span><span>1 local</span>{problems>0&&<span className="warning">{problems} com problema</span>}</div></header>
    {model.error&&<InlineNotice type="error" message={model.error} onDismiss={()=>model.setError(null)}/>} {model.notice&&<InlineNotice type="success" message={model.notice} onDismiss={()=>model.setNotice(null)}/>} 
    <h2 className="sectionLabel">Serviços</h2><section className="connectionsGrid">{model.loading?<><Skeleton/><Skeleton/><Skeleton/></>:<><ProviderCard provider="google" account={model.accounts.find(account=>account.provider==="google")} configured={model.configuration.googleConfigured} selected={selected.google} setSelected={next=>setSelected(current=>({...current,google:next}))} model={model}/><ProviderCard provider="microsoft" account={model.accounts.find(account=>account.provider==="microsoft")} configured={model.configuration.microsoftConfigured} selected={selected.microsoft} setSelected={next=>setSelected(current=>({...current,microsoft:next}))} model={model}/><OllamaCard/></>}</section>
    <section className="advancedConnections"><h2 className="sectionLabel">Configuração avançada</h2><p>Necessária apenas para configurar ou alterar o OAuth dos provedores.</p><Accordion id="google-oauth" title="Google OAuth" open={openOAuth==="google"} onToggle={()=>setOpenOAuth(openOAuth==="google"?undefined:"google")}><OAuthGoogle model={model} secret={googleSecret} setSecret={setGoogleSecret} show={showSecret} setShow={setShowSecret} selected={selected.google}/></Accordion><Accordion id="microsoft-oauth" title="Microsoft OAuth" open={openOAuth==="microsoft"} onToggle={()=>setOpenOAuth(openOAuth==="microsoft"?undefined:"microsoft")}><OAuthMicrosoft model={model}/></Accordion></section>
  </div>;
}

function ProviderCard({provider,account,configured,selected,setSelected,model}:{provider:ConnectionProvider;account?:ConnectionAccount;configured:boolean;selected:ConnectionCapability[];setSelected:(value:ConnectionCapability[])=>void;model:ReturnType<typeof useConnections>}){
  const[manage,setManage]=useState(false),[section,setSection]=useState<"permissions"|"status"|"diagnostic"|undefined>(),[menu,setMenu]=useState(false),[diagnostic,setDiagnostic]=useState<ConnectionDiagnosticSnapshot>(),[showJson,setShowJson]=useState(false);const title=provider==="google"?"Google":"Microsoft",busy=model.busy===provider;
  const requested=account?.requestedCapabilities??account?.capabilities??[];const granted=account?.capabilities??[];const email=capabilityState(granted,requested,["email.read","email.send","email.modify"]),calendar=capabilityState(granted,requested,["calendar.read","calendar.write"]);
  const toggle=(capability:ConnectionCapability)=>setSelected(selected.includes(capability)?selected.filter(value=>value!==capability):[...selected,capability]);
  async function openDiagnostic(){if(!account)return;setDiagnostic(await model.diagnostics(account.id));setManage(true);setSection("diagnostic");}
  async function disconnect(){if(account&&window.confirm(`Desconectar ${title}? Os tokens salvos serão removidos deste computador.`))await model.disconnect(provider,account.id);}
  return <article className="providerCard"><div className="providerCardHeader"><div className="providerIdentity"><ProviderIcon provider={provider}/><div><h3>{title}</h3><span>{account?.accountEmail??(configured?"Pronto para conectar":"Configure o OAuth antes de conectar")}</span></div></div><Status account={account} configured={configured}/></div><p className="providerDescription">{provider==="google"?"Gmail e Google Agenda":"Outlook, e-mail e calendário"}</p>{account?<><CapabilitySummary icon={<Mail size={16}/>} label="E-mail" state={email}/><CapabilitySummary icon={<CalendarDays size={16}/>} label="Agenda" state={calendar}/><small className="validationTime">{account.lastValidatedAt?`Última validação: ${new Date(account.lastValidatedAt).toLocaleString("pt-BR")}`:"Aguardando validação"}</small>{manage&&<div className="providerDetails"><Accordion id={`${provider}-permissions`} title="Permissões" summary={`${granted.length} de ${requested.length} operacionais`} open={section==="permissions"} onToggle={()=>setSection(section==="permissions"?undefined:"permissions")}><CapabilityManager draft={selected} toggle={toggle} account={account} onSave={()=>void model.updateCapabilities(provider,account.id,selected)} busy={busy}/></Accordion><Accordion id={`${provider}-status`} title="Estado da conexão" open={section==="status"} onToggle={()=>setSection(section==="status"?undefined:"status")}><ConnectionState account={account}/></Accordion><Accordion id={`${provider}-diagnostic`} title="Diagnóstico técnico" summary="Sem tokens ou secrets" open={section==="diagnostic"} onToggle={()=>{if(section==="diagnostic")setSection(undefined);else void openDiagnostic();}}>{diagnostic&&<Diagnostic value={diagnostic} json={showJson} setJson={setShowJson}/>}</Accordion></div>}</>:<div className="connectionChooser"><b>O que o Nexo poderá acessar?</b><CapabilityChooser selected={selected} toggle={toggle}/></div>}{account?<div className="cardActions"><button onClick={()=>{setSelected(requested);setManage(true);setSection("permissions");}}>Gerenciar conexão</button><IconButton icon={Ellipsis} label="Mais ações" onClick={()=>setMenu(value=>!value)}/>{menu&&<div className="actionMenu"><button onClick={()=>void model.test(provider,account.id)}><RefreshCw size={15}/> Testar conexão</button><button onClick={()=>void openDiagnostic()}><Settings2 size={15}/> Diagnóstico</button><button onClick={()=>{setSelected(requested);setManage(true);setSection("permissions");}}><PlugZap size={15}/> Reautorizar</button><button className="danger" onClick={()=>void disconnect()}><Unplug size={15}/> Desconectar</button></div>}</div>:<button className="connectButton" disabled={!configured||busy||!selected.length} onClick={()=>void model.connect(provider,selected)}>{busy?"Abrindo…":configured?`Conectar ${title}`:"Configurar OAuth"}</button>}</article>;
}

function OAuthGoogle({model,secret,setSecret,show,setShow,selected}:{model:ReturnType<typeof useConnections>;secret:string;setSecret:(value:string)=>void;show:boolean;setShow:(value:boolean)=>void;selected:ConnectionCapability[]}){const[help,setHelp]=useState(false),[scopeOpen,setScopeOpen]=useState(false),[copied,setCopied]=useState<string>();return <div className="oauthForm"><label htmlFor="google-client-id">Client ID <Tooltip content="Identificador OAuth do aplicativo Google."><span className="infoMark">i</span></Tooltip></label><input id="google-client-id" value={model.configuration.googleClientId} onChange={event=>model.setConfiguration({...model.configuration,googleClientId:event.target.value})}/><label htmlFor="google-client-secret">Client Secret <Tooltip content="Credencial privada armazenada apenas no computador."><span className="infoMark">i</span></Tooltip></label><div className="secretField"><input id="google-client-secret" type={show?"text":"password"} value={secret} placeholder={model.configuration.googleClientSecretConfigured?"Já armazenado — deixe em branco para manter":"GOCSPX-…"} onChange={event=>setSecret(event.target.value)}/><IconButton icon={show?EyeOff:Eye} label={show?"Ocultar Client Secret digitado":"Mostrar Client Secret digitado"} onClick={()=>setShow(!show)} disabled={!secret}/></div><p className="oauthStored">{model.configuration.googleClientSecretConfigured?"Client Secret armazenado com segurança neste computador.":"Client Secret ainda não configurado."}</p><div className="rowActions"><button disabled={model.busy!==null} onClick={()=>void model.saveOAuth(secret).then(()=>setSecret(""))}>Salvar credenciais</button>{model.configuration.googleClientSecretConfigured&&<button className="ghost danger" disabled={model.busy!==null} onClick={()=>{if(window.confirm("Remover o Client Secret do Google? As contas conectadas precisarão ser reautorizadas."))void model.removeGoogleSecret();}}>Remover Client Secret</button>}</div><Accordion id="google-help" title="Como configurar no Google Cloud" open={help} onToggle={()=>setHelp(!help)}><p><b>Permissões necessárias no Google Cloud</b></p><ol><li>Crie um cliente OAuth do tipo aplicativo para computador.</li><li>Em Google Auth Platform → Data Access, adicione os scopes exibidos abaixo.</li><li>Habilite Gmail API e Google Calendar API quando necessário.</li><li>Em Testing, inclua a conta em Test users e reautorize após qualquer alteração.</li></ol></Accordion><Accordion id="google-scopes" title="Scopes OAuth necessários" summary={`${selected.length} selecionados`} open={scopeOpen} onToggle={()=>setScopeOpen(!scopeOpen)}>{[...new Set(selected.map(value=>scopes[value]))].map(scope=><div className="scopeRow" key={scope}><code>{scope}</code><button onClick={()=>void navigator.clipboard.writeText(scope).then(()=>setCopied(scope))}>{copied===scope?"Copiado":"Copiar"}</button></div>)}</Accordion></div>;}
function OAuthMicrosoft({model}:{model:ReturnType<typeof useConnections>}){return <div className="oauthForm"><label>Client ID <Tooltip content="Identificador do aplicativo Microsoft Entra."><span className="infoMark">i</span></Tooltip><input value={model.configuration.microsoftClientId} onChange={event=>model.setConfiguration({...model.configuration,microsoftClientId:event.target.value})}/></label><label>Tenant <Tooltip content="Diretório Microsoft usado na autenticação."><span className="infoMark">i</span></Tooltip><input value={model.configuration.microsoftTenant} onChange={event=>model.setConfiguration({...model.configuration,microsoftTenant:event.target.value})}/></label><button disabled={model.busy!==null} onClick={()=>void model.saveOAuth("")}>Salvar configuração Microsoft</button></div>;}
function CapabilityManager({draft,toggle,account,onSave,busy}:{draft:ConnectionCapability[];toggle:(capability:ConnectionCapability)=>void;account:ConnectionAccount;onSave:()=>void;busy:boolean}){return <div className="capabilityManager"><b>E-mail</b>{capabilities.slice(0,3).map(capability=><CapabilityLine key={capability} capability={capability} checked={draft.includes(capability)} toggle={toggle} grant={account.capabilityGrants?.find(grant=>grant.capability===capability)}/>) }<b>Agenda</b>{capabilities.slice(3).map(capability=><CapabilityLine key={capability} capability={capability} checked={draft.includes(capability)} toggle={toggle} grant={account.capabilityGrants?.find(grant=>grant.capability===capability)}/>) }<button disabled={busy||!draft.length} onClick={onSave}>Salvar alterações</button></div>}
function CapabilityLine({capability,checked,toggle,grant}:{capability:ConnectionCapability;checked:boolean;toggle:(capability:ConnectionCapability)=>void;grant?:NonNullable<ConnectionAccount["capabilityGrants"]>[number]}){const detail=grant?`${grant.requested?"Solicitada":"Não solicitada"} · ${grant.granted?"Concedida":"Não concedida"} · ${grant.validated?"Validada":"Não validada"}`:"Não solicitada · Não concedida · Não validada";return <label><input type="checkbox" checked={checked} onChange={()=>toggle(capability)}/>{labels[capability]}<small>{detail}</small></label>}
function CapabilityChooser({selected,toggle}:{selected:ConnectionCapability[];toggle:(capability:ConnectionCapability)=>void}){return <div className="compactChooser">{capabilities.map(capability=><label key={capability}><input type="checkbox" checked={selected.includes(capability)} onChange={()=>toggle(capability)}/>{labels[capability]}</label>)}</div>}
function CapabilitySummary({icon,label,state}:{icon:ReactNode;label:string;state:"ok"|"partial"|"off"}){const help=label==="E-mail"?"Permissões para consultar, enviar ou alterar e-mails.":"Permissões para consultar, criar, editar ou cancelar compromissos.";return <Tooltip content={help}><div className={`capabilitySummary ${state}`} tabIndex={0}>{icon}<span>{label}</span><b>{state==="ok"?"Operacional":state==="partial"?"Parcial":"Não configurado"}</b></div></Tooltip>}
function ConnectionState({account}:{account:ConnectionAccount}){return <dl className="connectionState"><dt>Status</dt><dd>{account.status}</dd><dt>Última validação</dt><dd>{account.lastValidatedAt?new Date(account.lastValidatedAt).toLocaleString("pt-BR"):"—"}</dd><dt>Última renovação</dt><dd>{account.lastRefreshAt?new Date(account.lastRefreshAt).toLocaleString("pt-BR"):"—"}</dd><dt>Scopes concedidos</dt><dd>{account.grantedScopes?.length??0}</dd></dl>}
function Diagnostic({value,json,setJson}:{value:ConnectionDiagnosticSnapshot;json:boolean;setJson:(value:boolean)=>void}){const safe={provider:value.provider,status:value.status,tokenPresent:value.tokenPresent,refreshTokenPresent:value.refreshTokenPresent,clientMatches:value.clientMatches,scopeSource:value.scopeSource,grantedScopes:value.grantedScopes,requestedCapabilities:value.requestedCapabilities,capabilities:value.capabilities};const text=JSON.stringify(safe,null,2);return <div className="diagnostic"><p>{value.tokenPresent?"✓ Token presente":"⚠ Token ausente"}</p><p>{value.refreshTokenPresent?"✓ Refresh token presente":"⚠ Refresh token ausente"}</p>{value.clientMatches!==undefined&&<p>{value.clientMatches?"✓ Client ID confere":"⚠ Client ID não confere"}</p>}<button className="ghost" onClick={()=>setJson(!json)}>Ver JSON técnico</button><button className="ghost" onClick={()=>void navigator.clipboard.writeText(text)}><Copy size={15}/> Copiar diagnóstico</button>{json&&<pre>{text}</pre>}</div>}
function ProviderIcon({provider}:{provider:ConnectionProvider}){return <span className={`providerIcon ${provider}`}>{provider==="google"?<Chrome size={21}/>:<Mail size={21}/>}</span>}
function Status({account,configured}:{account?:ConnectionAccount;configured:boolean}){const status=account?.status??(configured?"ready":"unconfigured"),labels:Record<string,string>={connected:"✓ Conectado",degraded:"⚠ Parcial",refreshing:"↻ Renovando",validating:"◌ Validando",expired:"! Expirado","reauthorization-required":"↗ Reautorizar",ready:"Pronto para conectar",unconfigured:"Configuração necessária"},help:Record<string,string>={connected:"Conexão validada e operacional.",degraded:"Algumas permissões foram recusadas ou ainda não estão operacionais.",expired:"A autorização precisa ser renovada.","reauthorization-required":"Revise as permissões no provedor e autorize novamente."};return <StatusBadge status={status} label={labels[status]??"! Atenção"} help={help[status]??"Estado atual da conexão."}/>}
function OllamaCard(){return <article className="providerCard ollamaCard"><div className="providerCardHeader"><div className="providerIdentity"><span className="providerIcon ollama"><KeyRound size={21}/></span><div><h3>Ollama</h3><span>IA local</span></div></div><span className="connectionStatus connected">✓ Ativo</span></div><p className="providerDescription">Processamento local disponível. O Nexo usa o modelo configurado.</p></article>}
function Skeleton(){return <article className="providerCard skeleton"><span/><span/><span/></article>}
function capabilityState(granted:ConnectionCapability[],requested:ConnectionCapability[],group:ConnectionCapability[]){const count=group.filter(capability=>granted.includes(capability)).length,wanted=group.filter(capability=>requested.includes(capability)).length;return count===group.length||count===wanted&&wanted>0?"ok":count>0?"partial":"off";}
