import { randomUUID } from "node:crypto";
import type { DashboardGadgetId, DashboardGadgetInstance, GadgetDefinition, GadgetSize } from "@nexo/shared";
import type { NexoDatabase } from "../database/db.js";

const definitions: GadgetDefinition[] = [
  { id:"ai-status",title:"IA local",description:"Modelo, conexão e privacidade",category:"nexo",sizes:["S","M","L"],defaultSize:"S",provider:"internal",refreshInterval:5000 },
  { id:"tasks",title:"Tarefas em andamento",description:"Acompanhe os agentes ativos",category:"productivity",sizes:["S","M","L"],defaultSize:"M",provider:"internal" },
  { id:"approvals",title:"Aprovações",description:"Ações que aguardam sua decisão",category:"productivity",sizes:["S","M","L"],defaultSize:"S",provider:"internal",refreshInterval:10000 },
  { id:"automations",title:"Macros",description:"Rotinas e execuções recentes",category:"productivity",sizes:["S","M","L"],defaultSize:"M",provider:"internal",refreshInterval:30000 },
  { id:"activity",title:"Atividade do Nexo",description:"Ações registradas nos últimos dias",category:"nexo",sizes:["M","L","XL"],defaultSize:"L",provider:"internal",refreshInterval:30000 },
  { id:"documents",title:"Documentos recentes",description:"Arquivos usados no Nexo",category:"productivity",sizes:["S","M","L"],defaultSize:"M",provider:"internal",refreshInterval:30000 },
  { id:"system",title:"Saúde do computador",description:"Uso de memória e recursos locais",category:"system",sizes:["S","M","L"],defaultSize:"M",provider:"internal",refreshInterval:10000 },
  { id:"weather",title:"Clima",description:"Previsão local fornecida pela MET Norway",category:"weather",sizes:["S","M","L"],defaultSize:"S",provider:"http",refreshInterval:1200000,requiresInternet:true,requiresConfiguration:true,attribution:"MET Norway · dados sob CC BY 4.0" },
  { id:"currency",title:"Câmbio",description:"Taxas de referência para BRL",category:"finance",sizes:["S","M","L"],defaultSize:"S",provider:"http",refreshInterval:21600000,requiresInternet:true,attribution:"Frankfurter" },
  { id:"holidays",title:"Próximos feriados",description:"Feriados nacionais do Brasil",category:"information",sizes:["S","M","L"],defaultSize:"S",provider:"http",refreshInterval:86400000,requiresInternet:true,attribution:"BrasilAPI" },
  { id:"business-days",title:"Dias úteis",description:"Dias úteis restantes neste mês, descontando feriados nacionais",category:"information",sizes:["S","M"],defaultSize:"S",provider:"http",refreshInterval:86400000,requiresInternet:true,attribution:"BrasilAPI" },
  { id:"tech-news",title:"Tech Pulse",description:"Histórias em alta no Hacker News",category:"news",sizes:["M","L","XL"],defaultSize:"L",provider:"http",refreshInterval:600000,requiresInternet:true,attribution:"Hacker News" },
  { id:"earthquakes",title:"Atividade global",description:"Terremotos recentes pelo mundo",category:"information",sizes:["M","L"],defaultSize:"M",provider:"http",refreshInterval:300000,requiresInternet:true,attribution:"USGS" }
];
const allowedIds = new Set(definitions.map(item=>item.id));
const sizes = new Set<GadgetSize>(["S","M","L","XL"]);
const defaults: DashboardGadgetId[] = ["ai-status","tasks","approvals","automations","activity","documents","system"];
type CacheRow={payload_json:string;fetched_at:string;expires_at:string};
type InternalReader=(id:DashboardGadgetId)=>Promise<unknown>;

export class DashboardService {
  constructor(private readonly db:NexoDatabase,private readonly internal:InternalReader) { this.seed(); }
  catalog(){return structuredClone(definitions);}
  layout():DashboardGadgetInstance[]{return this.db.all<{instance_id:string;gadget_id:string;size:string;configuration_json:string;enabled:number}>("SELECT instance_id,gadget_id,size,configuration_json,enabled FROM dashboard_gadgets ORDER BY position,created_at").map(row=>({instanceId:row.instance_id,gadgetId:row.gadget_id as DashboardGadgetId,size:row.size as GadgetSize,configuration:this.parseConfig(row.configuration_json),enabled:row.enabled===1}));}
  add(gadgetId:DashboardGadgetId,configuration:Record<string,unknown>={},size?:GadgetSize){this.assertGadget(gadgetId);this.validateConfig(gadgetId,configuration);const definition=definitions.find(item=>item.id===gadgetId)!;const selected=size??definition.defaultSize;if(!definition.sizes.includes(selected))throw new Error("Tamanho não disponível para este gadget.");const now=new Date().toISOString(),instance={instanceId:randomUUID(),gadgetId,size:selected,configuration,enabled:true};this.db.run("INSERT INTO dashboard_gadgets(instance_id,gadget_id,position,size,configuration_json,enabled,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)",[instance.instanceId,gadgetId,this.layout().length,selected,JSON.stringify(configuration),now,now]);return instance;}
  remove(instanceId:string){this.db.run("DELETE FROM dashboard_gadgets WHERE instance_id=?",[instanceId]);this.reindex();return this.layout();}
  configure(instanceId:string,configuration:Record<string,unknown>,size?:GadgetSize){const row=this.db.get<{gadget_id:string}>('SELECT gadget_id FROM dashboard_gadgets WHERE instance_id=?',[instanceId]);if(!row)throw new Error("Gadget não encontrado.");this.validateConfig(row.gadget_id as DashboardGadgetId,configuration);const definition=definitions.find(item=>item.id===row.gadget_id)!;if(size&&!definition.sizes.includes(size))throw new Error("Tamanho não disponível para este gadget.");this.db.run(`UPDATE dashboard_gadgets SET configuration_json=?,size=COALESCE(?,size),updated_at=? WHERE instance_id=?`,[JSON.stringify(configuration),size??null,new Date().toISOString(),instanceId]);return this.layout().find(item=>item.instanceId===instanceId)!;}
  saveLayout(items:Array<{instanceId:string;size:GadgetSize;position:number}>){if(!Array.isArray(items)||items.length>40)throw new Error("Layout inválido.");const current=new Map(this.layout().map(item=>[item.instanceId,item]));if(items.length!==current.size||items.some(item=>{const existing=current.get(item.instanceId);return !existing||!definitions.find(definition=>definition.id===existing.gadgetId)!.sizes.includes(item.size)||!Number.isInteger(item.position)||item.position<0||item.position>=items.length;})||new Set(items.map(item=>item.instanceId)).size!==items.length||new Set(items.map(item=>item.position)).size!==items.length)throw new Error("O layout deve conter cada gadget uma única vez e posições válidas.");this.db.transaction(()=>{for(const item of items)this.db.run("UPDATE dashboard_gadgets SET position=?,size=?,updated_at=? WHERE instance_id=?",[item.position,item.size,new Date().toISOString(),item.instanceId]);});return this.layout();}
  async data(gadgetId:DashboardGadgetId,configuration:Record<string,unknown>={}){this.assertGadget(gadgetId);const definition=definitions.find(item=>item.id===gadgetId)!;if(definition.provider==="internal")return{data:await this.internal(gadgetId),fetchedAt:new Date().toISOString(),stale:false};this.validateConfig(gadgetId,configuration);const cacheKey=this.cacheKey(gadgetId,configuration),cached=this.db.get<CacheRow>("SELECT payload_json,fetched_at,expires_at FROM dashboard_cache WHERE provider=? AND cache_key=?",[gadgetId,cacheKey]),now=Date.now();if(cached&&Date.parse(cached.expires_at)>now)return{data:JSON.parse(cached.payload_json),fetchedAt:cached.fetched_at,stale:false};try{const payload=await this.fetchExternal(gadgetId,configuration);const fetchedAt=new Date().toISOString(),expiresAt=new Date(now+definition.refreshInterval!).toISOString();this.db.run("INSERT OR REPLACE INTO dashboard_cache(provider,cache_key,payload_json,fetched_at,expires_at) VALUES(?,?,?,?,?)",[gadgetId,cacheKey,JSON.stringify(payload),fetchedAt,expiresAt]);return{data:payload,fetchedAt,stale:false};}catch(error){if(cached)return{data:JSON.parse(cached.payload_json),fetchedAt:cached.fetched_at,stale:true,error:error instanceof Error?error.message:"Sem conexão."};throw error;}}
  private seed(){if(this.db.get("SELECT instance_id FROM dashboard_gadgets LIMIT 1"))return;const now=new Date().toISOString();this.db.transaction(()=>defaults.forEach((gadgetId,position)=>this.db.run("INSERT INTO dashboard_gadgets(instance_id,gadget_id,position,size,configuration_json,enabled,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)",[randomUUID(),gadgetId,position,definitions.find(item=>item.id===gadgetId)!.defaultSize,"{}",now,now])));}
  private reindex(){this.db.transaction(()=>this.layout().forEach((item,position)=>this.db.run("UPDATE dashboard_gadgets SET position=? WHERE instance_id=?",[position,item.instanceId])));}
  private assertGadget(id:string):asserts id is DashboardGadgetId{if(!allowedIds.has(id as DashboardGadgetId))throw new Error("Tipo de gadget não registrado.");}
  private parseConfig(value:string){try{const parsed=JSON.parse(value);return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}}
  private validateConfig(id:DashboardGadgetId,config:Record<string,unknown>){if(!config||typeof config!=="object"||Array.isArray(config)||JSON.stringify(config).length>4000)throw new Error("Configuração de gadget inválida.");if(id==="weather"){const {latitude,longitude}=config;if(typeof latitude!=="number"||latitude < -90||latitude > 90||typeof longitude!=="number"||longitude < -180||longitude > 180||typeof config.place!=="string"||config.place.trim().length<1||config.place.length>80)throw new Error("Configure local, latitude e longitude válidas para o clima.");if(config.unit!==undefined&&!['C','F'].includes(String(config.unit)))throw new Error("Unidade de temperatura inválida.");}if(id==="currency"){const codes=String(config.currencies??"USD,EUR,GBP,JPY").split(",").map(code=>code.trim());if(codes.length<1||codes.length>6||codes.some(code=>!/^[A-Z]{3}$/.test(code)||code==="BRL")||new Set(codes).size!==codes.length)throw new Error("Informe de 1 a 6 moedas válidas, sem repetir BRL.");}}
  private cacheKey(id:DashboardGadgetId,config:Record<string,unknown>){return id==="weather"?`${config.latitude},${config.longitude},${config.unit??"C"}`:id==="currency"?String(config.currencies??"USD,EUR,GBP,JPY"):id;}
  private async fetchJson(url:string,hostname:string,maxBytes=1_000_000){const parsed=new URL(url);if(parsed.protocol!=="https:"||parsed.hostname!==hostname||parsed.username||parsed.password)throw new Error("Destino externo não permitido.");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(parsed,{signal:controller.signal,redirect:"error",headers:{accept:"application/json","user-agent":"Nexo AI Desktop/0.6 (local dashboard)"}});if(!response.ok)throw new Error(`Serviço externo respondeu ${response.status}.`);const declared=Number(response.headers.get("content-length")??0);if(declared>maxBytes)throw new Error("Resposta externa excede o limite permitido.");if(!response.body){const text=await response.text();if(new TextEncoder().encode(text).byteLength>maxBytes)throw new Error("Resposta externa excede o limite permitido.");return JSON.parse(text) as unknown;}const reader=response.body.getReader(),chunks:Uint8Array[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>maxBytes){await reader.cancel();throw new Error("Resposta externa excede o limite permitido.");}chunks.push(value);}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return JSON.parse(new TextDecoder().decode(bytes)) as unknown;}finally{clearTimeout(timer);}}
  private async fetchExternal(id:DashboardGadgetId,config:Record<string,unknown>):Promise<unknown>{
    if(id==="currency"){const symbols=String(config.currencies??"USD,EUR,GBP,JPY").split(",").map(code=>code.trim());const data=await this.fetchJson(`https://api.frankfurter.dev/v1/latest?base=BRL&symbols=${symbols.join(",")}`,"api.frankfurter.dev");if(!data||typeof data!=="object"||!("rates" in data))throw new Error("Formato de câmbio inválido.");return data;}
    if(id==="holidays"){const year=new Date().getFullYear(),data=await this.fetchJson(`https://brasilapi.com.br/api/feriados/v1/${year}`,"brasilapi.com.br");if(!Array.isArray(data))throw new Error("Formato de feriados inválido.");return data.filter(item=>item&&typeof item.date==="string"&&typeof item.name==="string");}
    if(id==="business-days"){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),last=new Date(year,month+1,0).getDate(),holidays=await this.fetchJson(`https://brasilapi.com.br/api/feriados/v1/${year}`,"brasilapi.com.br");if(!Array.isArray(holidays))throw new Error("Formato de feriados inválido.");const holidayDates=new Set(holidays.filter(item=>item&&typeof item.date==="string").map(item=>item.date));let remaining=0;for(let day=now.getDate()+1;day<=last;day++){const date=new Date(year,month,day),iso=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;if(date.getDay()!==0&&date.getDay()!==6&&!holidayDates.has(iso))remaining++;}return{remaining,month:now.toLocaleDateString("pt-BR",{month:"long"}),year};}
    if(id==="weather"){const lat=Number(config.latitude),lon=Number(config.longitude),unit=config.unit==="F"?"fahrenheit":"celsius",data=await this.fetchJson(`https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=${lat}&lon=${lon}`,"api.met.no");if(!data||typeof data!=="object"||!("properties" in data))throw new Error("Formato de clima inválido.");return{data,unit,place:String(config.place??"Local configurado")};}
    if(id==="tech-news"){const top=await this.fetchJson("https://hacker-news.firebaseio.com/v0/topstories.json","hacker-news.firebaseio.com",100_000);if(!Array.isArray(top))throw new Error("Formato do Hacker News inválido.");const results=await Promise.allSettled(top.slice(0,6).filter(Number.isInteger).map(storyId=>this.fetchJson(`https://hacker-news.firebaseio.com/v0/item/${storyId}.json`,"hacker-news.firebaseio.com",30_000)));return results.flatMap(result=>result.status==="fulfilled"&&result.value&&typeof result.value==="object"&&"title" in result.value?[result.value]:[]);}
    if(id==="earthquakes"){const data=await this.fetchJson("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson","earthquake.usgs.gov",500_000);if(!data||typeof data!=="object"||!("features" in data)||!Array.isArray((data as {features:unknown}).features))throw new Error("Formato USGS inválido.");return(data as {features:unknown[]}).features.slice(0,8);}
    throw new Error("Provider externo indisponível.");
  }
}
