import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronRight, CirclePlay, Clock3, Copy, History, MoreHorizontal, Pause, Play, Plus, Search, Sparkles, TestTube2, Trash2, X } from "lucide-react";
import type { AutomationViewModel, AutomationPreset } from "@nexo/shared";
import type { AutomationExecutionResult } from "@nexo/shared";
import { useAppStore } from "../stores/app";
import { useAssistantStore } from "../stores/assistant";
import "./automations.css";

const status: Record<string, string> = { active: "Ativa", paused: "Pausada", running: "Executando", waiting_approval: "Aguardando aprovação", attention: "Precisa de atenção" };
type AutomationActionCatalogItem = { id: string; title: string; description: string; icon: string; risk: "read" | "write" | "sensitive"; fields: Array<{ key: string; label: string; type: string; required?: boolean; placeholder?: string }> };
const ago = (value?: string) => { if (!value) return "Ainda não executada"; const n = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return n < 1 ? "agora" : n < 60 ? `há ${n} min` : n < 1440 ? `há ${Math.floor(n / 60)} h` : `há ${Math.floor(n / 1440)} d`; };

export function Automations() {
  const [rows, setRows] = useState<AutomationViewModel[]>([]), [presets, setPresets] = useState<AutomationPreset[]>([]), [catalog, setCatalog] = useState<AutomationActionCatalogItem[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [filter, setFilter] = useState("Todas"), [builder, setBuilder] = useState<any>(null), [details, setDetails] = useState<AutomationViewModel | null>(null);
  const load = async () => { try { setError(""); const [a, p, c] = await Promise.all([window.nexo.listAutomations(), window.nexo.listAutomationPresets(), window.nexo.listAutomationActions()]); setRows(a as AutomationViewModel[]); setPresets(p as AutomationPreset[]); setCatalog(c as AutomationActionCatalogItem[]); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar as automações."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const attention = rows.filter(a => a.status === "attention" || a.status === "waiting_approval" || a.consecutiveFailures > 0);
  const filtered = useMemo(() => rows.filter(a => { const text = `${a.name} ${a.description ?? ""} ${a.triggerLabel} ${a.actionSummary}`.toLowerCase(); const state = filter === "Todas" || (filter === "Ativas" && ["active", "running"].includes(a.status)) || (filter === "Pausadas" && a.status === "paused") || (filter === "Atenção" && attention.some(x => x.id === a.id)) || (filter === "E-mail" && a.trigger.type === "email.received") || (filter === "Agenda" && a.trigger.type.startsWith("calendar")) || (filter === "Arquivos" && a.trigger.type.startsWith("file.")) || (filter === "Sistema" && a.trigger.type === "system.threshold"); return state && text.includes(query.toLowerCase()); }), [rows, query, filter, attention]);
  const action = async (work: () => Promise<unknown>) => { try { setError(""); const result = await work() as AutomationExecutionResult | AutomationViewModel; await load(); if (result && "conversationId" in result && result.conversationId) { useAppStore.getState().setPage("Assistente"); await useAssistantStore.getState().sync(); useAssistantStore.getState().selectSession(result.conversationId); } } catch (e) { setError(e instanceof Error ? e.message : "A operação falhou."); } };
  const stats = [[rows.filter(a => ["active", "running"].includes(a.status)).length, "Ativas", "ok"], [attention.length, "Atenção", "warn"], [rows.filter(a => a.status === "paused").length, "Pausadas", "muted"], [rows.filter(a => a.nextRunAt && new Date(a.nextRunAt).getTime() - Date.now() < 86400000).length, "Próximas", "info"]] as const;
  return <div className="automationPage"><header className="automationHeader"><div><span className="automationEyebrow">AUTOMATION CENTER</span><h1>Automações</h1><p>Rotinas trabalhando por você.</p></div><button className="automationPrimary" onClick={() => setBuilder({})}><Plus size={16}/> Nova automação</button></header>
    {error && <div className="automationError"><AlertTriangle size={16}/>{error}<button onClick={() => setError("")}><X size={15}/></button></div>}
    <section className="automationStats">{stats.map(([value, label, tone]) => <div key={label} className={tone}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <section className="automationToolbar"><label><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar automações..."/></label><div className="automationFilters">{["Todas", "Ativas", "Atenção", "Pausadas", "E-mail", "Agenda", "Arquivos", "Sistema"].map(x => <button className={filter === x ? "active" : ""} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div></section>
    {attention.length > 0 && <section className="attentionSection"><h2>Precisa da sua atenção</h2>{attention.map(a => <article key={a.id}><AlertTriangle/><div><b>{a.name}</b><p>{a.status === "waiting_approval" ? "Há uma ação aguardando sua aprovação." : `${a.consecutiveFailures || "Esta"} falha(s) precisa(m) de revisão.`}</p></div><button className="ghost" onClick={() => setDetails(a)}>Revisar <ChevronRight size={14}/></button></article>)}</section>}
    <section className="automationSection"><div className="sectionTitle"><h2>Suas automações</h2><span>{filtered.length} rotina{filtered.length === 1 ? "" : "s"}</span></div>{loading ? <div className="automationGrid">{[1,2,3].map(i => <div className="automationSkeleton" key={i}/>)}</div> : filtered.length ? <div className="automationGrid">{filtered.map(a => <Card key={a.id} item={a} open={() => setDetails(a)} action={action}/>)}</div> : <div className="automationEmpty"><Sparkles size={28}/><h3>Ainda não há automações</h3><p>Faça o Nexo trabalhar mesmo quando você não estiver conversando com ele.</p><button onClick={() => setBuilder({})}><Plus size={15}/> Criar primeira automação</button></div>}</section>
    <section className="automationSection presets"><div className="sectionTitle"><div><h2>Comece com um modelo</h2><p>Personalize uma rotina pronta antes de ativá-la.</p></div></div><div className="presetGrid">{presets.slice(0, 6).map(p => <article key={p.id}><span>{p.icon || "✨"}</span><h3>{p.title}</h3><p>{p.description}</p><button className="ghost" onClick={() => setBuilder(p)}>Usar modelo <ChevronRight size={14}/></button></article>)}</div></section>
    {builder && <Builder preset={builder as AutomationPreset} catalog={catalog} close={() => setBuilder(null)} done={async () => { setBuilder(null); await load(); }} fail={setError}/>} {details && <Details item={details} close={() => setDetails(null)} action={action}/>}</div>;
}

function Card({ item, open, action }: { item: AutomationViewModel; open: () => void; action: (f: () => Promise<unknown>) => Promise<void> }) { const [menu, setMenu] = useState(false); return <article className="automationCard" onClick={open} tabIndex={0} role="button" onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); open(); } }}><div className="cardTop"><span className="automationIcon" aria-hidden="true">{item.icon || "✨"}</span><span className={`automationStatus ${item.status}`}>{item.status === "running" && <i/>}{status[item.status]}</span><button className="menuButton" aria-label={`Ações de ${item.name}`} onClick={e => { e.stopPropagation(); setMenu(!menu); }}><MoreHorizontal size={18}/></button>{menu && <div className="automationMenu" onClick={e => e.stopPropagation()}><button onClick={() => void action(() => window.nexo.runAutomation(item.id))}><CirclePlay/> Executar agora</button><button onClick={() => void action(() => window.nexo.testAutomation(item.id))}><TestTube2/> Testar</button><button onClick={() => void action(() => window.nexo.duplicateAutomation(item.id))}><Copy/> Duplicar</button><button onClick={() => void action(() => window.nexo.toggleAutomation(item.id, !item.enabled))}>{item.enabled ? <Pause/> : <Play/>}{item.enabled ? "Pausar" : "Ativar"}</button><button className="danger" onClick={() => confirm(`Excluir “${item.name}”?`) && void action(() => window.nexo.removeAutomation(item.id))}><Trash2/> Excluir</button></div>}</div><h3>{item.name}</h3><p>{item.description || "Automação configurada no Nexo."}</p><div className="automationFlow"><span><Clock3/> {item.triggerLabel}</span><b>↓</b><span><Sparkles/> {item.actionSummary}</span></div><footer><span>{item.lastRunStatus === "success" ? <Check/> : item.lastRunStatus === "failed" ? <X/> : <History/>}{ago(item.lastRunAt)}</span><span>{item.nextRunAt ? `Próxima: ${new Date(item.nextRunAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}` : "Monitoramento contínuo"}</span></footer></article>; }

function Builder({ preset, catalog, close, done, fail }: { preset: AutomationPreset; catalog: AutomationActionCatalogItem[]; close: () => void; done: () => Promise<void>; fail: (message: string) => void }) {
  const source = preset?.automation;
  const [step, setStep] = useState(0), [name, setName] = useState(source?.name ?? ""), [description, setDescription] = useState(source?.description ?? ""), [trigger, setTrigger] = useState<Record<string, unknown>>(source?.trigger ?? { type: "manual" }), [conditions, setConditions] = useState<Array<{ id: string; field: string; operator: string; value: string }>>((source?.conditions ?? []) as Array<{ id: string; field: string; operator: string; value: string }>), [conditionOperator, setConditionOperator] = useState(String(source?.conditionOperator ?? "AND")), [actions, setActions] = useState<Array<{ id: string; type: string; config: Record<string, unknown> }>>(source?.actions ?? []), [saving, setSaving] = useState(false);
  const types = ["manual", "schedule", "interval", "email.received", "file.created", "file.changed", "calendar.before_event", "system.threshold"];
  const field = (key: string, value: unknown) => setTrigger(current => ({ ...current, [key]: value }));
  const addAction = (type: string) => setActions(current => [...current, { id: `action-${Date.now()}-${current.length}`, type, config: {} }]);
  const save = async (enabled: boolean, test = false) => { const input = { name: name.trim(), description: description.trim() || undefined, icon: preset?.icon || "sparkles", enabled, trigger, conditions, conditionOperator, actions, output: { type: "chat", conversationMode: "automation" }, policy: source?.policy ?? { maxConcurrentRuns: 1, retries: { enabled: true, count: 2 }, onRepeatedFailure: "pause" } }; if (!input.name || !actions.length) { fail("Informe um nome e adicione ao menos uma ação."); return; } try { setSaving(true); const created = await window.nexo.createAutomationV2(input as any) as AutomationViewModel; if (test) await window.nexo.testAutomation(created.id); await done(); } catch (e) { fail(e instanceof Error ? e.message : "Não foi possível salvar a automação."); } finally { setSaving(false); } };
  return <div className="automationOverlay" role="dialog" aria-modal="true"><section className="automationBuilder"><header><div><span className="automationEyebrow">NOVA AUTOMAÇÃO</span><h2>Quando → Se → Faça → Revisar</h2></div><button className="menuButton" onClick={close}><X/></button></header><div className="builderSteps">{["Quando", "Se", "Faça", "Revisar"].map((x, i) => <button key={x} className={i === step ? "active" : ""} onClick={() => setStep(i)}>{i + 1} {x}</button>)}</div>
    {step === 0 && <div className="builderBody"><h3>Quando isso deve acontecer?</h3><label>Nome da automação<input value={name} onChange={e => setName(e.target.value)} placeholder="Ex.: Monitorar GitHub"/></label><label>Descrição opcional<input value={description} onChange={e => setDescription(e.target.value)} placeholder="Explique o que esta rotina faz"/></label><div className="triggerChoices">{types.map(type => <button key={type} className={trigger.type === type ? "chosen" : ""} onClick={() => setTrigger(type === "schedule" ? { type, mode: "daily", time: "09:00" } : type === "interval" ? { type, minutes: 60 } : type === "email.received" ? { type, connectionId: "", pollIntervalMinutes: 5 } : type.startsWith("file") ? { type, path: "", debounceMs: 1500 } : { type })}>{type === "manual" ? "Execução manual" : type === "schedule" ? "Horário" : type === "interval" ? "Intervalo" : type === "email.received" ? "Novo e-mail" : type === "system.threshold" ? "Sistema" : type === "calendar.before_event" ? "Antes de compromisso" : "Arquivo alterado"}</button>)}</div>{trigger.type === "schedule" && <label>Horário<input type="time" value={String(trigger.time ?? "09:00")} onChange={e => field("time", e.target.value)}/></label>}{trigger.type === "interval" && <label>Intervalo em minutos<input type="number" min="1" value={String(trigger.minutes ?? 60)} onChange={e => field("minutes", Number(e.target.value))}/></label>}{(trigger.type === "file.created" || trigger.type === "file.changed") && <label>Pasta monitorada<input value={String(trigger.path ?? "")} onChange={e => field("path", e.target.value)} placeholder="C:\\Pasta"/></label>}</div>}
    {step === 1 && <div className="builderBody"><h3>Executar somente se...</h3><div className="conditionMode">{["AND", "OR"].map(mode => <button key={mode} className={conditionOperator === mode ? "chosen" : ""} onClick={() => setConditionOperator(mode)}>{mode === "AND" ? "Todas as condições" : "Qualquer condição"}</button>)}</div>{conditions.map((condition, index) => <div className="conditionRow" key={condition.id}><input aria-label={`Campo ${index + 1}`} value={condition.field} placeholder="Campo (ex.: assunto)" onChange={e => setConditions(list => list.map(c => c.id === condition.id ? { ...c, field: e.target.value } : c))}/><select aria-label="Operador" value={condition.operator} onChange={e => setConditions(list => list.map(c => c.id === condition.id ? { ...c, operator: e.target.value } : c))}><option value="contains">contém</option><option value="equals">é igual a</option><option value="notEquals">não é</option><option value="exists">existe</option></select><input aria-label="Valor" value={condition.value} placeholder="Valor" onChange={e => setConditions(list => list.map(c => c.id === condition.id ? { ...c, value: e.target.value } : c))}/><button className="removeCondition" onClick={() => setConditions(list => list.filter(c => c.id !== condition.id))}><X size={14}/></button></div>)}<button className="addCondition" onClick={() => setConditions(list => [...list, { id: `condition-${Date.now()}`, field: "", operator: "contains", value: "" }])}><Plus size={14}/> Adicionar condição</button>{!conditions.length && <p className="builderMuted">Sem condições: a automação será executada sempre que o gatilho acontecer.</p>}</div>}
    {step === 2 && <div className="builderBody"><h3>O que o Nexo deve fazer?</h3><div className="actionChoices">{catalog.map(item => <button key={item.id} className={actions.some(a => a.type === item.id) ? "chosen" : ""} onClick={() => addAction(item.id)}><span>{item.icon}</span><b>{item.title}</b><small>{item.description}</small><em className={item.risk}>{item.risk === "read" ? "Somente leitura" : item.risk === "sensitive" ? "Ação sensível" : "Pode alterar dados"}</em></button>)}</div><div className="selectedActions">{actions.map((a, index) => { const item = catalog.find(x => x.id === a.type); return <div key={a.id} className="selectedAction"><b>{index + 1}. {item?.title ?? a.type}</b><button aria-label="Remover ação" onClick={() => setActions(current => current.filter(x => x.id !== a.id))}><Trash2 size={14}/></button>{item?.fields.map(field => <label key={field.key}>{field.label}<input value={String(a.config[field.key] ?? "")} required={field.required} placeholder={field.placeholder} onChange={e => setActions(current => current.map(x => x.id === a.id ? { ...x, config: { ...x.config, [field.key]: e.target.value } } : x))}/></label>)}</div>; })}</div></div>}
    {step === 3 && <div className="builderBody review"><h3>{name || "Sua automação"}</h3><dl><dt>Quando</dt><dd>{String(trigger.type ?? "manual")}</dd><dt>Faça</dt><dd>{actions.map(a => catalog.find(x => x.id === a.type)?.title ?? a.type).join(" → ") || "Nenhuma ação"}</dd><dt>Saída</dt><dd>Notificação no Nexo</dd><dt>Segurança</dt><dd>{actions.some(a => catalog.find(x => x.id === a.type)?.risk !== "read") ? "⚠ Pode solicitar aprovação" : "✓ Somente leitura"}</dd></dl></div>}
    <footer className="builderFooter"><button className="ghost" onClick={() => step ? setStep(step - 1) : close()}>{step ? "← Voltar" : "Cancelar"}</button>{step < 3 ? <button onClick={() => setStep(step + 1)}>Continuar <ChevronRight size={15}/></button> : <><button className="ghost" disabled={saving} onClick={() => void save(false, true)}><TestTube2 size={15}/> Testar</button><button disabled={saving} onClick={() => void save(true)}>Ativar automação</button></>}</footer></section></div>;
}

function Details({ item, close, action }: { item: AutomationViewModel; close: () => void; action: (f: () => Promise<unknown>) => Promise<void> }) { const [runs, setRuns] = useState<Array<{ id: string; status: string; startedAt: string; durationMs?: number; summary?: string; error?: string }>>([]); useEffect(() => { void window.nexo.listAutomationRuns(item.id).then(r => setRuns(r as typeof runs)); const onKey = (e: KeyboardEvent) => e.key === "Escape" && close(); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [item.id, close]); return <div className="automationOverlay drawerOverlay" onMouseDown={e => e.target === e.currentTarget && close()}><section className="automationBuilder details" role="dialog" aria-modal="true" aria-label={`Detalhes de ${item.name}`}><header><div><span className="automationEyebrow">AUTOMAÇÃO</span><h2>{item.name}</h2><p>{item.description}</p></div><button className="menuButton" aria-label="Fechar detalhes" onClick={close}><X/></button></header><div className="detailActions"><button onClick={() => void action(() => window.nexo.runAutomation(item.id))}><CirclePlay size={15}/> Executar agora</button><button className="ghost" onClick={() => void action(() => window.nexo.testAutomation(item.id))}><TestTube2 size={15}/> Testar</button></div><div className="builderBody review"><dl><dt>Quando</dt><dd>{item.triggerLabel}</dd><dt>Faz</dt><dd>{item.actionSummary}</dd><dt>Última execução</dt><dd>{ago(item.lastRunAt)}</dd><dt>Próxima</dt><dd>{item.nextRunAt ? new Date(item.nextRunAt).toLocaleString("pt-BR") : "Monitorando continuamente"}</dd></dl><h3>Histórico</h3>{runs.length ? <div className="runList">{runs.map(r => <div key={r.id}><span className={r.status}>{r.status === "success" ? "✓" : r.status === "failed" ? "✕" : "⚠"}</span><b>{new Date(r.startedAt).toLocaleString("pt-BR")}</b><small>{r.durationMs ? `${r.durationMs} ms` : r.summary || r.error || r.status}</small></div>)}</div> : <p className="builderMuted">Ainda não há execuções registradas.</p>}</div></section></div>; }
