import { useEffect, useMemo, useState } from "react";
import type { CapabilityGrant, ConnectionAccount, ConnectionCapability, ConnectionDiagnosticSnapshot, ConnectionProvider } from "@nexo/shared";

const allCapabilities:ConnectionCapability[]=["email.read","email.send","email.modify","calendar.read","calendar.write"];
const capabilityLabels:Record<ConnectionCapability,string>={"email.read":"Ler e-mails","email.send":"Enviar e-mails","email.modify":"Alterar e-mails","calendar.read":"Ler agenda","calendar.write":"Alterar agenda"};
const googleScopeByCapability:Record<ConnectionCapability,string>={"email.read":"https://www.googleapis.com/auth/gmail.readonly","email.send":"https://www.googleapis.com/auth/gmail.send","email.modify":"https://www.googleapis.com/auth/gmail.modify","calendar.read":"https://www.googleapis.com/auth/calendar.readonly","calendar.write":"https://www.googleapis.com/auth/calendar"};
type OAuthConfiguration={googleClientId:string;microsoftClientId:string;microsoftTenant:string;googleConfigured:boolean;microsoftConfigured:boolean;googleClientSecretConfigured:boolean};
const emptyConfiguration:OAuthConfiguration={googleClientId:"",microsoftClientId:"",microsoftTenant:"common",googleConfigured:false,microsoftConfigured:false,googleClientSecretConfigured:false};

export function Connections(){
  const[accounts,setAccounts]=useState<ConnectionAccount[]>([]);
  const[configuration,setConfiguration]=useState<OAuthConfiguration>(emptyConfiguration);
  const[googleClientSecret,setGoogleClientSecret]=useState("");
  const[showGoogleSecret,setShowGoogleSecret]=useState(false);
  const[busy,setBusy]=useState<ConnectionProvider|"settings"|"secret"|null>(null);
  const[error,setError]=useState<string|null>(null);
  const[notice,setNotice]=useState<string|null>(null);
  const[googleCapabilities,setGoogleCapabilities]=useState<ConnectionCapability[]>(["email.read"]);
  const[diagnostics,setDiagnostics]=useState<Record<string,ConnectionDiagnosticSnapshot|undefined>>({});

  const reload=async()=>{const[nextAccounts,nextConfiguration]=await Promise.all([window.nexo.listConnections(),window.nexo.getConnectionConfiguration()]);setAccounts(nextAccounts);setConfiguration(nextConfiguration);};
  useEffect(()=>{void reload().catch(e=>setError(errorText(e)));},[]);

  async function saveConfiguration(){setBusy("settings");setError(null);setNotice(null);try{const next=await window.nexo.saveConnectionConfiguration({googleClientId:configuration.googleClientId,googleClientSecret:googleClientSecret.trim()||undefined,microsoftClientId:configuration.microsoftClientId,microsoftTenant:configuration.microsoftTenant});setConfiguration(next);setGoogleClientSecret("");setShowGoogleSecret(false);setNotice("Configuração OAuth salva. O Client Secret do Google foi armazenado criptografado neste computador.");}catch(e){setError(errorText(e));}finally{setBusy(null);}}
  async function removeGoogleSecret(){if(!window.confirm("Remover o Client Secret do Google? As contas Google conectadas precisarão ser autorizadas novamente."))return;setBusy("secret");setError(null);setNotice(null);try{await window.nexo.deleteGoogleClientSecret();await reload();setNotice("Client Secret removido. Configure uma nova credencial antes de reconectar o Google.");}catch(e){setError(errorText(e));}finally{setBusy(null);}}
  async function connect(provider:ConnectionProvider,capabilities:ConnectionCapability[]){setBusy(provider);setError(null);setNotice(null);try{const account=await window.nexo.connect(provider,capabilities) as ConnectionAccount;await reload();if(account.status==="degraded")setNotice(`${provider==="google"?"Google":"Microsoft"} conectado parcialmente. As permissões válidas continuam disponíveis; abra Diagnóstico para ver exatamente o que o provedor concedeu.`);else if(account.status==="reauthorization-required")setNotice("A conta foi identificada, mas nenhuma capability solicitada ficou operacional. Abra Diagnóstico antes de reautorizar.");else setNotice(`${provider==="google"?"Google":"Microsoft"} conectado e validado.`);}catch(e){setError(errorText(e));}finally{setBusy(null);}}
  async function testConnection(provider:ConnectionProvider,id:string){setBusy(provider);setError(null);setNotice(null);try{await window.nexo.testConnection(id);await reload();setDiagnostics(current=>({...current,[id]:undefined}));setNotice("Conexão revalidada. Scopes concedidos e disponibilidade das APIs foram reconciliados.");}catch(e){setError(errorText(e));await reload().catch(()=>undefined);}finally{setBusy(null);}}
  async function setCapabilities(provider:ConnectionProvider,id:string,capabilities:ConnectionCapability[]){if(!capabilities.length)return;setBusy(provider);setError(null);setNotice(null);try{await window.nexo.setConnectionCapabilities(id,capabilities);await reload();setDiagnostics(current=>({...current,[id]:undefined}));setNotice("Permissões desejadas atualizadas e reconciliadas com o Google.");}catch(e){setError(errorText(e));await reload().catch(()=>undefined);}finally{setBusy(null);}}
  async function showDiagnostics(id:string){try{const value=await window.nexo.connectionDiagnostics(id) as ConnectionDiagnosticSnapshot;setDiagnostics(current=>({...current,[id]:value}));}catch(e){setError(errorText(e));}}

  return <div>
    <header><div><h1>Conexões</h1><p>Configure credenciais OAuth e acompanhe separadamente o que foi solicitado, concedido e realmente validado.</p></div></header>
    {error&&<p className="notice error">{error}</p>}{notice&&<p className="notice success">{notice}</p>}
    <section className="panel settings oauthSetup">
      <h3>Google OAuth</h3>
      <p className="muted">O Client ID fica nas configurações locais. O Client Secret é armazenado pelo processo principal com a criptografia segura do sistema e nunca é devolvido ao React.</p>
      <label>Client ID do Google<input value={configuration.googleClientId} placeholder="…apps.googleusercontent.com" onChange={event=>setConfiguration(current=>({...current,googleClientId:event.target.value}))}/></label>
      <label>Client Secret do Google<div className="secretInputRow"><input type={showGoogleSecret?"text":"password"} value={googleClientSecret} placeholder={configuration.googleClientSecretConfigured?"Client Secret já armazenado — deixe em branco para manter":"GOCSPX-…"} onChange={event=>setGoogleClientSecret(event.target.value)} autoComplete="new-password"/><button type="button" onClick={()=>setShowGoogleSecret(value=>!value)} disabled={!googleClientSecret}>{showGoogleSecret?"Ocultar":"Mostrar"}</button></div></label>
      <p className="muted">{configuration.googleClientSecretConfigured?"✓ Client Secret armazenado com segurança neste computador.":"Client Secret ainda não configurado."}</p>
      <div className="rowActions"><button onClick={()=>void saveConfiguration()} disabled={busy!==null}>{busy==="settings"?"Salvando…":"Salvar credenciais"}</button>{configuration.googleClientSecretConfigured&&<button onClick={()=>void removeGoogleSecret()} disabled={busy!==null}>{busy==="secret"?"Removendo…":"Remover Client Secret"}</button>}</div>
      <div className="oauthHelp"><b>Antes de conectar</b><ul><li>Use um cliente OAuth do tipo aplicativo para computador.</li><li>Habilite Gmail API e, se usar agenda, Google Calendar API no mesmo projeto do Client ID.</li><li>Em Testing, inclua a conta em Test users.</li></ul></div>
      <GooglePermissions capabilities={googleCapabilities}/>
    </section>
    <section className="panel settings oauthSetup"><h3>Microsoft OAuth</h3><label>Client ID do Microsoft<input value={configuration.microsoftClientId} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" onChange={event=>setConfiguration(current=>({...current,microsoftClientId:event.target.value}))}/></label><label>Tenant Microsoft<input value={configuration.microsoftTenant} placeholder="common" onChange={event=>setConfiguration(current=>({...current,microsoftTenant:event.target.value}))}/></label><button onClick={()=>void saveConfiguration()} disabled={busy!==null}>{busy==="settings"?"Salvando…":"Salvar configuração Microsoft"}</button></section>
    <section className="panel list"><StaticConnection name="Ollama" detail="IA local"/>{(["google","microsoft"] as const).map(provider=><ProviderRow key={provider} provider={provider} configured={provider==="google"?configuration.googleConfigured:configuration.microsoftConfigured} account={accounts.find(account=>account.provider===provider)} busy={busy===provider} onConnect={connect} onTest={testConnection} onSetCapabilities={setCapabilities} onDiagnostics={showDiagnostics} diagnostics={accounts.find(account=>account.provider===provider)?diagnostics[accounts.find(account=>account.provider===provider)!.id]:undefined} reload={reload} selectedCapabilities={provider==="google"?googleCapabilities:undefined} onSelectedCapabilitiesChange={provider==="google"?setGoogleCapabilities:undefined}/>)}</section>
  </div>;
}

function ProviderRow({provider,configured,account,busy,onConnect,onTest,onSetCapabilities,onDiagnostics,diagnostics,reload,selectedCapabilities,onSelectedCapabilitiesChange}:{provider:ConnectionProvider;configured:boolean;account?:ConnectionAccount;busy:boolean;onConnect:(provider:ConnectionProvider,capabilities:ConnectionCapability[])=>Promise<void>;onTest:(provider:ConnectionProvider,id:string)=>Promise<void>;onSetCapabilities:(provider:ConnectionProvider,id:string,capabilities:ConnectionCapability[])=>Promise<void>;onDiagnostics:(id:string)=>Promise<void>;diagnostics?:ConnectionDiagnosticSnapshot;reload:()=>Promise<void>;selectedCapabilities?:ConnectionCapability[];onSelectedCapabilitiesChange?:(capabilities:ConnectionCapability[])=>void}){
  const[localSelected,setLocalSelected]=useState<ConnectionCapability[]>(provider==="google"?["email.read"]:["email.read","calendar.read"]);
  const[managing,setManaging]=useState(false);const[draft,setDraft]=useState<ConnectionCapability[]>([]);
  const title=provider==="google"?"Google":"Microsoft",selected=selectedCapabilities??localSelected,setSelected=onSelectedCapabilitiesChange??setLocalSelected;
  const toggleSelected=(capability:ConnectionCapability)=>setSelected(selected.includes(capability)?selected.filter(item=>item!==capability):[...selected,capability]);
  const status=statusPresentation(account,configured);
  useEffect(()=>{if(!account){setManaging(false);setDraft([]);}},[account]);
  async function disconnect(){if(!account)return;if(!window.confirm(`Desconectar ${title}? Os tokens salvos para esta conta serão removidos deste computador.`))return;await window.nexo.disconnect(account.id);await reload();}
  function openManage(){if(!account)return;setDraft(account.requestedCapabilities?.length?account.requestedCapabilities:account.capabilities);setManaging(true);}
  const toggleDraft=(capability:ConnectionCapability)=>setDraft(current=>current.includes(capability)?current.filter(item=>item!==capability):[...current,capability]);

  return <div className="row providerRow"><div><b>{title}</b><span>{account?.accountEmail??account?.lastError??(configured?"Pronto para autorizar no navegador padrão":"Credenciais OAuth ainda não configuradas")}</span>
    {account?<><div className="capabilities grantedCapabilities">{allCapabilities.map(capability=><CapabilityState key={capability} capability={capability} grant={account.capabilityGrants?.find(item=>item.capability===capability)} operational={account.capabilities.includes(capability)} requested={(account.requestedCapabilities??account.capabilities).includes(capability)}/>)}</div>
      {account.lastValidatedAt&&<small>Última validação: {new Date(account.lastValidatedAt).toLocaleString("pt-BR")}</small>}{account.lastRefreshAt&&<small> · Última renovação: {new Date(account.lastRefreshAt).toLocaleString("pt-BR")}</small>}
      {managing&&<div className="capabilities"><b>Permissões desejadas</b>{allCapabilities.map(capability=><label key={capability}><input type="checkbox" checked={draft.includes(capability)} onChange={()=>toggleDraft(capability)}/>{capabilityLabels[capability]}</label>)}<div className="rowActions"><button disabled={busy||!draft.length} onClick={()=>void onSetCapabilities(provider,account.id,draft).then(()=>setManaging(false))}>{busy?"Autorizando…":"Salvar e reconciliar"}</button><button onClick={()=>setManaging(false)} disabled={busy}>Cancelar</button></div></div>}
      {diagnostics&&<DiagnosticsPanel value={diagnostics}/>}</>:<div className="capabilities">{allCapabilities.map(capability=><label key={capability}><input type="checkbox" checked={selected.includes(capability)} onChange={()=>toggleSelected(capability)}/>{capabilityLabels[capability]}</label>)}</div>}</div>
    <div className="rowActions"><span className={`tag ${status.success?"success":"pending"}`}>{status.label}</span>{account?<><button onClick={()=>void onTest(provider,account.id)} disabled={busy}>{busy?"Testando…":"Testar"}</button><button onClick={()=>void onDiagnostics(account.id)} disabled={busy}>Diagnóstico</button><button onClick={openManage} disabled={busy}>Gerenciar permissões</button>{(account.status==="reauthorization-required"||account.status==="expired")&&<button onClick={openManage} disabled={busy||!configured}>Reautorizar</button>}<button onClick={()=>void disconnect()} disabled={busy}>Desconectar</button></>:<button onClick={()=>void onConnect(provider,selected)} disabled={busy||!configured||!selected.length}>{busy?"Abrindo…":configured?`Conectar ${title}`:"Configure as credenciais"}</button>}</div></div>;
}

function CapabilityState({capability,grant,operational,requested}:{capability:ConnectionCapability;grant?:CapabilityGrant;operational:boolean;requested:boolean}){
  const symbol=operational?"✓":requested?"✗":"○";
  const detail=grant?.validated?grant.grantedByScope:grant?.providerMessage??(requested?"Ainda não validada":"Não solicitada");
  return <span title={detail}>{symbol} {capabilityLabels[capability]}{requested&&detail?<small> · {detail}</small>:null}</span>;
}

function DiagnosticsPanel({value}:{value:ConnectionDiagnosticSnapshot}){
  const safe={provider:value.provider,status:value.status,accountEmail:value.accountEmail,oauthClientId:value.oauthClientId,configuredClientId:value.configuredClientId,clientMatches:value.clientMatches,tokenPresent:value.tokenPresent,refreshTokenPresent:value.refreshTokenPresent,scopeSource:value.scopeSource,grantedScopes:value.grantedScopes,requestedCapabilities:value.requestedCapabilities,capabilities:Object.fromEntries(value.capabilities.map(grant=>[grant.capability,{status:grant.status,granted:grant.granted,validated:grant.validated,grantedByScope:grant.grantedByScope,reason:grant.providerReason,message:grant.providerMessage,httpStatus:grant.httpStatus}]))};
  const text=JSON.stringify(safe,null,2);
  return <div className="oauthHelp"><b>Diagnóstico seguro</b><p className="muted">Não contém access token, refresh token nem Client Secret.</p><pre>{text}</pre><button type="button" onClick={()=>void navigator.clipboard.writeText(text)}>Copiar diagnóstico</button></div>;
}

function GooglePermissions({capabilities}:{capabilities:ConnectionCapability[]}){const[copied,setCopied]=useState<string|null>(null);const scopes=[...new Set(capabilities.map(capability=>googleScopeByCapability[capability]))];async function copy(scope:string){try{await navigator.clipboard.writeText(scope);setCopied(scope);}catch{setCopied(null);}}return <div className="oauthHelp googlePermissions"><b>Permissões necessárias no Google Cloud</b><p>O Nexo normaliza scopes redundantes no OAuth. A lista abaixo mostra os scopes correspondentes às funcionalidades escolhidas.</p>{scopes.map(scope=><div className="scopeRow" key={scope}><code>{scope}</code><button type="button" onClick={()=>void copy(scope)}>{copied===scope?"Copiado":"Copiar"}</button></div>)}<ul><li>Gmail API e Calendar API devem estar no mesmo projeto do Client ID.</li><li>Se o app estiver em Testing, inclua a conta em Test users.</li><li>O diagnóstico diferencia scope ausente de API que recusou um scope presente.</li></ul></div>;}
function statusPresentation(account:ConnectionAccount|undefined,configured:boolean){if(!account)return{label:configured?"pronto":"configurar",success:configured};if(account.status==="connected")return{label:"conectado",success:true};if(account.status==="degraded")return{label:"conectado parcialmente",success:false};if(account.status==="refreshing")return{label:"renovando",success:false};if(account.status==="validating")return{label:"validando",success:false};if(account.status==="expired")return{label:"expirado",success:false};if(account.status==="reauthorization-required")return{label:"reautorizar",success:false};return{label:"atenção",success:false};}
function errorText(value:unknown){return value instanceof Error?value.message:String(value);}
function StaticConnection({name,detail}:{name:string;detail:string}){return <div className="row"><div><b>{name}</b><span>{detail}</span></div><span className="tag success">ativo</span></div>;}
