import { Suspense, lazy, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, CalendarClock, CheckCircle2, Command, Gauge, LayoutGrid, Pencil, Plus, RefreshCw, Sparkles, X } from "lucide-react";
import { GadgetCard } from "../components/dashboard/GadgetCard";
import { useDashboardStore } from "../stores/dashboard";
import { useAppStore } from "../stores/app";
import { useAssistantStore } from "../stores/assistant";
import { useVisualStore } from "../stores/visual";
import { useDeveloperDiagnosticsEnabled } from "../hooks/useDeveloperDiagnostics";
import { userFacingError } from "../utils/user-facing-error";
import { Tooltip } from "../components/ui/Tooltip";
import type { DashboardGadgetInstance, GadgetSize } from "@nexo/shared";
import "./dashboard.css";
import "./dashboard-tokens.css";
import "./dashboard-motion.css";

const NexoOrb = lazy(() => import("../components/ai/NexoOrb").then(module => ({ default: module.NexoOrb })));
const GadgetCatalog = lazy(() => import("../components/dashboard/GadgetCatalog").then(module => ({ default: module.GadgetCatalog })));

export function Dashboard(){
  const {layout,catalog,data,loading,error,editing,load,refresh,add,remove,configure,resize,reorder,setEditing}=useDashboardStore(),setPage=useAppStore(state=>state.setPage),status=useAppStore(state=>state.status) as any,tasks=useAssistantStore(state=>state.tasks),setVisual=useVisualStore(state=>state.set),diagnostics=useDeveloperDiagnosticsEnabled();
  const [catalogOpen,setCatalogOpen]=useState(false),[configuring,setConfiguring]=useState<DashboardGadgetInstance>(),[clock,setClock]=useState(new Date());
  useEffect(()=>{void load();const timer=window.setInterval(()=>setClock(new Date()),60_000);return()=>clearInterval(timer);},[load]);
  useEffect(()=>{const active=tasks.filter(task=>["queued","running","waiting_approval"].includes(task.status)).sort((a,b)=>(Date.parse(b.startedAt??"")||0)-(Date.parse(a.startedAt??"")||0))[0];if(active)setVisual(active.status==="waiting_approval"?"awaiting-approval":active.progressText?"responding":"planning",active.statusMessage);else if(status?.llm&&!status.llm.ok)setVisual("offline");else setVisual("idle");},[tasks,status,setVisual]);
  useEffect(()=>{const unsubscribe=window.nexo.onTaskEvent(()=>{const state=useDashboardStore.getState();for(const instance of state.layout){if(["tasks","approvals","automations"].includes(instance.gadgetId))void state.refresh(instance);}});return()=>{unsubscribe();};},[]);
  useEffect(()=>{const unsubscribe=window.nexo.onVisualEvent((event:any)=>{if(["run.completed","run.failed","run.cancelled"].includes(event?.type)){for(const instance of useDashboardStore.getState().layout.filter(item=>item.gadgetId==="activity"))void useDashboardStore.getState().refresh(instance);}});return()=>{unsubscribe();};},[]);
  useEffect(()=>{const timers=layout.map(instance=>{const definition=catalog.find(item=>item.id===instance.gadgetId);if(!definition?.refreshInterval)return undefined;return window.setInterval(()=>void useDashboardStore.getState().refresh(instance),definition.refreshInterval);}).filter((item):item is number=>item!==undefined);return()=>timers.forEach(clearInterval);},[layout,catalog]);
  useEffect(()=>{const move=(event:Event)=>{const detail=(event as CustomEvent<{from:string;to:string}>).detail;void reorder(detail.from,detail.to);};window.addEventListener("nexo:dashboard:move",move);return()=>window.removeEventListener("nexo:dashboard:move",move);},[reorder]);
  const greeting=useMemo(()=>{const hour=clock.getHours();return hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite";},[clock]);
  const activeTasks=layout.find(item=>item.gadgetId==="tasks");const pendingApprovals=layout.find(item=>item.gadgetId==="approvals");const macros=layout.find(item=>item.gadgetId==="automations");const ai=layout.find(item=>item.gadgetId==="ai-status");
  const signals=[{icon:<Sparkles/>,label:"MODELO LOCAL",value:data[ai?.instanceId??""]?.data?.model??status?.settings?.model??"Verificando…",note:data[ai?.instanceId??""]?.data?.connected?"Conectado":"Local"},{icon:<LayoutGrid/>,label:"TAREFAS ATIVAS",value:data[activeTasks?.instanceId??""]?.data?.length??"—",note:"Agentes trabalhando"},{icon:<Gauge/>,label:"MACROS ATIVAS",value:data[macros?.instanceId??""]?.data?.enabled??"—",note:"Rotinas configuradas"},{icon:<CheckCircle2/>,label:"APROVAÇÕES",value:data[pendingApprovals?.instanceId??""]?.data?.length??"—",note:"Aguardando você"}];
  const moveBy=(instanceId:string,direction:-1|1)=>{const index=layout.findIndex(item=>item.instanceId===instanceId),next=layout[index+direction];if(next)void reorder(instanceId,next.instanceId);};
  const refreshAll=useCallback(()=>{void load();},[load]);
  return <div className="dashboardPage">
    <header className="dashboardPageHeader"><div><span className="dashboardEyebrow">NEXO / COMMAND CENTER <i>·</i> {clock.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).toUpperCase()}</span><h1>{greeting}. <em>O Nexo está com você.</em></h1><p>Seu trabalho, seus agentes e as informações que você escolheu em um só lugar.</p></div><div className={`dashboardConnection ${status?.llm?.ok?"online":""}`}><span/><b>{status?.llm?.ok?"IA local pronta":"IA local"}</b><small>{status?.settings?.model??"verificando conexão"}</small></div></header>
    <section className="dashboardHero" aria-label="Núcleo neural Nexo"><div className="heroAmbient"/><div className="dashboardHeroCopy"><span className="heroKicker"><i/> NEXO CORE <b>01 / INTELIGÊNCIA</b></span><h2>Ideias em movimento.<br/><em>Resultados no seu ritmo.</em></h2><p>Acompanhe a inteligência local, veja o que está acontecendo e escolha seu próximo passo.</p><div className="dashboardHeroActions"><button className="dashboardPrimary" onClick={()=>setPage("Assistente")}>Conversar com Nexo <ArrowRight size={16}/></button><button className="dashboardSecondary" onClick={()=>setPage("Escritório")}>Abrir escritório <ArrowUpRight size={15}/></button></div><span className="heroPrivacy"><i/> Seus dados permanecem neste computador</span></div><div className="dashboardOrb"><Suspense fallback={<div className="dashboardOrbLoading" role="status" aria-label="Carregando núcleo neural" style={{width:"min(100%,385px)",height:295,borderRadius:"50%",background:"radial-gradient(circle at 50% 48%, #a294ff20 0, #a294ff08 25%, transparent 64%)",boxShadow:"inset 0 0 50px #a294ff08"}}/>}><NexoOrb compact/></Suspense><div className="orbAnnotation annotationTop"><i/> NÚCLEO ATIVO</div><div className="orbAnnotation annotationBottom">LOCAL <b>·</b> PRIVADO <b>·</b> SEU</div></div><div className="heroCoordinates" aria-hidden="true"><span>LATÊNCIA LOCAL <b>◆</b></span><span>01 ───────── 04</span></div></section>
    <section className="dashboardSignals" aria-label="Sinais do Nexo">{signals.map(signal=><article key={signal.label}><span className="signalIcon">{signal.icon}</span><div><small>{signal.label}</small><strong>{signal.value}</strong><span>{signal.note}</span></div><i className="signalTrace"/></article>)}</section>
    <section className="dashboardWorkspace"><header className="dashboardWorkspaceHeader"><div><span className="dashboardEyebrow">SEU ESPAÇO</span><h2>Meu dashboard <small>{layout.length} gadgets</small></h2></div><div className="dashboardToolbar"><Tooltip content="Atualizar dashboard"><button type="button" className="dashboardIconButton" onClick={refreshAll} aria-label="Atualizar dashboard"><RefreshCw size={15}/></button></Tooltip>{editing&&<button className="dashboardSecondary" onClick={()=>setEditing(false)}><CheckCircle2 size={15}/> Concluir edição</button>}<button className={editing?"dashboardSecondary":"dashboardPrimary"} onClick={()=>editing?setEditing(false):setEditing(true)}>{editing?<><X size={15}/> Cancelar edição</>:<><Pencil size={15}/> Editar layout</>}</button><button className="dashboardAddButton" onClick={()=>setCatalogOpen(true)}><Plus size={16}/> Adicionar gadget</button></div></header>
      {error&&layout.length>0&&<div className="dashboardStale" role="status"><span>{userFacingError(error,"Não foi possível atualizar. Exibindo os dados anteriores.",diagnostics)}</span><button type="button" onClick={refreshAll}>Tentar novamente</button></div>}
      {loading&&layout.length>0&&<div className="dashboardRefreshStatus" role="status">Atualizando dashboard…</div>}
      {loading&&layout.length===0?<div className="dashboardGrid" role="status" aria-label="Carregando dashboard">{[1,2,3,4].map(index=><div key={index} className="gadgetSkeleton"/>)}</div>:error&&layout.length===0?<div className="dashboardLoadError" role="alert"><h3>Não foi possível carregar o dashboard</h3><p>{userFacingError(error,"Tente novamente para carregar suas informações.",diagnostics)}</p><button type="button" onClick={refreshAll}>Tentar novamente</button></div>:layout.length===0?<div className="dashboardEmpty"><Sparkles/><h3>Monte um dashboard que seja seu</h3><p>Adicione gadgets locais ou escolha as informações online que quer acompanhar.</p><button className="dashboardPrimary" onClick={()=>setCatalogOpen(true)}><Plus size={15}/> Adicionar primeiro gadget</button></div>:<div className={`dashboardGrid${editing?" isEditing":""}`}>
        {layout.map((item,index)=>{const definition=catalog.find(value=>value.id===item.gadgetId);if(!definition)return null;return <GadgetCard key={item.instanceId} item={item} definition={definition} result={data[item.instanceId]} editing={editing} onResize={(size:GadgetSize)=>void resize(item.instanceId,size)} onRemove={()=>void remove(item.instanceId)} onMove={direction=>moveBy(item.instanceId,direction)} onRefresh={()=>refresh(item,true)} onConfigure={()=>setConfiguring(item)}/>;})}
      </div>}
    </section>
    <footer className="dashboardPageFooter"><span><Command size={12}/> NEXO DESKTOP</span><span>LOCAL-FIRST INTELLIGENCE <i>·</i> SOB SEU CONTROLE</span><button onClick={()=>setPage("Configurações")}>Configurações <ArrowUpRight size={12}/></button></footer>
    {(catalogOpen||configuring)&&<Suspense fallback={null}><GadgetCatalog catalog={catalog} initial={configuring} close={()=>{setCatalogOpen(false);setConfiguring(undefined);}} add={add} save={configure}/></Suspense>}
  </div>;
}
