import type { MacroPreset } from "@nexo/shared";

export const emailMacroPresets: MacroPreset[] = [
  { id:"unread-email-summary",version:1,category:"email",title:"Resumir e-mails não lidos",description:"Cria um resumo dos e-mails não lidos em dias úteis.",icon:"mail",requiredCapabilities:["email.read"],macro:{name:"Resumir e-mails não lidos",icon:"mail",prompt:"Resuma meus e-mails não lidos e destaque os que exigem ação.",trigger:{type:"schedule",mode:"weekdays",time:"09:00"},conditions:[],actions:[{id:"summary",type:"nexo.command",config:{command:"Resuma meus e-mails não lidos e destaque os que exigem ação."}}],output:{type:"chat",conversationMode:"automation"}} },
  { id:"important-email",version:1,category:"email",title:"Avisar e-mail importante",description:"Avisa quando chegar uma mensagem importante.",icon:"mail-warning",requiredCapabilities:["email.read"],macro:{name:"E-mail importante",icon:"mail-warning",trigger:{type:"email.received",connectionId:"",categories:["primary"],pollIntervalMinutes:5},conditions:[{id:"unread",field:"message.isRead",operator:"equals",value:false}],actions:[{id:"summary",type:"email.summary",config:{source:"$trigger.data.message"}},{id:"notify",type:"notification.show",config:{title:"E-mail importante",content:"$actions.summary"}}]} },
  { id:"email-from-person",version:1,category:"email",title:"Avisar e-mail de uma pessoa",description:"Filtra mensagens por remetente.",icon:"user-round",requiredCapabilities:["email.read"],macro:{name:"E-mail de uma pessoa",icon:"user-round",trigger:{type:"email.received",connectionId:"",categories:["primary"],pollIntervalMinutes:5},conditions:[{id:"sender",field:"message.from",operator:"contains",value:""}],actions:[{id:"notify",type:"notification.show",config:{title:"Novo e-mail",content:"$trigger.data.message.subject"}}]} },
  { id:"email-with-attachment",version:1,category:"email",title:"Avisar quando chegar anexo",description:"Avisa somente mensagens que possuem anexos.",icon:"paperclip",requiredCapabilities:["email.read"],macro:{name:"E-mail com anexo",icon:"paperclip",trigger:{type:"email.received",connectionId:"",pollIntervalMinutes:5},conditions:[{id:"attachment",field:"message.hasAttachments",operator:"equals",value:true}],actions:[{id:"notify",type:"notification.show",config:{title:"Novo anexo recebido",content:"$trigger.data.message.subject"}}]} },
  { id:"github-workflow-failed",version:1,category:"email",title:"Avisar falhas do GitHub",description:"Detecta notificações de workflow com falha.",icon:"github",requiredCapabilities:["email.read"],macro:{name:"Falhas do GitHub",icon:"github",trigger:{type:"email.received",connectionId:"",categories:["primary","updates"],pollIntervalMinutes:5},conditions:[{id:"sender",field:"message.from",operator:"contains",value:"github"},{id:"subject",field:"message.subject",operator:"contains",value:"failed"}],conditionOperator:"AND",actions:[{id:"summary",type:"email.summary",config:{source:"$trigger.data.message"}},{id:"notify",type:"notification.show",config:{title:"Workflow com falha",content:"$actions.summary"}}]} }
];
