import { useCallback,useEffect,useRef,useState } from "react";
import type { OfficeStationId } from "@nexo/shared";
import { OfficeEngine } from "./engine/OfficeEngine";
import { useOfficeStore } from "./state/office-store";
import { useOfficePerformance } from "./hooks/useOfficePerformance";
import { AgentFlowView } from "./ui/AgentFlowView";
export function PixelOfficeCanvas({onAgent,onStation}:{onAgent:()=>void;onStation:(station:OfficeStationId)=>void}){
  const host=useRef<HTMLDivElement>(null),engine=useRef<OfficeEngine|undefined>(undefined),event=useOfficeStore(state=>state.event),zoom=useOfficeStore(state=>state.zoom),reduced=useOfficeStore(state=>state.reducedMotion),developer=useOfficeStore(state=>state.developerMode);const[error,setError]=useState<string>(),[debug,setDebug]=useState<Record<string,unknown>>({});
  useEffect(()=>{const instance=new OfficeEngine();engine.current=instance;let active=true;void instance.mount(host.current!,onAgent,onStation).catch(reason=>active&&setError(reason instanceof Error?reason.message:String(reason)));return()=>{active=false;instance.destroy();engine.current=undefined;};},[onAgent,onStation]);
  useEffect(()=>{if(event)engine.current?.consume(event);},[event?.eventId]);useEffect(()=>engine.current?.setReducedMotion(reduced),[reduced]);useEffect(()=>engine.current?.setDeveloperMode(developer),[developer]);useEffect(()=>{if(host.current)engine.current?.setZoom(host.current,zoom);},[zoom]);const visibility=useCallback((visible:boolean)=>engine.current?.setVisible(visible),[]);useOfficePerformance(visibility);useEffect(()=>{if(!developer)return;const timer=window.setInterval(()=>setDebug(engine.current?.debug()??{}),500);return()=>window.clearInterval(timer);},[developer]);
  useEffect(()=>{const timer=window.setInterval(()=>{const metrics=engine.current?.debug();if(!metrics)return;for(const [name,key] of [["pixel_office.fps","fps"],["pixel_office.queue_size","queue"],["pixel_office.navigation_ms","navigationMs"],["pixel_office.navigation_failures","navigationFailures"]] as const){const value=metrics[key];if(typeof value==="number")void window.nexo.recordMetric(name,value);}},5000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{const exportGrid=()=>{const data=engine.current?.exportGrid();if(!data)return;const url=URL.createObjectURL(new Blob([data],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="navigation-grid.json";anchor.click();URL.revokeObjectURL(url);};window.addEventListener("nexo:office:export-grid",exportGrid);return()=>window.removeEventListener("nexo:office:export-grid",exportGrid);},[]);
  if(error)return <div className="officeFallback" role="alert"><h2>A visualização Pixel Office não está disponível.</h2><p>Usando o modo simplificado.</p><small>{error}</small><AgentFlowView/><button onClick={()=>location.reload()}>Recarregar</button></div>;
  return <div className="officeCanvas" ref={host} role="img" aria-label={`Escritório virtual do Nexo. Estado atual: ${event?.label??"Disponível"}`}>{developer&&<pre className="developerOverlay">{Object.entries(debug).map(([key,value])=>`${key}: ${typeof value==="object"?JSON.stringify(value):value}`).join("\n")}</pre>}</div>;
}
