import type { ConnectionService } from "../connections/service.js";
export type CalendarEvent = { id:string; calendarId:string; title:string; start:string; end:string; timeZone?:string; location?:string; attendees?:{email:string;name?:string;status?:string}[]; description?:string; meetingUrl?:string };
export class CalendarService {
  constructor(private connections: ConnectionService) {}
  async list(connectionId:string, start:string, end:string) { const account=this.connections.get(connectionId); if(!account) throw new Error("Conexão não encontrada."); const token=await this.connections.accessToken(connectionId,"calendar.read"); return account.provider === "google" ? listGoogle(token,start,end) : listMicrosoft(token,start,end); }
  async create(connectionId:string, event:Omit<CalendarEvent,"id"|"calendarId">) { const account=this.connections.get(connectionId); if(!account) throw new Error("Conexão não encontrada."); const token=await this.connections.accessToken(connectionId,"calendar.write"); const response=account.provider === "google" ? await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({summary:event.title,start:{dateTime:event.start,timeZone:event.timeZone},end:{dateTime:event.end,timeZone:event.timeZone},location:event.location,description:event.description,attendees:event.attendees?.map(x=>({email:x.email,displayName:x.name}))})}) : await fetch("https://graph.microsoft.com/v1.0/me/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({subject:event.title,start:{dateTime:event.start,timeZone:event.timeZone ?? "UTC"},end:{dateTime:event.end,timeZone:event.timeZone ?? "UTC"},location:event.location?{displayName:event.location}:undefined,body:event.description?{contentType:"text",content:event.description}:undefined,attendees:event.attendees?.map(x=>({emailAddress:{address:x.email,name:x.name},type:"required"}))})}); if(!response.ok) throw new Error("O provedor recusou a criação do evento."); return normalize(account.provider, await response.json() as any); }
}
async function listGoogle(token:string,start:string,end:string) { const query=new URLSearchParams({timeMin:start,timeMax:end,singleEvents:"true",orderBy:"startTime"}); const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?${query}`,{headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível consultar o Google Calendar."); return ((await response.json()) as any).items.map((item:any)=>normalize("google",item)); }
async function listMicrosoft(token:string,start:string,end:string) { const response=await fetch(`https://graph.microsoft.com/v1.0/me/calendarView?${new URLSearchParams({startDateTime:start,endDateTime:end,"$top":"100"})}`,{headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível consultar o Microsoft Calendar."); return ((await response.json()) as any).value.map((item:any)=>normalize("microsoft",item)); }
function normalize(provider:"google"|"microsoft", item:any):CalendarEvent { return provider === "google" ? {id:item.id,calendarId:"primary",title:item.summary ?? "(sem título)",start:item.start?.dateTime ?? item.start?.date,end:item.end?.dateTime ?? item.end?.date,timeZone:item.start?.timeZone,location:item.location,description:item.description,meetingUrl:item.hangoutLink,attendees:item.attendees?.map((x:any)=>({email:x.email,name:x.displayName,status:x.responseStatus}))} : {id:item.id,calendarId:item.calendar?.id ?? "primary",title:item.subject ?? "(sem título)",start:item.start?.dateTime,end:item.end?.dateTime,timeZone:item.start?.timeZone,location:item.location?.displayName,description:item.bodyPreview,meetingUrl:item.onlineMeeting?.joinUrl,attendees:item.attendees?.map((x:any)=>({email:x.emailAddress?.address,name:x.emailAddress?.name,status:x.status?.response}))}; }
