import type { ConnectionService } from "../connections/service.js";
export type CalendarEvent = { id:string; calendarId:string; title:string; start:string; end:string; timeZone?:string; location?:string; attendees?:{email:string;name?:string;status?:string}[]; description?:string; meetingUrl?:string; recurrence?:string[]; allDay?:boolean; reminders?:number[] };
export type CalendarInfo = { id:string; name:string; primary?:boolean; timeZone?:string };
export class CalendarService {
  constructor(private connections: ConnectionService) {}
  async list(connectionId:string, start:string, end:string): Promise<CalendarEvent[]> { const account=this.connections.get(connectionId); if(!account) throw new Error("Conexão não encontrada."); const token=await this.connections.accessToken(connectionId,"calendar.read"); return account.provider === "google" ? listGoogle(token,start,end) : listMicrosoft(token,start,end); }
  async listCalendars(connectionId:string): Promise<CalendarInfo[]> { const account=this.connections.get(connectionId); if(!account) throw new Error("Conexão não encontrada."); const token=await this.connections.accessToken(connectionId,"calendar.read"); const response=account.provider === "google" ? await fetch("https://www.googleapis.com/calendar/v3/users/me/calendarList",{headers:{Authorization:`Bearer ${token}`}}) : await fetch("https://graph.microsoft.com/v1.0/me/calendars?$select=id,name,isDefaultCalendar",{headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível listar os calendários."); const data=await response.json() as any; return account.provider === "google" ? (data.items??[]).map((item:any)=>({id:item.id,name:item.summary??"(sem nome)",primary:item.primary,timeZone:item.timeZone})) : (data.value??[]).map((item:any)=>({id:item.id,name:item.name??"(sem nome)",primary:item.isDefaultCalendar})); }
  async create(connectionId:string, event:Omit<CalendarEvent,"id"|"calendarId">) { const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.write"); const response=await fetch(account.provider === "google" ? "https://www.googleapis.com/calendar/v3/calendars/primary/events" : "https://graph.microsoft.com/v1.0/me/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(eventPayload(account.provider,event))}); if(!response.ok) throw new Error("O provedor recusou a criação do evento."); return normalize(account.provider, await response.json() as any); }
  async get(connectionId:string, eventId:string) { return this.eventRequest(connectionId,eventId,"GET"); }
  async update(connectionId:string, eventId:string, event:Partial<Omit<CalendarEvent,"id"|"calendarId">>) {
    const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.write"); const response=await fetch(eventUrl(account.provider,eventId),{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(eventPayload(account.provider,event))}); if(!response.ok) throw new Error("O provedor recusou a atualização do evento."); return normalize(account.provider,await response.json() as any);
  }
  async delete(connectionId:string,eventId:string) { const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.write"); const response=await fetch(eventUrl(account.provider,eventId),{method:"DELETE",headers:{Authorization:`Bearer ${token}`}}); if(!response.ok && response.status!==204) throw new Error("O provedor recusou o cancelamento do evento."); return {id:eventId,deleted:true}; }
  async rsvp(connectionId:string,eventId:string,response:"accept"|"tentative"|"decline") { const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.write"); const url=account.provider === "google" ? `${eventUrl("google",eventId)}/attendees/me` : `https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(eventId)}/${response}`; const method=account.provider === "google" ? "PATCH" : "POST"; const body=account.provider === "google" ? JSON.stringify({responseStatus:response === "accept" ? "accepted" : response === "decline" ? "declined" : "tentative"}) : JSON.stringify({}); const result=await fetch(url,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body}); if(!result.ok) throw new Error("Não foi possível responder ao convite."); return {id:eventId,response}; }
  async createMeeting(connectionId:string,event:Omit<CalendarEvent,"id"|"calendarId">) { const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.write"); const payload=eventPayload(account.provider,event); if(account.provider==="google") Object.assign(payload,{conferenceData:{createRequest:{requestId:crypto.randomUUID()}},conferenceDataVersion:1}); else Object.assign(payload,{isOnlineMeeting:true,onlineMeetingProvider:"teamsForBusiness"}); const response=await fetch(account.provider==="google" ? "https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1" : "https://graph.microsoft.com/v1.0/me/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload)}); if(!response.ok) throw new Error("O provedor recusou a criação da reunião."); return normalize(account.provider,await response.json() as any); }
  async findFreeTime(connectionId:string, start:string, end:string, durationMinutes:number) {
    if (!Number.isInteger(durationMinutes) || durationMinutes < 5 || durationMinutes > 24 * 60) throw new Error("Duração inválida.");
    const rangeStart = new Date(start).getTime(), rangeEnd = new Date(end).getTime(); if (!Number.isFinite(rangeStart) || !Number.isFinite(rangeEnd) || rangeEnd <= rangeStart) throw new Error("Período inválido.");
    const events = await this.list(connectionId, start, end); const duration = durationMinutes * 60_000;
    const busy = events.map(event => ({ start: Math.max(rangeStart, new Date(event.start).getTime()), end: Math.min(rangeEnd, new Date(event.end).getTime()) })).filter(slot => Number.isFinite(slot.start) && Number.isFinite(slot.end) && slot.end > slot.start).sort((a,b) => a.start - b.start);
    const slots: Array<{start:string;end:string}> = []; let cursor = rangeStart;
    for (const slot of busy) { if (slot.start - cursor >= duration) slots.push({ start:new Date(cursor).toISOString(), end:new Date(cursor + duration).toISOString() }); cursor = Math.max(cursor, slot.end); }
    if (rangeEnd - cursor >= duration) slots.push({ start:new Date(cursor).toISOString(), end:new Date(cursor + duration).toISOString() });
    return slots.slice(0, 10);
  }
  private account(connectionId:string) { const account=this.connections.get(connectionId); if(!account) throw new Error("Conexão não encontrada."); return account; }
  private async eventRequest(connectionId:string,eventId:string,method:"GET") { const account=this.account(connectionId); const token=await this.connections.accessToken(connectionId,"calendar.read"); const response=await fetch(eventUrl(account.provider,eventId),{method,headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível consultar o evento."); return normalize(account.provider,await response.json() as any); }
}
function eventUrl(provider:"google"|"microsoft",eventId:string) { const encoded=encodeURIComponent(eventId); return provider === "google" ? `https://www.googleapis.com/calendar/v3/calendars/primary/events/${encoded}` : `https://graph.microsoft.com/v1.0/me/events/${encoded}`; }
function eventPayload(provider:"google"|"microsoft",event:Partial<Omit<CalendarEvent,"id"|"calendarId">>) { const date=(value:string)=>value.slice(0,10); return provider === "google" ? {summary:event.title,start:event.start?(event.allDay?{date:date(event.start)}:{dateTime:event.start,timeZone:event.timeZone}):undefined,end:event.end?(event.allDay?{date:date(event.end)}:{dateTime:event.end,timeZone:event.timeZone}):undefined,location:event.location,description:event.description,attendees:event.attendees?.map(x=>({email:x.email,displayName:x.name})),recurrence:event.recurrence,reminders:event.reminders?{useDefault:false,overrides:event.reminders.map(minutes=>({method:"popup",minutes}))}:undefined} : {subject:event.title,start:event.start?{dateTime:event.start,timeZone:event.timeZone??"UTC"}:undefined,end:event.end?{dateTime:event.end,timeZone:event.timeZone??"UTC"}:undefined,isAllDay:event.allDay,recurrence:microsoftRecurrence(event.recurrence,event.start),location:event.location?{displayName:event.location}:undefined,body:event.description?{contentType:"text",content:event.description}:undefined,attendees:event.attendees?.map(x=>({emailAddress:{address:x.email,name:x.name},type:"required"}))}; }
function microsoftRecurrence(rules:string[]|undefined,start:string|undefined) { const raw=rules?.find(rule=>rule.startsWith("RRULE:")); if(!raw||!start)return undefined; const parts=Object.fromEntries(raw.slice(6).split(";").map(pair=>pair.split("=",2))); const frequency=parts.FREQ?.toLowerCase(); const type=frequency==="daily"?"daily":frequency==="weekly"?"weekly":frequency==="monthly"?"absoluteMonthly":frequency==="yearly"?"absoluteYearly":undefined; if(!type) throw new Error("Recorrência não suportada pelo Microsoft Calendar."); const interval=Math.max(1,Number(parts.INTERVAL??1)); const pattern:any={type,interval}; if(type==="weekly") pattern.daysOfWeek=(parts.BYDAY??"").split(",").filter(Boolean).map((day:string)=>({MO:"monday",TU:"tuesday",WE:"wednesday",TH:"thursday",FR:"friday",SA:"saturday",SU:"sunday"} as Record<string,string>)[day]).filter(Boolean); if(type==="absoluteMonthly") pattern.dayOfMonth=Number(parts.BYMONTHDAY??new Date(start).getUTCDate()); if(type==="absoluteYearly") { pattern.dayOfMonth=Number(parts.BYMONTHDAY??new Date(start).getUTCDate()); pattern.month=Number(parts.BYMONTH??new Date(start).getUTCMonth()+1); } return {pattern,range:{type:"noEnd",startDate:start.slice(0,10)}}; }
async function listGoogle(token:string,start:string,end:string) { const query=new URLSearchParams({timeMin:start,timeMax:end,singleEvents:"true",orderBy:"startTime"}); const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?${query}`,{headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível consultar o Google Calendar."); return ((await response.json()) as any).items.map((item:any)=>normalize("google",item)); }
async function listMicrosoft(token:string,start:string,end:string) { const response=await fetch(`https://graph.microsoft.com/v1.0/me/calendarView?${new URLSearchParams({startDateTime:start,endDateTime:end,"$top":"100"})}`,{headers:{Authorization:`Bearer ${token}`}}); if(!response.ok) throw new Error("Não foi possível consultar o Microsoft Calendar."); return ((await response.json()) as any).value.map((item:any)=>normalize("microsoft",item)); }
function normalize(provider:"google"|"microsoft", item:any):CalendarEvent { return provider === "google" ? {id:item.id,calendarId:"primary",title:item.summary ?? "(sem título)",start:item.start?.dateTime ?? item.start?.date,end:item.end?.dateTime ?? item.end?.date,timeZone:item.start?.timeZone,location:item.location,description:item.description,meetingUrl:item.hangoutLink,attendees:item.attendees?.map((x:any)=>({email:x.email,name:x.displayName,status:x.responseStatus}))} : {id:item.id,calendarId:item.calendar?.id ?? "primary",title:item.subject ?? "(sem título)",start:item.start?.dateTime,end:item.end?.dateTime,timeZone:item.start?.timeZone,location:item.location?.displayName,description:item.bodyPreview,meetingUrl:item.onlineMeeting?.joinUrl,attendees:item.attendees?.map((x:any)=>({email:x.emailAddress?.address,name:x.emailAddress?.name,status:x.status?.response}))}; }
