import {BaseCheckpointSaver,type ChannelVersions,type Checkpoint,type CheckpointListOptions,type CheckpointTuple} from "@langchain/langgraph-checkpoint";
import type {CheckpointMetadata,PendingWrite} from "@langchain/langgraph-checkpoint";
import type {RunnableConfig} from "@langchain/core/runnables";
import type {NexoDatabase} from "../../database/db.js";

type Row={id:string;run_id:string;namespace:string;parent_id:string|null;state_json:string;metadata_json:string;writes_json:string;created_at:string};
export class NexoLangGraphCheckpointer extends BaseCheckpointSaver {
  constructor(private readonly db:NexoDatabase){super();}
  async getTuple(config:RunnableConfig):Promise<CheckpointTuple|undefined>{const {threadId,namespace,checkpointId}=identity(config);const row=checkpointId?this.db.get<Row>("SELECT * FROM agent_graph_checkpoints WHERE run_id=? AND namespace=? AND id=?",[threadId,namespace,checkpointId]):this.db.get<Row>("SELECT * FROM agent_graph_checkpoints WHERE run_id=? AND namespace=? ORDER BY created_at DESC LIMIT 1",[threadId,namespace]);return row?tuple(row):undefined;}
  async *list(config:RunnableConfig,options:CheckpointListOptions={}):AsyncGenerator<CheckpointTuple>{const {threadId,namespace}=identity(config);const before=options.before?.configurable?.checkpoint_id;const params:unknown[]=[threadId,namespace];let sql="SELECT * FROM agent_graph_checkpoints WHERE run_id=? AND namespace=?";if(before){sql+=" AND created_at<(SELECT created_at FROM agent_graph_checkpoints WHERE id=?)";params.push(before);}sql+=" ORDER BY created_at DESC";if(options.limit){sql+=" LIMIT ?";params.push(options.limit);}for(const row of this.db.all<Row>(sql,params)){const value=tuple(row);if(!options.filter||Object.entries(options.filter).every(([key,expected])=>(value.metadata as Record<string,unknown>)[key]===expected))yield value;}}
  async put(config:RunnableConfig,checkpoint:Checkpoint,metadata:CheckpointMetadata,_newVersions:ChannelVersions):Promise<RunnableConfig>{const {threadId,namespace}=identity(config),parentId=String(config.configurable?.checkpoint_id??"")||null,now=new Date().toISOString();this.db.run("INSERT OR REPLACE INTO agent_graph_checkpoints(id,run_id,namespace,parent_id,state_json,metadata_json,writes_json,created_at,status) VALUES(?,?,?,?,?,?,?,?,?)",[checkpoint.id,threadId,namespace,parentId,JSON.stringify(checkpoint),JSON.stringify(metadata),"[]",now,"ACTIVE"]);return{...config,configurable:{...config.configurable,thread_id:threadId,checkpoint_ns:namespace,checkpoint_id:checkpoint.id}};}
  async putWrites(config:RunnableConfig,writes:PendingWrite[],taskId:string):Promise<void>{const {threadId,namespace,checkpointId}=identity(config);if(!checkpointId)throw new Error("checkpoint_id é obrigatório para gravar writes.");const row=this.db.get<Row>("SELECT * FROM agent_graph_checkpoints WHERE run_id=? AND namespace=? AND id=?",[threadId,namespace,checkpointId]);if(!row)throw new Error("Checkpoint não encontrado.");const current=JSON.parse(row.writes_json) as Array<[string,string,unknown]>;writes.forEach(([channel,value])=>current.push([taskId,channel,value]));this.db.run("UPDATE agent_graph_checkpoints SET writes_json=? WHERE id=?",[JSON.stringify(current),checkpointId]);}
  prune(threadId:string,keep=5){const rows=this.db.all<{id:string}>("SELECT id FROM agent_graph_checkpoints WHERE run_id=? ORDER BY created_at DESC",[threadId]);for(const row of rows.slice(Math.max(1,keep)))this.db.run("DELETE FROM agent_graph_checkpoints WHERE id=?",[row.id]);}
}
function identity(config:RunnableConfig){const threadId=String(config.configurable?.thread_id??"");if(!threadId)throw new Error("thread_id é obrigatório.");return{threadId,namespace:String(config.configurable?.checkpoint_ns??""),checkpointId:config.configurable?.checkpoint_id?String(config.configurable.checkpoint_id):undefined};}
function tuple(row:Row):CheckpointTuple{return{config:{configurable:{thread_id:row.run_id,checkpoint_ns:row.namespace,checkpoint_id:row.id}},checkpoint:JSON.parse(row.state_json),metadata:JSON.parse(row.metadata_json),...(row.parent_id?{parentConfig:{configurable:{thread_id:row.run_id,checkpoint_ns:row.namespace,checkpoint_id:row.parent_id}}}:{}),pendingWrites:(JSON.parse(row.writes_json) as Array<[string,string,unknown]>).map(([task,channel,value])=>[task,channel,value])};}
