import type { ConnectionService } from "../connections/service.js";
import type { EmailDraft, EmailDraftInput, EmailMessage, EmailSearchQuery } from "./types.js";
import { randomUUID } from "node:crypto";

export class EmailService {
  constructor(private connections: ConnectionService) {}
  async search(input: EmailSearchQuery): Promise<EmailMessage[]> { const account = this.connections.get(input.connectionId); if (!account) throw new Error("Conexão não encontrada."); const token = await this.connections.accessToken(account.id, "email.read"); return account.provider === "google" ? searchGoogle(token, input) : searchMicrosoft(token, input); }
  async createDraft(input: EmailDraftInput): Promise<EmailDraft> { const account = this.connections.get(input.connectionId); if (!account) throw new Error("Conexão não encontrada."); await this.connections.accessToken(account.id, "email.send"); return { id: randomUUID(), provider: account.provider, message: input }; }
  async sendDraft(draft: EmailDraft) { const token = await this.connections.accessToken(draft.message.connectionId, "email.send"); if (draft.provider === "google") { const payload = [`To: ${draft.message.to.map(x=>x.email).join(", ")}`, `Subject: ${draft.message.subject}`, "", draft.message.bodyText].join("\r\n"); const raw = Buffer.from(payload).toString("base64url"); const response = await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send", { method:"POST", headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}, body:JSON.stringify({raw}) }); if (!response.ok) throw new Error("O Gmail recusou o envio."); return { ok:true, provider:"google" }; }
    const response = await fetch("https://graph.microsoft.com/v1.0/me/sendMail", { method:"POST", headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}, body:JSON.stringify({message:{subject:draft.message.subject,body:{contentType:"Text",content:draft.message.bodyText},toRecipients:draft.message.to.map(x=>({emailAddress:{address:x.email,name:x.name}})),ccRecipients:draft.message.cc?.map(x=>({emailAddress:{address:x.email,name:x.name}}))},saveToSentItems:true}) }); if (!response.ok) throw new Error("O Microsoft Graph recusou o envio."); return { ok:true, provider:"microsoft" };
  }
}
async function searchGoogle(token:string, input:EmailSearchQuery) { const query = new URLSearchParams({ maxResults:String(Math.min(input.maxResults ?? 20, 50)), q:[input.unread ? "is:unread" : "", input.query ?? ""].filter(Boolean).join(" ") }); const listed = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?${query}`, {headers:{Authorization:`Bearer ${token}`}}); if (!listed.ok) throw new Error("Não foi possível consultar o Gmail."); const messages = ((await listed.json()) as any).messages ?? []; return Promise.all(messages.slice(0,20).map(async ({id}:any) => { const response = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${id}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject`, {headers:{Authorization:`Bearer ${token}`}}); const item = await response.json() as any; const headers = Object.fromEntries((item.payload?.headers ?? []).map((h:any)=>[h.name.toLowerCase(),h.value])); return {id:item.id,provider:"google",threadId:item.threadId,from:{email:headers.from ?? ""},to:[{email:headers.to ?? ""}],subject:headers.subject ?? "(sem assunto)",receivedAt:new Date(Number(item.internalDate)).toISOString(),snippet:item.snippet,isUnread:(item.labelIds ?? []).includes("UNREAD"),hasAttachments:false} satisfies EmailMessage; })); }
async function searchMicrosoft(token:string, input:EmailSearchQuery) { const params = new URLSearchParams({ "$top":String(Math.min(input.maxResults ?? 20,50)), "$select":"id,subject,from,toRecipients,receivedDateTime,bodyPreview,isRead,hasAttachments" }); const response = await fetch(`https://graph.microsoft.com/v1.0/me/messages?${params}`, {headers:{Authorization:`Bearer ${token}`}}); if (!response.ok) throw new Error("Não foi possível consultar o Microsoft Graph."); return ((await response.json()) as any).value.map((item:any) => ({id:item.id,provider:"microsoft",from:{email:item.from?.emailAddress?.address ?? "",name:item.from?.emailAddress?.name},to:(item.toRecipients ?? []).map((x:any)=>({email:x.emailAddress.address,name:x.emailAddress.name})),subject:item.subject ?? "(sem assunto)",receivedAt:item.receivedDateTime,snippet:item.bodyPreview,isUnread:!item.isRead,hasAttachments:item.hasAttachments})); }
