import { parsePresentation } from "../chat/presentation/types.js";
import type { ChatPresentation } from "@nexo/shared";
import { v4 as uuid } from "uuid";
import type { NexoDatabase } from "../database/db.js";
import { ProgressPersistenceScheduler } from "./progress-persistence.js";
import { LLM_STREAM_CONTENT_STARTED, LLM_STREAM_THINKING_STARTED } from "../llm/stream-events.js";

export type BackgroundTaskStatus="queued"|"running"|"waiting_review"|"waiting_approval"|"completed"|"failed"|"cancelled";
export type BackgroundTask={presentation?:ChatPresentation;pendingApprovalId?:string;pendingReviewDraftId?:string;id:string;type:string;status:BackgroundTaskStatus;input:Record<string,unknown>;result?:unknown;error?:string;createdAt:string;startedAt?:string;finishedAt?:string;progressText?:string;statusMessage?:string;statusHistory?:string[];conversationId?:string;agentId?:string;runId?:string};
export type BackgroundTaskEvent={kind:"created"|"status"|"token"|"completed"|"failed"|"cancelled";taskId:string;task?:BackgroundTask;token?:string};
type TaskRow={id:string;type:string;status:BackgroundTaskStatus;input_json:string;result_json:string|null;error:string|null;created_at:string;started_at:string|null;finished_at:string|null;progress_json?:string|null;conversation_id?:string|null;agent_id?:string|null;run_id?:string|null};
type LiveProgress={presentation?:ChatPresentation;pendingApprovalId?:string;pendingReviewDraftId?:string;text:string;statusMessage:string;statusHistory:string[]};
export type TaskExecutionMetadata={conversationId?:string;agentId?:string;runId?:string};

export class BackgroundTaskService{
  private listeners=new Set<(event:BackgroundTaskEvent)=>void>();private liveProgress=new Map<string,LiveProgress>();private liveResults=new Map<string,unknown>();private liveErrors=new Map<string,string>();private progressPersistence:ProgressPersistenceScheduler;
  constructor(private db:NexoDatabase,private readonly isPrivate=()=>false){this.progressPersistence=new ProgressPersistenceScheduler(350,id=>this.persistProgress(id));}
  subscribe(listener:(event:BackgroundTaskEvent)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener);}private notify(event:BackgroundTaskEvent){for(const listener of this.listeners)listener(event);}
  recoverInterruptedTasks(){const now=new Date().toISOString();for(const row of this.db.all<TaskRow>("SELECT * FROM tasks WHERE status IN ('queued','running')")){this.db.run("UPDATE tasks SET status='failed', error=?, finished_at=? WHERE id=?",["A tarefa foi interrompida por um encerramento anterior do Nexo.",now,row.id]);}}
  create(type:string,input:Record<string,unknown>,metadata:TaskExecutionMetadata={},id=uuid()){const createdAt=new Date().toISOString();this.db.run("INSERT INTO tasks(id,type,status,input_json,result_json,error,created_at,started_at,finished_at,progress_json,conversation_id,agent_id,run_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,type,"queued",JSON.stringify(this.isPrivate()?{privateMode:true}:input),null,null,createdAt,null,null,JSON.stringify({text:"",statusMessage:"Na fila…",statusHistory:["Na fila…"]}),metadata.conversationId??null,metadata.agentId??null,metadata.runId??null]);this.liveProgress.set(id,{text:"",statusMessage:"Na fila…",statusHistory:["Na fila…"]});const task=this.get(id)!;this.notify({kind:"created",taskId:id,task});return task;}
  assignExecution(id:string,metadata:TaskExecutionMetadata){this.db.run("UPDATE tasks SET conversation_id=COALESCE(?,conversation_id),agent_id=COALESCE(?,agent_id),run_id=COALESCE(?,run_id) WHERE id=?",[metadata.conversationId??null,metadata.agentId??null,metadata.runId??null,id]);this.notify({kind:"status",taskId:id,task:this.get(id)});}
  markRunning(id:string){const current=this.get(id);const progress=this.progressFor(id);if(progress){progress.pendingApprovalId=undefined;progress.pendingReviewDraftId=undefined;for(const block of progress.presentation?.blocks??[])if(block.type==="approval"){const approval=this.db.get<{status:typeof block.status}>("SELECT status FROM approvals WHERE id=?",[block.approvalId]);if(approval)block.status=approval.status;}this.liveProgress.set(id,progress);}this.db.run("UPDATE tasks SET status='running', started_at=COALESCE(started_at,?) WHERE id=?",[new Date().toISOString(),id]);if(current?.status!=="running")this.setStatus(id,"Iniciando processamento local…");}
  setStatus(id:string,statusMessage:string){if(!this.isActive(id))return;const current=this.progressFor(id)??{text:"",statusMessage:"",statusHistory:[]};const history=[...current.statusHistory];if(statusMessage&&history.at(-1)!==statusMessage)history.push(statusMessage);this.liveProgress.set(id,{...current,statusMessage,statusHistory:history.slice(-8)});this.persistProgress(id);this.notify({kind:"status",taskId:id,task:this.get(id)});}
  appendProgress(id:string,token:string){if(!this.isActive(id))return;if(token===LLM_STREAM_THINKING_STARTED){this.setStatus(id,"Raciocinando localmente…");return;}if(token===LLM_STREAM_CONTENT_STARTED){this.setStatus(id,"Respondendo…");return;}const current=this.progressFor(id)??{text:"",statusMessage:"Gerando resposta…",statusHistory:["Gerando resposta…"]};this.liveProgress.set(id,{...current,text:current.text+token});this.progressPersistence.schedule(id);this.notify({kind:"token",taskId:id,token});}
  setPresentation(id:string,presentation:ChatPresentation){if(!this.isActive(id))return;const current=this.progressFor(id)??{text:"",statusMessage:"",statusHistory:[]};this.liveProgress.set(id,{...current,presentation});this.persistProgress(id);this.notify({kind:"status",taskId:id,task:this.get(id)});}
  replaceProgress(id:string,text:string){if(!this.isActive(id))return;const current=this.progressFor(id)??{text:"",statusMessage:"",statusHistory:[]};this.liveProgress.set(id,{...current,text});this.progressPersistence.schedule(id);}
  complete(id:string,result:unknown){const reviewDraftId=result&&typeof result==="object"&&"reviewDraftId" in result&&typeof (result as {reviewDraftId?:unknown}).reviewDraftId==="string"?(result as {reviewDraftId:string}).reviewDraftId:undefined;if(reviewDraftId){this.markWaitingReview(id,reviewDraftId);return;}this.progressPersistence.cancel(id);const privateMode=this.isPrivate();if(privateMode)this.liveResults.set(id,result);this.db.run("UPDATE tasks SET status='completed', result_json=?, finished_at=?, progress_json=? WHERE id=?",[privateMode?null:JSON.stringify(result),new Date().toISOString(),null,id]);this.liveProgress.delete(id);this.notify({kind:"completed",taskId:id,task:this.get(id)});}
  fail(id:string,error:unknown){this.progressPersistence.cancel(id);const message=error instanceof Error?error.message:String(error),privateMode=this.isPrivate();if(privateMode)this.liveErrors.set(id,message);this.db.run("UPDATE tasks SET status='failed', error=?, finished_at=?, progress_json=? WHERE id=?",[privateMode?"Tarefa privada falhou.":message,new Date().toISOString(),null,id]);this.liveProgress.delete(id);this.notify({kind:"failed",taskId:id,task:this.get(id)});}
  markWaitingReview(id:string,draftId:string){const current=this.progressFor(id)??{text:"",statusMessage:"",statusHistory:[]},statusMessage="Aguardando revisão do e-mail…";this.liveProgress.set(id,{...current,pendingApprovalId:undefined,pendingReviewDraftId:draftId,statusMessage,statusHistory:[...current.statusHistory,statusMessage].slice(-8)});this.db.run("UPDATE tasks SET status='waiting_review', progress_json=? WHERE id=?",[JSON.stringify(this.isPrivate()?{...this.liveProgress.get(id),presentation:undefined}:this.liveProgress.get(id)),id]);this.notify({kind:"status",taskId:id,task:this.get(id)});return draftId;}
  markWaitingApproval(id:string,approvalId:string){const current=this.progressFor(id)??{text:"",statusMessage:"",statusHistory:[]},statusMessage="Aguardando sua aprovação…";this.liveProgress.set(id,{...current,pendingReviewDraftId:undefined,pendingApprovalId:approvalId,statusMessage,statusHistory:[...current.statusHistory,statusMessage].slice(-8)});this.db.run("UPDATE tasks SET status='waiting_approval', progress_json=? WHERE id=?",[JSON.stringify(this.isPrivate()?{...this.liveProgress.get(id),presentation:undefined}:this.liveProgress.get(id)),id]);this.notify({kind:"status",taskId:id,task:this.get(id)});return approvalId;}
  cancel(id:string){const task=this.get(id);if(!task||!["queued","running","waiting_review","waiting_approval"].includes(task.status))return false;this.progressPersistence.cancel(id);this.db.run("UPDATE tasks SET status='cancelled', error=?, finished_at=?, progress_json=? WHERE id=?",["Cancelada pelo usuário.",new Date().toISOString(),null,id]);this.liveProgress.delete(id);this.notify({kind:"cancelled",taskId:id,task:this.get(id)});return true;}
  get(id:string):BackgroundTask|undefined{const row=this.db.get<TaskRow>("SELECT * FROM tasks WHERE id=?",[id]);if(!row)return;const task=this.toTask(row);return{...task,result:this.liveResults.get(id)??task.result,error:this.liveErrors.get(id)??task.error};}
  list(limit=50){return this.db.all<TaskRow>("SELECT * FROM tasks ORDER BY created_at DESC LIMIT ?",[limit]).map(row=>this.toTask(row));}
  listActive(){return this.db.all<TaskRow>("SELECT * FROM tasks WHERE status IN ('queued','running','waiting_review','waiting_approval') ORDER BY created_at ASC").map(row=>this.toTask(row));}
  listByConversation(conversationId:string,limit=50){return this.db.all<TaskRow>("SELECT * FROM tasks WHERE conversation_id=? ORDER BY created_at DESC LIMIT ?",[conversationId,limit]).map(row=>this.toTask(row));}
  private toTask(row:TaskRow):BackgroundTask{const progress=this.progressFor(row.id);return{id:row.id,type:row.type,status:row.status,input:JSON.parse(row.input_json||"{}"),result:row.result_json?JSON.parse(row.result_json):undefined,error:row.error??undefined,createdAt:row.created_at,startedAt:row.started_at??undefined,finishedAt:row.finished_at??undefined,presentation:parsePresentation(progress?.presentation),pendingApprovalId:progress?.pendingApprovalId,pendingReviewDraftId:progress?.pendingReviewDraftId,progressText:progress?.text,statusMessage:progress?.statusMessage,statusHistory:progress?.statusHistory,conversationId:row.conversation_id??undefined,agentId:row.agent_id??undefined,runId:row.run_id??undefined};}
  private progressFor(id:string):LiveProgress|undefined{const live=this.liveProgress.get(id);if(live)return live;const row=this.db.get<{progress_json:string|null}>("SELECT progress_json FROM tasks WHERE id=?",[id]);try{return row?.progress_json?JSON.parse(row.progress_json):undefined;}catch{return undefined;}}
  private persistProgress(id:string){const progress=this.liveProgress.get(id);if(progress)this.db.run("UPDATE tasks SET progress_json=? WHERE id=?",[JSON.stringify(this.isPrivate()?{...progress,presentation:undefined}:progress),id]);}
  private isActive(id:string){return Boolean(this.db.get("SELECT id FROM tasks WHERE id=? AND status IN ('queued','running','waiting_review','waiting_approval')",[id]));}
}
