import { z } from "zod";
import type { DocumentAssistantService } from "../../documents/assistant.js";
import type { DocumentService } from "../../documents/service.js";
import { DocumentWriterService } from "../../documents/writer.js";
import type { ToolDefinition } from "../types.js";

export function documentTools(documents: DocumentService, assistant: DocumentAssistantService, writer = new DocumentWriterService()): ToolDefinition[] {
  const ids = z.array(z.string().min(1)).min(1);
  const idsOrPath=<T extends z.ZodRawShape>(shape:T)=>z.object({documentIds:ids.optional(),path:z.string().min(1).optional()}).extend(shape).refine(input=>Boolean(input.documentIds?.length||input.path),"Informe documentIds ou path.");
  const resolveIds=async(input:{documentIds?:string[];path?:string})=>input.documentIds??[(await documents.importFromTrustedPicker(input.path!)).id];
  return [
    { name:"document_import_path",description:"Importa e indexa um arquivo local para uso pelas ferramentas documentais",domain:"document",operation:"import_path",risk:"SAFE_WRITE",permissions:["filesystem.read"],pathFields:["path"],mutatesState:true,mutationSafety:{idempotency:"none",reconciliation:"supported"},agent:{outputTrust:"sensitive_local"},inputSchema:z.object({path:z.string().min(1)}),async execute({path}){const document=await documents.importFromTrustedPicker(path);return{ok:true,summary:`Documento importado e indexado: ${document.name}`,data:{documentId:document.id,path,name:document.name,mimeType:document.mimeType,status:document.status}};} },
    { name:"document_get",description:"Obtém metadados e conteúdo indexado de um documento anexado",domain:"document",operation:"get",risk:"READ",permissions:[],agent:{outputTrust:"sensitive_local"},inputSchema:z.object({documentId:z.string()}),async execute({documentId}){const document=documents.get(documentId);if(!document)return{ok:false,summary:"Documento não encontrado.",error:"DOCUMENT_NOT_FOUND"};return{ok:true,summary:`Documento carregado: ${document.name}`,data:{document,chunks:documents.getChunks(documentId)}};} },
    { name:"document_search",description:"Busca trechos relevantes em documentos anexados ou em um path local confiável",domain:"document",operation:"search",risk:"READ",permissions:["filesystem.read"],pathFields:["path"],agent:{outputTrust:"sensitive_local"},inputSchema:idsOrPath({query:z.string().min(1)}),async execute(input){const documentIds=await resolveIds(input);const matches=await documents.retrieve(documentIds,input.query);return{ok:true,summary:`${matches.length} trecho(s) relevante(s) encontrado(s).`,data:matches};} },
    { name:"document_summarize",description:"Resume documentos anexados ou importa automaticamente um path local confiável",domain:"document",operation:"summarize",risk:"READ",permissions:["filesystem.read"],pathFields:["path"],agent:{outputTrust:"sensitive_local"},inputSchema:idsOrPath({instruction:z.string().default("Resuma os pontos principais.")}),async execute(input,context){const documentIds=await resolveIds(input);const result=await assistant.process(documentIds,`Resuma o documento. ${input.instruction}`,{signal:context?.signal});return{ok:true,summary:"Resumo do documento concluído.",data:{...result,documentIds}};} },
    { name:"document_extract",description:"Extrai informações de documentos anexados ou de um path local confiável",domain:"document",operation:"extract",risk:"READ",permissions:["filesystem.read"],pathFields:["path"],agent:{outputTrust:"sensitive_local"},inputSchema:idsOrPath({instruction:z.string().min(1)}),async execute(input,context){const documentIds=await resolveIds(input);const result=await assistant.process(documentIds,`Extraia do documento: ${input.instruction}`,{signal:context?.signal});return{ok:true,summary:"Extração documental concluída.",data:{...result,documentIds}};} },
    { name:"document_compare",description:"Compara exatamente dois documentos anexados",domain:"document",operation:"compare",risk:"READ",permissions:[],agent:{outputTrust:"sensitive_local"},inputSchema:z.object({documentIds:z.array(z.string()).length(2),instruction:z.string().default("Compare os documentos.")}),async execute({documentIds,instruction},context){const result=await assistant.process(documentIds,`Compare os documentos. ${instruction}`,{signal:context?.signal});return{ok:true,summary:"Comparação documental concluída.",data:result};} },
    { name:"document_create",description:"Cria e valida um documento TXT, Markdown ou DOCX novo",domain:"document",operation:"create",risk:"SAFE_WRITE",permissions:["filesystem.write"],pathFields:["path"],mutatesState:true,mutationSafety:{idempotency:"nexo",reconciliation:"supported"},inputSchema:z.object({path:z.string(),format:z.enum(["txt","md","docx"]),title:z.string().optional(),content:z.string()}),async execute(input,context){const data=await writer.write({...input,createOnly:true,executionId:context?.executionId});return{ok:true,summary:`Documento criado e validado: ${data.path}`,data};} },
    { name:"document_transform",description:"Transforma documentos anexados e grava uma versão reduzida validada",domain:"document",operation:"transform",risk:"SENSITIVE",permissions:["filesystem.write"],pathFields:["outputPath"],mutatesState:true,mutationSafety:{idempotency:"nexo",reconciliation:"supported"},inputSchema:z.object({sourceDocumentIds:ids,instruction:z.string().min(1),outputPath:z.string(),format:z.enum(["txt","md","docx"])}),async execute({sourceDocumentIds,instruction,outputPath,format},context){const transformed=await assistant.process(sourceDocumentIds,`Resuma e transforme o documento conforme esta instrução: ${instruction}`,{signal:context?.signal});const data=await writer.write({path:outputPath,format,content:transformed.text,createOnly:true,executionId:context?.executionId});return{ok:true,summary:`Documento transformado e validado: ${data.path}`,data:{...data,sourceDocumentIds}};} }
  ];
}
