import { z } from "zod";
import type { CalendarService } from "../../calendar/service.js";
import type { ToolDefinition } from "../types.js";
const eventSchema=z.object({connectionId:z.string().uuid(),title:z.string().min(1),start:z.string().datetime(),end:z.string().datetime(),timeZone:z.string().optional(),location:z.string().optional(),description:z.string().optional(),attendees:z.array(z.object({email:z.string().email(),name:z.string().optional()})).optional(),recurrence:z.array(z.string()).optional(),reminders:z.array(z.number().int().min(0)).optional(),allDay:z.boolean().optional()});
const eventIdSchema=z.object({connectionId:z.string().uuid(),eventId:z.string().min(1)});
export const calendarTools=(service:CalendarService):ToolDefinition[]=>[
  {name:"calendar_list_calendars",description:"Lista calendários disponíveis na conta conectada",inputSchema:z.object({connectionId:z.string().uuid()}),risk:"READ",permissions:["calendar.read"],execute:async input=>{const data=await service.listCalendars(input.connectionId);return {ok:true,summary:`${data.length} calendário(s) encontrado(s).`,data};}},
  {name:"calendar_list",description:"Lista compromissos em um período",inputSchema:z.object({connectionId:z.string().uuid(),start:z.string().datetime(),end:z.string().datetime()}),risk:"READ",permissions:["calendar.read"],execute:async input=>{const data=await service.list(input.connectionId,input.start,input.end);return {ok:true,summary:`${data.length} compromisso(s) encontrado(s).`,data};}},
  {name:"calendar_find_free_time",description:"Encontra horários livres em um período",inputSchema:z.object({connectionId:z.string().uuid(),start:z.string().datetime(),end:z.string().datetime(),durationMinutes:z.number().int().min(5).max(1440)}),risk:"READ",permissions:["calendar.read"],execute:async input=>{const data=await service.findFreeTime(input.connectionId,input.start,input.end,input.durationMinutes);return {ok:true,summary:data.length ? `${data.length} horário(s) livre(s) encontrado(s).` : "Nenhum horário livre encontrado.",data};}},
  {name:"calendar_get",description:"Obtém os detalhes de um compromisso",inputSchema:eventIdSchema,risk:"READ",permissions:["calendar.read"],execute:async input=>({ok:true,summary:"Compromisso carregado.",data:await service.get(input.connectionId,input.eventId)})},
  {name:"calendar_create",description:"Cria um compromisso no calendário conectado",inputSchema:eventSchema,risk:"SENSITIVE",permissions:["calendar.write"],execute:async input=>({ok:true,summary:"Compromisso criado.",data:await service.create(input.connectionId,input)})},
  {name:"calendar_create_meeting",description:"Cria uma reunião online com participantes",inputSchema:eventSchema,risk:"SENSITIVE",permissions:["calendar.write"],execute:async input=>({ok:true,summary:"Reunião criada.",data:await service.createMeeting(input.connectionId,input)})},
  {name:"calendar_update",description:"Atualiza um compromisso existente",inputSchema:eventIdSchema.merge(eventSchema.omit({connectionId:true}).partial()),risk:"SENSITIVE",permissions:["calendar.write"],execute:async input=>({ok:true,summary:"Compromisso atualizado.",data:await service.update(input.connectionId,input.eventId,input)})},
  {name:"calendar_delete",description:"Cancela um compromisso",inputSchema:eventIdSchema,risk:"CRITICAL",permissions:["calendar.write"],execute:async input=>({ok:true,summary:"Compromisso cancelado.",data:await service.delete(input.connectionId,input.eventId)})},
  {name:"calendar_rsvp",description:"Responde a um convite de calendário",inputSchema:eventIdSchema.extend({response:z.enum(["accept","tentative","decline"])}),risk:"SENSITIVE",permissions:["calendar.write"],execute:async input=>({ok:true,summary:"Resposta ao convite enviada.",data:await service.rsvp(input.connectionId,input.eventId,input.response)})}
];
