import { z } from "zod";
import type { CalendarService } from "../../calendar/service.js";
import type { ToolDefinition } from "../types.js";
const eventSchema=z.object({connectionId:z.string().uuid(),title:z.string().min(1),start:z.string().datetime(),end:z.string().datetime(),timeZone:z.string().optional(),location:z.string().optional(),description:z.string().optional(),attendees:z.array(z.object({email:z.string().email(),name:z.string().optional()})).optional(),recurrence:z.array(z.string()).optional(),reminders:z.array(z.number().int().min(0)).optional(),allDay:z.boolean().optional()});
const eventIdSchema=z.object({connectionId:z.string().uuid(),eventId:z.string().min(1)});
export const calendarTools=(service:CalendarService):ToolDefinition[]=>[
  {name:"calendar_list_calendars",description:"Lista calendários disponíveis na conta conectada",domain:"calendar",operation:"list_calendars",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid()}),risk:"READ",permissions:["calendar.read"],execute:async(input,context)=>{const data=await service.listCalendars(input.connectionId,context?.signal);return {ok:true,summary:`${data.length} calendário(s) encontrado(s).`,data};}},
  {name:"calendar_list",description:"Lista compromissos em um período",domain:"calendar",operation:"list_events",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),start:z.string().datetime(),end:z.string().datetime()}),risk:"READ",permissions:["calendar.read"],execute:async(input,context)=>{const data=await service.list(input.connectionId,input.start,input.end,context?.signal);return {ok:true,summary:calendarSummary(data),data};}},
  {name:"calendar_search",description:"Pesquisa compromissos por texto em um período",domain:"calendar",operation:"search_events",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),start:z.string().datetime(),end:z.string().datetime(),query:z.string().optional()}),risk:"READ",permissions:["calendar.read"],execute:async(input,context)=>{const rows=await service.list(input.connectionId,input.start,input.end,context?.signal);const query=input.query?.trim().toLowerCase();const data=query?rows.filter(event=>`${event.title} ${event.description??""} ${event.location??""}`.toLowerCase().includes(query)):rows;return{ok:true,summary:calendarSummary(data),data};}},
  {name:"calendar_find_free_time",description:"Encontra horários livres em um período",domain:"calendar",operation:"find_free_time",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),start:z.string().datetime(),end:z.string().datetime(),durationMinutes:z.number().int().min(5).max(1440)}),risk:"READ",permissions:["calendar.read"],execute:async(input,context)=>{const data=await service.findFreeTime(input.connectionId,input.start,input.end,input.durationMinutes,context?.signal);return {ok:true,summary:data.length?`${data.length} horário(s) livre(s) encontrado(s).`:"Nenhum horário livre encontrado.",data};}},
  {name:"calendar_get",description:"Obtém os detalhes de um compromisso",domain:"calendar",operation:"read_event",mutatesState:false,inputSchema:eventIdSchema,risk:"READ",permissions:["calendar.read"],execute:async(input,context)=>({ok:true,summary:"Compromisso carregado.",data:await service.get(input.connectionId,input.eventId,context?.signal)})},
  {name:"calendar_create",description:"Cria um compromisso no calendário conectado",domain:"calendar",operation:"create",mutatesState:true,inputSchema:eventSchema,risk:"SENSITIVE",permissions:["calendar.write"],execute:async(input,context)=>({ok:true,summary:"Compromisso criado.",data:await service.create(input.connectionId,input,context?.signal)})},
  {name:"calendar_create_meeting",description:"Cria uma reunião online com participantes",domain:"calendar",operation:"create_meeting",mutatesState:true,inputSchema:eventSchema,risk:"SENSITIVE",permissions:["calendar.write"],execute:async(input,context)=>({ok:true,summary:"Reunião criada.",data:await service.createMeeting(input.connectionId,input,context?.signal)})},
  {name:"calendar_update",description:"Atualiza um compromisso existente",domain:"calendar",operation:"update",mutatesState:true,inputSchema:eventIdSchema.merge(eventSchema.omit({connectionId:true}).partial()),risk:"SENSITIVE",permissions:["calendar.write"],execute:async(input,context)=>({ok:true,summary:"Compromisso atualizado.",data:await service.update(input.connectionId,input.eventId,input,context?.signal)})},
  {name:"calendar_delete",description:"Cancela um compromisso",domain:"calendar",operation:"delete",mutatesState:true,inputSchema:eventIdSchema,risk:"CRITICAL",permissions:["calendar.write"],execute:async(input,context)=>({ok:true,summary:"Compromisso cancelado.",data:await service.delete(input.connectionId,input.eventId,context?.signal)})},
  {name:"calendar_rsvp",description:"Responde a um convite de calendário",domain:"calendar",operation:"rsvp",mutatesState:true,inputSchema:eventIdSchema.extend({response:z.enum(["accept","tentative","decline"])}),risk:"SENSITIVE",permissions:["calendar.write"],execute:async(input,context)=>({ok:true,summary:"Resposta ao convite enviada.",data:await service.rsvp(input.connectionId,input.eventId,input.response,context?.signal)})}
];
function calendarSummary(events:any[]){if(!events.length)return"Nenhum compromisso encontrado no período.";return`${events.length} compromisso(s) encontrado(s):\n${events.slice(0,20).map((event,index)=>`${index+1}. ${event.start?new Date(event.start).toLocaleString("pt-BR"):"horário não informado"} — ${event.title??"(sem título)"}`).join("\n")}`;}
