import { useState } from "react";
import { ArrowDown, ArrowUp, ExternalLink, LoaderCircle, RefreshCw, Settings2, Trash2 } from "lucide-react";
import type { DashboardGadgetId, DashboardGadgetInstance, GadgetDefinition, GadgetSize } from "@nexo/shared";
import { useAppStore } from "../../stores/app";
import { EmailGadget } from "./gadgets/EmailGadget";
import { AgendaGadget } from "./gadgets/AgendaGadget";
type Data={data:any;fetchedAt:string;stale:boolean;error?:string};
export function GadgetCard({item,definition,result,editing,onResize,onRemove,onMove,onRefresh,onConfigure}:{item:DashboardGadgetInstance;definition:GadgetDefinition;result?:Data;editing:boolean;onResize:(size:GadgetSize)=>void;onRemove:()=>void;onMove:(direction:-1|1)=>void;onRefresh:()=>void;onConfigure:()=>void}){
  const [busy,setBusy]=useState(false),Icon=({"ai-status":"◈",tasks:"◷",approvals:"✓",automations:"⌘",activity:"⌁",documents:"▤",system:"⌬",weather:"☼",currency:"↗",holidays:"✳","business-days":"◫",earthquakes:"◎",email:"✉",agenda:"◫"} as Record<DashboardGadgetId,string>)[item.gadgetId];
  const reload=async()=>{setBusy(true);try{await onRefresh();}finally{setBusy(false);}};
  return <article className={`gadgetCard gadgetSize${item.size}`} draggable={editing} onDragStart={event=>{event.dataTransfer.setData("text/plain",item.instanceId);event.dataTransfer.effectAllowed="move";}} onDragOver={event=>{if(editing)event.preventDefault();}} onDrop={event=>{if(editing){event.preventDefault();const from=event.dataTransfer.getData("text/plain");if(from&&from!==item.instanceId)(window as any).dispatchEvent(new CustomEvent("nexo:dashboard:move",{detail:{from,to:item.instanceId}}));}}}>
    <header className="gadgetHeader"><span className="gadgetIcon" aria-hidden="true">{Icon}</span><div><h3>{definition.title}</h3><small>{definition.provider==="http"?"INFORMAÇÃO ONLINE":"NEXO · LOCAL"}</small></div><button className="gadgetRefresh" onClick={()=>void reload()} aria-label={`Atualizar ${definition.title}`} disabled={busy}>{busy?<LoaderCircle size={14} className="spin"/>:<RefreshCw size={14}/>}</button>{editing&&<button className="gadgetRefresh" onClick={onConfigure} aria-label={`Configurar ${definition.title}`}><Settings2 size={15}/></button>}{editing&&<button className="gadgetRefresh dangerIcon" onClick={onRemove} aria-label={`Remover ${definition.title}`}><Trash2 size={15}/></button>}</header>
    {editing&&<div className="gadgetEditControls"><label>Tamanho<select value={item.size} onChange={event=>onResize(event.target.value as GadgetSize)}>{definition.sizes.map(size=><option key={size} value={size}>{size}</option>)}</select></label><button onClick={()=>onMove(-1)} aria-label={`Mover ${definition.title} para cima`}><ArrowUp size={14}/></button><button onClick={()=>onMove(1)} aria-label={`Mover ${definition.title} para baixo`}><ArrowDown size={14}/></button></div>}
    {result?.error&&<div className={`gadgetConnection ${result.stale?"stale":"error"}`} role="status"><span>{result.stale?"Exibindo último dado salvo":"Não foi possível carregar os dados"}</span>{result.error&&<small>{result.error}</small>}</div>}
    <GadgetBody id={item.gadgetId} data={result?.data} />
    <footer className="gadgetFooter">{result?.fetchedAt&&<span>{result.stale?"Última atualização":"Atualizado"} {timeAgo(result.fetchedAt)}</span>}{result?.stale&&<span className="staleBadge">Offline</span>}{definition.attribution&&<span className="gadgetAttribution">{definition.attribution}</span>}</footer>
  </article>;
}
function GadgetBody({id,data}:{id:DashboardGadgetId;data:any}){
  const setPage=useAppStore(state=>state.setPage);
  if(id==="email")return <EmailGadget data={data}/>;
  if(id==="agenda")return <AgendaGadget data={data}/>;
  if(id==="ai-status")return <div className="aiGadget"><strong>{data?.model??"Modelo local"}</strong><p><i className={data?.connected?"isOnline":"isOffline"}/>{data?.connected?"Ollama conectado":"IA local indisponível"}</p><div><span>{data?.autonomy??"—"} · {data?.privateMode?"Privado":"Local"}</span><span>{data?.toolCount??0} ferramentas</span></div></div>;
  if(id==="tasks")return <div className="taskGadget">{!data?.length?<Empty>Nenhuma tarefa em execução.</Empty>:data.slice(0,4).map((task:any)=><div className="taskGadgetRow" key={task.id}><i/><b>{task.title}</b><small>{task.progress||task.status}</small></div>)}</div>;
  if(id==="approvals")return <div className="approvalGadget">{!data?.length?<Empty>Nenhuma ação aguardando aprovação.</Empty>:data.slice(0,3).map((approval:any)=><div key={approval.id}><span><b>{approval.toolName.replaceAll("_"," ")}</b><small>{approval.reason}</small></span><button onClick={()=>setPage("Aprovações")}>Revisar <ExternalLink size={12}/></button></div>)}</div>;
  if(id==="automations")return <div className="automationGadget"><div className="automationTotals"><strong>{data?.enabled??0}<small> / {data?.total??0}</small></strong><span>macros ativas</span></div>{data?.recentRuns?.length?data.recentRuns.slice(0,3).map((run:any)=><p key={run.id}><i className={run.status}/>{run.name??run.summary??run.status}<small>{run.status}</small></p>):<Empty>As execuções recentes aparecerão aqui.</Empty>}</div>;
  if(id==="activity")return <ActivityWidget data={data}/>;
  if(id==="documents")return <div className="documentsGadget">{!data?.length?<Empty>Seus documentos recentes aparecerão aqui.</Empty>:data.slice(0,5).map((document:any)=><div key={document.id}><span className="docType">{document.mimeType?.includes("pdf")?"PDF":document.name?.split(".").at(-1)?.toUpperCase()}</span><b>{document.name}</b><small>{timeAgo(document.updatedAt)}</small></div>)}</div>;
  if(id==="system")return <div className="systemGadget"><Usage label="RAM" value={data?.memory?.usedGB} total={data?.memory?.totalGB} suffix="GB"/><Usage label="Disco" value={data?.disk?.use} total={100} suffix="%"/><div className="systemGadgetFooter">{data?.platform??"Computador"}<span><i/>Monitoramento local</span></div></div>;
  if(id==="weather")return <WeatherWidget data={data}/>;
  if(id==="currency")return <CurrencyWidget data={data}/>;
  if(id==="holidays")return <HolidayWidget data={data}/>;
  if(id==="business-days")return <div className="businessDays"><strong>{data?.remaining??"—"}</strong><span>dias úteis restantes<br/>em {data?.month??"este mês"}</span></div>;
  if(id==="earthquakes")return <div className="earthquakeGadget">{!Array.isArray(data)||!data.length?<Empty>Nenhum evento significativo recente.</Empty>:data.slice(0,5).map((feature:any)=><div key={feature.id}><span className="magnitude">M{Number(feature.properties?.mag??0).toFixed(1)}</span><b>{feature.properties?.place??"Localização indisponível"}</b><small>{timeAgo(new Date(feature.properties?.time??Date.now()).toISOString())}</small></div>)}</div>;
  return <Empty>Gadget sem dados disponíveis.</Empty>;
}
function ActivityWidget({data}:{data:any[]}){const days=Array.from({length:7},(_,index)=>{const day=new Date();day.setHours(0,0,0,0);day.setDate(day.getDate()-(6-index));return{day,count:(data??[]).filter((row:any)=>new Date(row.createdAt).toDateString()===day.toDateString()).length,label:day.toLocaleDateString("pt-BR",{weekday:"narrow"})};}),max=Math.max(1,...days.map(day=>day.count)),points=days.map((day,index)=>`${18+index*52},${82-(day.count/max)*58}`).join(" ");return <div className="activityGadget"><div className="activityChart"><svg viewBox="0 0 330 100" role="img" aria-label="Atividade dos últimos sete dias"><defs><linearGradient id="activityFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".28"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polygon points={`18,88 ${points} 330,88`} fill="url(#activityFill)"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{days.map((day,index)=><circle key={index} cx={18+index*52} cy={82-(day.count/max)*58} r="3" fill="currentColor"/>)}</svg></div><div className="activityDays">{days.map((day,index)=><span key={index}>{day.label}</span>)}</div><strong>{data?.length??0}<small> ações recentes</small></strong></div>;}
function WeatherWidget({data}:{data:any}){const current=data?.data?.properties?.timeseries?.[0]?.data?.instant?.details,forecast=data?.data?.properties?.timeseries?.[0]?.data?.next_1_hours?.summary?.symbol_code,celsius=current?.air_temperature,temperature=typeof celsius==="number"?(data?.unit==="fahrenheit"?celsius*9/5+32:celsius):undefined;return <div className="weatherGadget"><span className="weatherGlyph">{weatherSymbol(forecast)}</span><div><strong>{temperature!==undefined?`${Math.round(temperature)}°${data?.unit==="fahrenheit"?"F":"C"}`:"—"}</strong><span>{data?.place??"Local"}</span></div><small>{weatherText(forecast)}</small><footer><span>Vento {Math.round(current?.wind_speed??0)} m/s</span><span>Humidade {current?.relative_humidity??"—"}%</span></footer></div>;}
function CurrencyWidget({data}:{data:any}){const rates=data?.rates??{};return <div className="currencyGadget">{Object.entries(rates).slice(0,4).map(([currency,rate])=><div key={currency}><span>{currency}<small> / BRL</small></span><b>R$ {typeof rate==="number"?(1/rate).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:4}):"—"}</b></div>)}</div>;}
function HolidayWidget({data}:{data:any[]}){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),next:Array<{date:string;name:string;timestamp:number}>=Array.isArray(data)?data.map((holiday:any)=>({date:String(holiday.date??""),name:String(holiday.name??"Feriado"),timestamp:new Date(`${holiday.date}T00:00:00`).getTime()})).filter(holiday=>Number.isFinite(holiday.timestamp)&&holiday.timestamp>=today).sort((a,b)=>a.timestamp-b.timestamp).slice(0,3):[];if(!next.length)return <Empty>Não há feriados próximos cadastrados.</Empty>;const first=next[0],days=Math.max(0,Math.ceil((first.timestamp-today)/86400000));return <div className="holidayGadget"><time>{new Date(first.timestamp).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}).replace(" de "," ").toUpperCase()}</time><div><b>{first.name}</b><small>Faltam {days} {days===1?"dia":"dias"}</small></div>{next.slice(1).map(holiday=><p key={holiday.date}>{new Date(holiday.timestamp).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})} · {holiday.name}</p>)}</div>;}
function Usage({label,value,total,suffix}:{label:string;value?:number;total?:number;suffix:string}){const percent=suffix==="%"?value:total&&value!==undefined?value/total*100:undefined;return <div className="usageRow"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,percent??0))}%`}}/></div><b>{value===undefined?"—":suffix==="%"?`${value.toFixed(0)}%`:`${value} / ${total} ${suffix}`}</b></div>;}
function Empty({children}:{children:string}){return <p className="gadgetEmpty">{children}</p>;}
function timeAgo(value:string){const time=Date.parse(value);if(!Number.isFinite(time))return "agora";const minutes=Math.max(0,Math.floor((Date.now()-time)/60000));return minutes<1?"agora":minutes<60?`há ${minutes} min`:minutes<1440?`há ${Math.floor(minutes/60)} h`:`há ${Math.floor(minutes/1440)} d`;}
function weatherSymbol(code?:string){if(!code)return"◌";if(code.includes("rain"))return"☂";if(code.includes("snow"))return"❄";if(code.includes("cloud"))return"☁";return"☀";}
function weatherText(code?:string){return code?.replaceAll("_"," ")??"Previsão local";}
