import { useMemo, useState } from "react";
import { ArrowUpRight, CloudSun, Cpu, FileClock, Gauge, Globe2, Landmark, ListTodo, Newspaper, Plus, Search, ShieldCheck, Sparkles, Wallet, X } from "lucide-react";
import type { DashboardGadgetId, GadgetDefinition } from "@nexo/shared";
import type { DashboardGadgetInstance } from "@nexo/shared";
const icons:Record<DashboardGadgetId,typeof Sparkles>={"ai-status":Sparkles,tasks:ListTodo,approvals:ShieldCheck,automations:Gauge,activity:FileClock,documents:Landmark,system:Cpu,weather:CloudSun,currency:Wallet,holidays:Landmark,"business-days":Gauge,"tech-news":Newspaper,earthquakes:Globe2};
export function GadgetCatalog({catalog,close,add,initial,save}:{catalog:GadgetDefinition[];close:()=>void;add:(id:DashboardGadgetId,config:Record<string,unknown>)=>Promise<void>;initial?:DashboardGadgetInstance;save?:(item:DashboardGadgetInstance,config:Record<string,unknown>)=>Promise<void>}){
  const initialDefinition=initial?catalog.find(item=>item.id===initial.gadgetId):undefined,initialConfig=initial?.configuration??{};
  const [query,setQuery]=useState(""),[choice,setChoice]=useState<GadgetDefinition|undefined>(initialDefinition),[place,setPlace]=useState(String(initialConfig.place??"")),[latitude,setLatitude]=useState(String(initialConfig.latitude??"")),[longitude,setLongitude]=useState(String(initialConfig.longitude??"")),[unit,setUnit]=useState(String(initialConfig.unit??"C")),[currencies,setCurrencies]=useState(String(initialConfig.currencies??"USD,EUR,GBP,JPY")),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const filtered=useMemo(()=>catalog.filter(item=>`${item.title} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[catalog,query]);
  async function submit(){if(!choice)return;setBusy(true);setError("");try{const configuration=choice.id==="weather"?{place:place.trim(),latitude:Number(latitude),longitude:Number(longitude),unit}:choice.id==="currency"?{currencies}:{};if(initial&&save)await save(initial,configuration);else await add(choice.id,configuration);close();}catch(e){setError(e instanceof Error?e.message:"Não foi possível adicionar o gadget.");}finally{setBusy(false);}}
  const grouped=new Map<string,GadgetDefinition[]>();for(const item of filtered){const key=item.provider==="internal"?"DADOS LOCAIS DO NEXO":"INFORMAÇÕES ONLINE";grouped.set(key,[...(grouped.get(key)??[]),item]);}
  return <div className="dashboardOverlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="gadgetCatalog" role="dialog" aria-modal="true" aria-label={choice?`Configurar ${choice.title}`:"Adicionar gadget"}>
    <header><div><span className="dashboardEyebrow">PERSONALIZE SEU ESPAÇO</span><h2>{choice?`Configurar ${choice.title}`:"Adicionar gadget"}</h2></div><button className="dashboardIconButton" onClick={()=>choice?setChoice(undefined):close()} aria-label={choice?"Voltar ao catálogo":"Fechar catálogo"}>{choice?<ArrowUpRight size={17}/>:<X size={17}/>}</button></header>
    {!choice?<><label className="gadgetSearch"><Search size={16}/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar gadget…"/></label><div className="gadgetCatalogList">{[...grouped].map(([group,items])=><section key={group}><h3>{group}</h3>{items.map(item=>{const Icon=icons[item.id];return <button className="catalogGadget" key={item.id} onClick={()=>setChoice(item)}><span className="catalogIcon"><Icon size={17}/></span><span><b>{item.title}{item.requiresInternet&&<small className="onlineTag">ONLINE</small>}</b><small>{item.description}</small></span><Plus size={16}/></button>;})}</section>)}</div></>:<div className="gadgetSetup">
      <p>{choice.description}{choice.attribution&&<small className="attribution">Fonte: {choice.attribution}</small>}</p>
      {choice.id==="weather"&&<><label>Local de referência<input value={place} onChange={event=>setPlace(event.target.value)} placeholder="Ex.: São Paulo, SP" required/></label><div className="coordinateFields"><label>Latitude<input inputMode="decimal" value={latitude} onChange={event=>setLatitude(event.target.value)} placeholder="Ex.: -23.5505" required/></label><label>Longitude<input inputMode="decimal" value={longitude} onChange={event=>setLongitude(event.target.value)} placeholder="Ex.: -46.6333" required/></label></div><fieldset><legend>Unidade</legend><label><input type="radio" name="unit" checked={unit==="C"} onChange={()=>setUnit("C")}/> Celsius</label><label><input type="radio" name="unit" checked={unit==="F"} onChange={()=>setUnit("F")}/> Fahrenheit</label></fieldset></>}
      {choice.id==="currency"&&<label>Moedas (códigos separados por vírgula)<input value={currencies} onChange={event=>setCurrencies(event.target.value.toUpperCase())} placeholder="USD,EUR,GBP,JPY"/></label>}
      {choice.requiresInternet&&<aside className="privacyNotice"><Globe2 size={17}/><div><b>Este gadget consulta um serviço externo</b><p>{choice.id==="weather"?`Ao adicionar, as coordenadas ${latitude||"(a configurar)"}, ${longitude||"(a configurar)"} serão enviadas à MET Norway para obter a previsão de ${place||"local escolhido"}.`:`Ao adicionar, o Nexo consultará ${choice.attribution} para carregar informações públicas.`} Conversas, documentos e dados locais não são enviados.</p></div></aside>}
      {error&&<p role="alert" className="gadgetError">{error}</p>}<footer><button className="dashboardSecondary" onClick={()=>initial?close():setChoice(undefined)}>{initial?"Cancelar":"Voltar"}</button><button className="dashboardPrimary" disabled={busy||choice.id==="weather"&&(!place.trim()||!latitude.trim()||!longitude.trim()||!Number.isFinite(Number(latitude))||!Number.isFinite(Number(longitude)))} onClick={()=>void submit()}>{busy?"Salvando…":initial?"Salvar configuração":"Adicionar ao dashboard"}</button></footer>
    </div>}
  </section></div>;
}
