import { z } from "zod";
import type { EmailService } from "../../email/service.js";
import type { ToolDefinition } from "../types.js";

const address=z.object({email:z.string().email(),name:z.string().optional()});
const connection=z.object({connectionId:z.string().uuid()});
const gmailCategory=z.enum(["primary","promotions","social","updates","forums"]);
const readConnection=connection.extend({categories:z.array(gmailCategory).min(1).max(5).optional()});
const messageIds=z.array(z.string().min(1)).min(1).max(100);

export const emailTools=(service:EmailService):ToolDefinition[]=>[
  {name:"email_latest",description:"Obtém o e-mail mais recente da caixa de entrada",domain:"email",operation:"latest",mutatesState:false,inputSchema:readConnection,risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const message=await service.latest(input.connectionId,input.categories,context?.signal);if(!message)return{ok:true,summary:"Nenhum e-mail foi encontrado na caixa de entrada.",data:null};const when=new Date(message.receivedAt).toLocaleString("pt-BR");return{ok:true,summary:`Último e-mail recebido em ${when}. De: ${message.from.name??message.from.email}. Assunto: ${message.subject}.${message.snippet?` ${message.snippet}`:""}`,data:message};}},
  {name:"email_stats",description:"Consulta totais e quantidade de e-mails não lidos",domain:"email",operation:"stats",mutatesState:false,inputSchema:readConnection,risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.stats(input.connectionId,input.categories,context?.signal);const parts=[data.totalMessages!==undefined?`${data.totalMessages} e-mails no total`:undefined,data.inboxMessages!==undefined?`${data.inboxMessages} na caixa de entrada selecionada`:undefined,data.unreadMessages!==undefined?`${data.unreadMessages} não lidos`:undefined].filter(Boolean);return{ok:true,summary:parts.length?`Sua conta possui ${parts.join(", ")}.`:"As estatísticas da conta foram consultadas.",data};}},
  {name:"email_search",description:"Pesquisa e lista e-mails da conta conectada",domain:"email",operation:"search",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),query:z.string().optional(),unread:z.boolean().optional(),categories:z.array(gmailCategory).min(1).max(5).optional(),maxResults:z.number().int().min(1).max(50).optional(),pageToken:z.string().optional()}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.search(input,context?.signal);return{ok:true,summary:emailListSummary(data.messages),data};}},
  {name:"email_get",description:"Obtém o conteúdo detalhado de um e-mail",domain:"email",operation:"read",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>({ok:true,summary:"E-mail carregado.",data:await service.getMessage(input.connectionId,input.messageId,context?.signal)})},
  {name:"email_get_many",description:"Obtém detalhes de vários e-mails já selecionados",domain:"email",operation:"read_many",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),messageIds:z.array(z.string().min(1)).min(1).max(30)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const rows=[];for(const id of input.messageIds){if(context?.signal?.aborted)throw context.signal.reason??new DOMException("Cancelado","AbortError");rows.push(await service.getMessage(input.connectionId,id,context?.signal));}return{ok:true,summary:emailListSummary(rows),data:rows};}},
  {name:"email_get_thread",description:"Obtém todas as mensagens de uma conversa",domain:"email",operation:"read_thread",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),threadId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.getThread(input.connectionId,input.threadId,context?.signal);return{ok:true,summary:`${data.length} mensagem(ns) na conversa.`,data};}},
  {name:"email_list_attachments",description:"Lista anexos de um e-mail sem baixá-los",domain:"email",operation:"list_attachments",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.listAttachments(input.connectionId,input.messageId,context?.signal);return{ok:true,summary:`${data.length} anexo(s) encontrado(s).`,data};}},
  {name:"email_download_attachment",description:"Baixa um anexo para uma pasta autorizada sem sobrescrever arquivos",domain:"email",operation:"download_attachment",mutatesState:true,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),attachmentId:z.string().min(1),destination:z.string().min(1)}),pathFields:["destination"],risk:"SENSITIVE",permissions:["email.read"],execute:async(input,context)=>({ok:true,summary:"Anexo baixado.",data:await service.downloadAttachment(input.connectionId,input.messageId,input.attachmentId,input.destination,context?.signal)})},
  {name:"email_create_draft",description:"Prepara localmente um rascunho de e-mail sem enviar",domain:"email",operation:"create_draft",mutatesState:false,inputSchema:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string().max(998),bodyText:z.string().min(1),cc:z.array(address).optional()}),risk:"SAFE_WRITE",permissions:["email.send"],execute:async input=>({ok:true,summary:"Rascunho preparado. Nenhum e-mail foi enviado.",data:await service.createDraft(input)})},
  {name:"email_send_composed",description:"Envia um e-mail após confirmação explícita do usuário",domain:"email",operation:"send",mutatesState:true,inputSchema:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1).max(50),subject:z.string().max(998),bodyText:z.string().min(1),cc:z.array(address).optional()}),risk:"SENSITIVE",permissions:["email.send"],execute:async(input,context)=>{const draft=await service.createDraft(input);const data=await service.sendDraft(draft,context?.signal);return{ok:true,summary:`E-mail enviado para ${input.to.map((item:any)=>item.email).join(", ")}.`,data};}},
  {name:"email_send",description:"Envia um rascunho de e-mail aprovado",domain:"email",operation:"send_draft",mutatesState:true,inputSchema:z.object({id:z.string().uuid(),provider:z.enum(["google","microsoft"]),message:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string(),bodyText:z.string(),cc:z.array(address).optional()})}),risk:"SENSITIVE",permissions:["email.send"],execute:async(input,context)=>({ok:true,summary:"E-mail enviado.",data:await service.sendDraft(input,context?.signal)})},
  singleMutation(service,"email_mark_read","mark_read","Marca um e-mail como lido","SAFE_WRITE"),
  singleMutation(service,"email_mark_unread","mark_unread","Marca um e-mail como não lido","SAFE_WRITE"),
  singleMutation(service,"email_archive","archive","Arquiva um e-mail","SAFE_WRITE"),
  singleMutation(service,"email_flag","flag","Sinaliza um e-mail","SAFE_WRITE"),
  singleMutation(service,"email_trash","trash","Move um e-mail para a lixeira","CRITICAL"),
  valueMutation(service,"email_move","move","Move um e-mail para uma pasta","destinationId"),
  valueMutation(service,"email_add_label","add_label","Adiciona marcador/categoria a um e-mail","labelId"),
  valueMutation(service,"email_remove_label","remove_label","Remove marcador/categoria de um e-mail","labelId"),
  bulkMutation(service,"email_bulk_trash","trash","Move vários e-mails selecionados para a lixeira","CRITICAL"),
  bulkMutation(service,"email_bulk_archive","archive","Arquiva vários e-mails selecionados","SAFE_WRITE"),
  bulkMutation(service,"email_bulk_mark_read","mark_read","Marca vários e-mails selecionados como lidos","SAFE_WRITE"),
  bulkMutation(service,"email_bulk_mark_unread","mark_unread","Marca vários e-mails selecionados como não lidos","SAFE_WRITE")
];

function singleMutation(service:EmailService,name:string,action:any,description:string,risk:"SAFE_WRITE"|"CRITICAL"):ToolDefinition{return{name,description,domain:"email",operation:action,mutatesState:true,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk,permissions:["email.modify"],execute:async(input,context)=>({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action,undefined,context?.signal)})};}
function valueMutation(service:EmailService,name:string,action:any,description:string,field:string):ToolDefinition{return{name,description,domain:"email",operation:action,mutatesState:true,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),[field]:z.string().min(1)}),risk:"SAFE_WRITE",permissions:["email.modify"],execute:async(input:any,context)=>({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action,input[field],context?.signal)})};}
function bulkMutation(service:EmailService,name:string,action:any,description:string,risk:"SAFE_WRITE"|"CRITICAL"):ToolDefinition{return{name,description,domain:"email",operation:action,mutatesState:true,inputSchema:z.object({connectionId:z.string().uuid(),messageIds}),risk,permissions:["email.modify"],execute:async(input,context)=>{const failures:Array<{messageId:string;error:string}>=[];let succeeded=0;for(const id of input.messageIds){if(context?.signal?.aborted)throw context.signal.reason??new DOMException("Cancelado","AbortError");try{await service.modify(input.connectionId,id,action,undefined,context?.signal);succeeded++;}catch(error){failures.push({messageId:id,error:error instanceof Error?error.message:String(error)});}}const data={requested:input.messageIds.length,succeeded,failed:failures.length,failures};return{ok:succeeded>0||failures.length===0,summary:failures.length?`${succeeded} e-mail(s) alterado(s); ${failures.length} falharam.`:`${succeeded} e-mail(s) alterado(s) com sucesso.`,data,error:succeeded===0&&failures.length?"Nenhum e-mail pôde ser alterado.":undefined};}};}
function emailListSummary(messages:any[]){if(!messages.length)return"Nenhum e-mail encontrado.";const rows=messages.slice(0,20).map((message,index)=>`${index+1}. ${message.subject??"(sem assunto)"} — ${message.from?.name??message.from?.email??"remetente desconhecido"}${message.receivedAt?` — ${new Date(message.receivedAt).toLocaleString("pt-BR")}`:""}`);return`Encontrei ${messages.length} e-mail(s):\n${rows.join("\n")}`;}
