import { z } from "zod";
import type { EmailService } from "../../email/service.js";
import type { ToolDefinition } from "../types.js";
const address = z.object({ email:z.string().email(), name:z.string().optional() });
export const emailTools = (service: EmailService): ToolDefinition[] => [
  { name:"email_search", description:"Pesquisa e-mails da conta conectada", inputSchema:z.object({connectionId:z.string().uuid(),query:z.string().optional(),unread:z.boolean().optional(),maxResults:z.number().int().min(1).max(50).optional(),pageToken:z.string().optional()}), risk:"READ", permissions:["email.read"], execute: async input => { const data=await service.search(input); return {ok:true,summary:`${data.messages.length} e-mail(s) encontrado(s).`,data}; } },
  { name:"email_get", description:"Obtém o conteúdo detalhado de um e-mail", inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}), risk:"READ", permissions:["email.read"], execute:async input=>({ok:true,summary:"E-mail carregado.",data:await service.getMessage(input.connectionId,input.messageId)}) },
  { name:"email_get_thread", description:"Obtém todas as mensagens de uma conversa", inputSchema:z.object({connectionId:z.string().uuid(),threadId:z.string().min(1)}), risk:"READ", permissions:["email.read"], execute:async input=>{const data=await service.getThread(input.connectionId,input.threadId);return {ok:true,summary:`${data.length} mensagem(ns) na conversa.`,data};} },
  { name:"email_list_attachments", description:"Lista anexos de um e-mail sem baixá-los", inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}), risk:"READ", permissions:["email.read"], execute:async input=>{const data=await service.listAttachments(input.connectionId,input.messageId);return {ok:true,summary:`${data.length} anexo(s) encontrado(s).`,data};} },
  { name:"email_download_attachment", description:"Baixa um anexo para uma pasta autorizada sem sobrescrever arquivos", inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),attachmentId:z.string().min(1),destination:z.string().min(1)}), pathFields:["destination"], risk:"SENSITIVE", permissions:["email.read"], execute:async input=>({ok:true,summary:"Anexo baixado.",data:await service.downloadAttachment(input.connectionId,input.messageId,input.attachmentId,input.destination)}) },
  { name:"email_create_draft", description:"Prepara um rascunho de e-mail sem enviar", inputSchema:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string().min(1),bodyText:z.string().min(1),cc:z.array(address).optional()}), risk:"SAFE_WRITE", permissions:["email.send"], execute: async input => ({ok:true,summary:"Rascunho preparado. Revise e aprove o envio.",data:await service.createDraft(input)}) },
  { name:"email_send", description:"Envia um rascunho de e-mail aprovado", inputSchema:z.object({id:z.string().uuid(),provider:z.enum(["google","microsoft"]),message:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string(),bodyText:z.string(),cc:z.array(address).optional()})}), risk:"SENSITIVE", permissions:["email.send"], execute: async input => ({ok:true,summary:"E-mail enviado.",data:await service.sendDraft(input)}) },
  ...([ ["email_mark_read","mark_read","Marca um e-mail como lido","SAFE_WRITE"], ["email_mark_unread","mark_unread","Marca um e-mail como não lido","SAFE_WRITE"], ["email_archive","archive","Arquiva um e-mail","SAFE_WRITE"], ["email_flag","flag","Sinaliza um e-mail","SAFE_WRITE"], ["email_trash","trash","Move um e-mail para a lixeira","CRITICAL"] ] as const).map(([name,action,description,risk]) => ({ name, description, inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}), risk, permissions:["email.modify"], execute:async (input:any) => ({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action)}) } satisfies ToolDefinition))
  ,...([ ["email_move","move","Move um e-mail para uma pasta","destinationId"], ["email_add_label","add_label","Adiciona marcador/categoria a um e-mail","labelId"], ["email_remove_label","remove_label","Remove marcador/categoria de um e-mail","labelId"] ] as const).map(([name,action,description,field]) => ({ name,description,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),[field]:z.string().min(1)}),risk:"SAFE_WRITE",permissions:["email.modify"],execute:async(input:any)=>({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action,input[field])})} satisfies ToolDefinition))
];
