import { z } from "zod";
import type { EmailService } from "../../email/service.js";
import type { ToolDefinition } from "../types.js";
const address=z.object({email:z.string().email(),name:z.string().optional()});
const connection=z.object({connectionId:z.string().uuid()});

export const emailTools=(service:EmailService):ToolDefinition[]=>[
  {name:"email_latest",description:"Obtém o e-mail mais recente da caixa de entrada",inputSchema:connection,risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const message=await service.latest(input.connectionId,context?.signal);if(!message)return{ok:true,summary:"Nenhum e-mail foi encontrado na caixa de entrada.",data:null};const when=new Date(message.receivedAt).toLocaleString("pt-BR");return{ok:true,summary:`Último e-mail recebido em ${when}. De: ${message.from.name??message.from.email}. Assunto: ${message.subject}.${message.snippet?` ${message.snippet}`:""}`,data:message};}},
  {name:"email_stats",description:"Consulta totais e quantidade de e-mails não lidos",inputSchema:connection,risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.stats(input.connectionId,context?.signal);const parts=[data.totalMessages!==undefined?`${data.totalMessages} e-mails no total`:undefined,data.inboxMessages!==undefined?`${data.inboxMessages} na caixa de entrada`:undefined,data.unreadMessages!==undefined?`${data.unreadMessages} não lidos`:undefined].filter(Boolean);return{ok:true,summary:parts.length?`Sua conta possui ${parts.join(", ")}.`:"As estatísticas da conta foram consultadas.",data};}},
  {name:"email_search",description:"Pesquisa e-mails da conta conectada",inputSchema:z.object({connectionId:z.string().uuid(),query:z.string().optional(),unread:z.boolean().optional(),maxResults:z.number().int().min(1).max(50).optional(),pageToken:z.string().optional()}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.search(input,context?.signal);return{ok:true,summary:`${data.messages.length} e-mail(s) encontrado(s).`,data};}},
  {name:"email_get",description:"Obtém o conteúdo detalhado de um e-mail",inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>({ok:true,summary:"E-mail carregado.",data:await service.getMessage(input.connectionId,input.messageId,context?.signal)})},
  {name:"email_get_thread",description:"Obtém todas as mensagens de uma conversa",inputSchema:z.object({connectionId:z.string().uuid(),threadId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.getThread(input.connectionId,input.threadId,context?.signal);return{ok:true,summary:`${data.length} mensagem(ns) na conversa.`,data};}},
  {name:"email_list_attachments",description:"Lista anexos de um e-mail sem baixá-los",inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk:"READ",permissions:["email.read"],execute:async(input,context)=>{const data=await service.listAttachments(input.connectionId,input.messageId,context?.signal);return{ok:true,summary:`${data.length} anexo(s) encontrado(s).`,data};}},
  {name:"email_download_attachment",description:"Baixa um anexo para uma pasta autorizada sem sobrescrever arquivos",inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),attachmentId:z.string().min(1),destination:z.string().min(1)}),pathFields:["destination"],risk:"SENSITIVE",permissions:["email.read"],execute:async(input,context)=>({ok:true,summary:"Anexo baixado.",data:await service.downloadAttachment(input.connectionId,input.messageId,input.attachmentId,input.destination,context?.signal)})},
  {name:"email_create_draft",description:"Prepara um rascunho de e-mail sem enviar",inputSchema:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string().min(1),bodyText:z.string().min(1),cc:z.array(address).optional()}),risk:"SAFE_WRITE",permissions:["email.send"],execute:async input=>({ok:true,summary:"Rascunho preparado. Revise e aprove o envio.",data:await service.createDraft(input)})},
  {name:"email_send",description:"Envia um rascunho de e-mail aprovado",inputSchema:z.object({id:z.string().uuid(),provider:z.enum(["google","microsoft"]),message:z.object({connectionId:z.string().uuid(),to:z.array(address).min(1),subject:z.string(),bodyText:z.string(),cc:z.array(address).optional()})}),risk:"SENSITIVE",permissions:["email.send"],execute:async(input,context)=>({ok:true,summary:"E-mail enviado.",data:await service.sendDraft(input,context?.signal)})},
  ...([ ["email_mark_read","mark_read","Marca um e-mail como lido","SAFE_WRITE"], ["email_mark_unread","mark_unread","Marca um e-mail como não lido","SAFE_WRITE"], ["email_archive","archive","Arquiva um e-mail","SAFE_WRITE"], ["email_flag","flag","Sinaliza um e-mail","SAFE_WRITE"], ["email_trash","trash","Move um e-mail para a lixeira","CRITICAL"] ] as const).map(([name,action,description,risk])=>({name,description,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1)}),risk,permissions:["email.modify"],execute:async(input:any,context)=>({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action,undefined,context?.signal)})} satisfies ToolDefinition)),
  ...([ ["email_move","move","Move um e-mail para uma pasta","destinationId"], ["email_add_label","add_label","Adiciona marcador/categoria a um e-mail","labelId"], ["email_remove_label","remove_label","Remove marcador/categoria de um e-mail","labelId"] ] as const).map(([name,action,description,field])=>({name,description,inputSchema:z.object({connectionId:z.string().uuid(),messageId:z.string().min(1),[field]:z.string().min(1)}),risk:"SAFE_WRITE",permissions:["email.modify"],execute:async(input:any,context)=>({ok:true,summary:`E-mail atualizado: ${description.toLowerCase()}.`,data:await service.modify(input.connectionId,input.messageId,action,input[field],context?.signal)})} satisfies ToolDefinition))
];
