import { useEffect, useLayoutEffect, useMemo, useState } from "react";
import { AnimatePresence,motion,useReducedMotion } from "motion/react";
import { ArrowRight,Command as CommandIcon,FileText,Search,Sparkles } from "lucide-react";
import { useAppStore } from "../../stores/app";
import { useAssistantStore } from "../../stores/assistant";
import { useToastStore } from "../../stores/toast";
import type { AutomationViewModel, ConversationSummary, DocumentRecord } from "@nexo/shared";
import { motionTokens } from "../../design/motion";
import "./command-palette.css";

type Command = { label:string; keywords:string; group:string; page?:string; run?:()=>Promise<void> };
const pages=["Dashboard","Assistente","Macros","Escritório","Documentos","Aprovações","Atividade","Ferramentas","Memória","Diagnóstico","Configurações"];

export function CommandPalette() {
  const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[selected,setSelected]=useState(0),[recent,setRecent]=useState<string[]>([]),[dynamicCommands,setDynamicCommands]=useState<Command[]>([]),[invoking,setInvoking]=useState(false); const setPage=useAppStore(s=>s.setPage),reduceMotion=useReducedMotion();
  const commands=useMemo<Command[]>(()=>[
    ...pages.map(page=>({label:`Abrir ${page}`,keywords:page,group:"Navegação",page})),
    {label:"Nova conversa",keywords:"chat assistente nova conversa",group:"Comandos",page:"Assistente",run:async()=>{await useAssistantStore.getState().createSession();}},
    {label:"Importar documento",keywords:"arquivo word pdf importar anexo",group:"Comandos",page:"Assistente",run:async()=>{const store=useAssistantStore.getState();const id=store.activeSessionId||await store.createSession();if(id)await useAssistantStore.getState().attach(id);}},
    {label:"Conectar Google",keywords:"gmail google conta conexão",group:"Comandos",page:"Configurações"},
    {label:"Conectar Microsoft",keywords:"outlook microsoft conta conexão",group:"Comandos",page:"Configurações"},
    {label:"Criar macro",keywords:"macro automação agendar rotina",group:"Comandos",page:"Macros"},
    {label:"Ver ferramentas",keywords:"tools arquivos sistema web",group:"Comandos",page:"Configurações"},
    {label:"Ativar/desativar modo privado",keywords:"privacidade privado",group:"Comandos",run:async()=>{const current=await window.nexo.getSettings();await window.nexo.updateSettings({privateMode:!current.privateMode});setPage("Configurações");}},
    ...dynamicCommands
  ],[dynamicCommands,setPage]);
  const visible=useMemo(()=>commands.map((command,index)=>({command,index,score:fuzzyScore(`${command.label} ${command.keywords}`,query),recentIndex:recent.indexOf(command.label)})).filter(item=>item.score>=0).sort((a,b)=>query.trim()?b.score-a.score||a.index-b.index:(a.recentIndex<0?Infinity:a.recentIndex)-(b.recentIndex<0?Infinity:b.recentIndex)||a.index-b.index).map(item=>item.command),[commands,query,recent]);
  const invoke=async(command:Command)=>{if(invoking)return;setInvoking(true);try{if(command.run)await command.run();if(command.page)setPage(command.page);const next=[command.label,...recent.filter(label=>label!==command.label)].slice(0,5);setRecent(next);try{localStorage.setItem("nexo.command.recent",JSON.stringify(next));}catch{}setOpen(false);setQuery("");setSelected(0);}catch(error){useToastStore.getState().show({title:"Não foi possível executar o comando",description:error instanceof Error?error.message:"Tente novamente.",tone:"error"});}finally{setInvoking(false);}};
  useEffect(()=>{if(!open)return;let active=true;const load=<T,>(read:()=>Promise<T>,fallback:T)=>Promise.resolve().then(read).catch(()=>fallback);void Promise.all([load(()=>window.nexo.listAutomations?.()??Promise.resolve([]),[]),load(()=>window.nexo.listConversations(),[]),load(()=>window.nexo.listRecentDocuments?.()??Promise.resolve([]),[])]).then(([macros,conversations,documents])=>{if(!active)return;const searchableMacros=(macros as AutomationViewModel[]).map(macro=>({label:`Executar macro: ${macro.name}`,keywords:`macro executar ${macro.name} ${macro.description??macro.prompt??""}`,group:"Macros",page:"Macros",run:async()=>{await window.nexo.runAutomation(macro.id);}}));const searchableConversations=(conversations as ConversationSummary[]).map(conversation=>({label:`Abrir conversa: ${conversation.title}`,keywords:`conversa chat histórico ${conversation.title}`,group:"Conversas",page:"Assistente",run:async()=>{await useAssistantStore.getState().sync();useAssistantStore.getState().selectSession(conversation.id);}}));const searchableDocuments=(documents as DocumentRecord[]).map(document=>({label:`Abrir documento: ${document.name}`,keywords:`arquivo documento ${document.name} ${document.mimeType}`,group:"Arquivos",page:"Documentos"}));setDynamicCommands([...searchableMacros,...searchableConversations,...searchableDocuments]);});return()=>{active=false;};},[open]);
  useLayoutEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&(event.key.toLowerCase()==="k"||event.code==="Space")){event.preventDefault();setOpen(value=>!value);}if(event.key==="Escape")setOpen(false);if(open&&event.key==="ArrowDown"){event.preventDefault();setSelected(value=>Math.min(value+1,Math.max(visible.length-1,0)));}if(open&&event.key==="ArrowUp"){event.preventDefault();setSelected(value=>Math.max(0,value-1));}if(open&&event.key==="Enter"&&visible[selected]){event.preventDefault();void invoke(visible[selected]);}};const show=()=>{setOpen(true);setQuery("");setSelected(0);try{const value=JSON.parse(localStorage.getItem("nexo.command.recent")||"[]");setRecent(Array.isArray(value)?value.filter((item):item is string=>typeof item==="string").slice(0,5):[]);}catch{setRecent([]);}};window.addEventListener("keydown",key);window.addEventListener("nexo:open-command-palette",show);return()=>{window.removeEventListener("keydown",key);window.removeEventListener("nexo:open-command-palette",show);};},[open,visible,selected]);
  return <AnimatePresence>{open&&<motion.div className="paletteOverlay" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}} initial={reduceMotion?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduceMotion?0:motionTokens.duration.fast/1000}}><motion.div className="palette" role="dialog" aria-modal="true" aria-label="Paleta de comandos" onMouseDown={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key!=="Tab")return;const focusable=[...event.currentTarget.querySelectorAll<HTMLElement>("input:not([disabled]),button:not([disabled])")];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}} initial={reduceMotion?false:{opacity:0,y:-8,scale:motionTokens.scale.popover}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-4,scale:motionTokens.scale.popover}} transition={reduceMotion?{duration:0}:motionTokens.spring.normal}><div className="paletteSearch"><Search size={17} aria-hidden="true"/><input autoFocus role="combobox" aria-autocomplete="list" aria-expanded="true" aria-controls="nexo-command-list" aria-activedescendant={visible[selected]?`nexo-command-${selected}`:undefined} value={query} onChange={event=>{setQuery(event.target.value);setSelected(0);}} placeholder="O que deseja fazer?"/><kbd>ESC</kbd></div><div id="nexo-command-list" className="paletteList" role="listbox" aria-label="Comandos disponíveis">{visible.length?visible.map((command,index)=><div className="paletteGroup" role="group" aria-label={command.group} key={`${command.group}:${command.label}:${index}`}>{(index===0||visible[index-1].group!==command.group)&&<div className="paletteGroupHeading">{!query.trim()&&recent.includes(command.label)?"Recentes":command.group}</div>}<button id={`nexo-command-${index}`} className={`paletteCommand${selected===index?" selected":""}`} role="option" aria-selected={selected===index} disabled={invoking} onMouseEnter={()=>setSelected(index)} onClick={()=>void invoke(command)}><span className="paletteCommandIcon">{command.group==="Macros"?<Sparkles size={15}/>:command.group==="Arquivos"?<FileText size={15}/>:<ArrowRight size={15}/>}</span><span>{command.label}<small>{command.page??"Ação rápida"}{!query.trim()&&recent.includes(command.label)?" · Recente":""}</small></span><kbd>↵</kbd></button></div>):<div className="paletteNoResults">Nenhum comando encontrado.</div>}</div><footer><span><kbd>↑</kbd><kbd>↓</kbd> navegar</span><span><kbd>↵</kbd> abrir</span><span><kbd>Esc</kbd> fechar</span><span className="paletteFooterBrand"><CommandIcon size={12}/> Nexo Command</span></footer></motion.div></motion.div>}</AnimatePresence>;
}

function fuzzyScore(source:string,query:string){if(!query.trim())return 1;const haystack=source.toLocaleLowerCase(),needle=query.toLocaleLowerCase().trim();if(haystack.includes(needle))return 100- haystack.indexOf(needle);let cursor=0,score=0,last=-2;for(const character of needle){const index=haystack.indexOf(character,cursor);if(index<0)return-1;score+=index===last+1?5:Math.max(0,3-index/20);last=index;cursor=index+1;}return score;}
