import type { ChatActionRequest, ChatActionOutcome, ChatBlock, ChatResourceUpdatedEvent } from "@nexo/shared";
import { create } from "zustand";
import type { BackgroundTask,ChatMessage,ConversationSummary,DocumentRecord,ChatSessionStatus } from "@nexo/shared";
export const MAX_CHAT_SESSIONS=4;
export type AssistantAttachment={taskId:string;name:string;status:"indexing"|"ready"|"failed";documentId?:string};
export type ChatSessionState={id:string;title:string;createdAt:string;updatedAt:string;messages:ChatMessage[];attachments:AssistantAttachment[];activeTaskId?:string;agentId?:string;runId?:string;status:ChatSessionStatus};
type TaskEvent={kind:string;taskId:string;task?:BackgroundTask;token?:string};
type Store={
blockLimits:Record<string,number>;
executeResourceAction:(request:ChatActionRequest)=>Promise<ChatActionOutcome>;
resolveInlineApproval:(conversationId:string,messageId:string,approvalId:string,approved:boolean)=>Promise<void>;
loadMoreBlock:(conversationId:string,messageId:string,blockId:string)=>Promise<void>;
updateMessageBlock:(conversationId:string,messageId:string,block:ChatBlock)=>void;
handleResourceEvent:(event:ChatResourceUpdatedEvent)=>void;
sessions:ChatSessionState[];activeSessionId:string;tasks:BackgroundTask[];error:string|null;isFollowing:boolean;sync:()=>Promise<void>;syncSession:(id:string)=>Promise<void>;createSession:()=>Promise<string|undefined>;closeSession:(id:string)=>Promise<boolean>;renameSession:(id:string,title:string)=>Promise<void>;selectSession:(id:string)=>void;isStreaming:(id:string)=>boolean;handleTaskEvent:(event:unknown)=>void;syncAttachments:(sessionId?:string)=>Promise<void>;send:(sessionId:string,text:string)=>Promise<boolean>;cancel:(sessionId:string)=>Promise<void>;attach:(sessionId:string)=>Promise<void>;removeAttachment:(sessionId:string,id:string)=>void;setFollowing:(value:boolean)=>void};
const taskStatus=(task?:BackgroundTask):ChatSessionStatus=>task?.status==="waiting_approval"?"waiting_approval":task?.status==="running"||task?.status==="queued"?"running":task?.status==="failed"?"failed":task?.status==="completed"?"completed":"idle";
const buildSession=(conversation:ConversationSummary,messages:ChatMessage[],tasks:BackgroundTask[],existing?:ChatSessionState):ChatSessionState=>{const active=tasks.find(task=>task.type==="assistant-chat"&&task.conversationId===conversation.id&&["queued","running","waiting_approval"].includes(task.status));return{id:conversation.id,title:conversation.title,createdAt:conversation.createdAt,updatedAt:conversation.updatedAt,messages,attachments:existing?.attachments??[],activeTaskId:active?.id,agentId:active?.agentId??existing?.agentId,runId:active?.runId??existing?.runId,status:taskStatus(active)};};
export const useAssistantStore=create<Store>((set,get)=>({blockLimits:{},
  updateMessageBlock:(conversationId,messageId,block)=>set(state=>({sessions:state.sessions.map(session=>session.id!==conversationId?session:{...session,messages:session.messages.map(message=>message.id!==messageId?message:{...message,blocks:message.blocks?.some(value=>value.id===block.id)?message.blocks.map(value=>value.id===block.id?block:value):[...(message.blocks??[]),block]})})})),
  handleResourceEvent:event=>{const message=get().sessions.find(session=>session.id===event.conversationId)?.messages.find(message=>message.id===event.messageId),block=message?.blocks?.find(block=>block.id===event.blockId);if(block?.type==="resource_collection")get().updateMessageBlock(event.conversationId,event.messageId,{...block,items:block.items.map(item=>item.id===event.itemId?event.item:item)});if(event.approval)get().updateMessageBlock(event.conversationId,event.messageId,event.approval);},
  executeResourceAction:async request=>{const result=await window.nexo.executeChatAction(request);if(result.item)get().handleResourceEvent({type:"chat.resource.updated",...request,state:result.item.state??"idle",item:result.item,approval:result.approval});if(result.block)get().updateMessageBlock(request.conversationId,request.messageId,result.block);if(result.copyText)await navigator.clipboard.writeText(result.copyText);return result;},
  resolveInlineApproval:async(conversationId,messageId,approvalId,approved)=>{try{const result=await window.nexo.resolveInlineApproval(conversationId,messageId,approvalId,approved);const message=get().sessions.find(session=>session.id===conversationId)?.messages.find(message=>message.id===messageId),block=message?.blocks?.find(block=>block.type==="approval"&&block.approvalId===approvalId);if(result?.approval)get().updateMessageBlock(conversationId,messageId,result.approval);else if(block?.type==="approval")get().updateMessageBlock(conversationId,messageId,{...block,status:approved?"approved":"rejected"});}catch(error){await get().syncSession(conversationId);throw error;}},
  loadMoreBlock:async(conversationId,messageId,blockId)=>{const block=get().sessions.find(session=>session.id===conversationId)?.messages.find(message=>message.id===messageId)?.blocks?.find(block=>block.id===blockId);if(block?.type!=="resource_collection")return;const limit=get().blockLimits[blockId]??8;if(limit>=block.items.length&&block.pagination?.hasMore){const next=await window.nexo.loadMoreChatBlock(conversationId,messageId,blockId);get().updateMessageBlock(conversationId,messageId,next);}set(state=>({blockLimits:{...state.blockLimits,[blockId]:limit+8}}));},
  sessions:[],activeSessionId:"",tasks:[],error:null,isFollowing:true,
  sync:async()=>{try{let conversations=(await window.nexo.listConversations()) as ConversationSummary[];if(!conversations.length)conversations=[await window.nexo.createConversation() as ConversationSummary];const tasks=(await window.nexo.listActiveTasks()) as BackgroundTask[];const visible:ConversationSummary[]=conversations.slice(0,MAX_CHAT_SESSIONS);const messages:ChatMessage[][]=await Promise.all(visible.map((item:ConversationSummary)=>window.nexo.conversationMessages(item.id) as Promise<ChatMessage[]>));set(state=>{const sessions=visible.map((conversation:ConversationSummary,index:number)=>buildSession(conversation,messages[index]??[],tasks,state.sessions.find((item:ChatSessionState)=>item.id===conversation.id)));const active=sessions.some(item=>item.id===state.activeSessionId)?state.activeSessionId:sessions[0]?.id??"";return{sessions,activeSessionId:active,tasks,error:null};});}catch(error){set({error:error instanceof Error?error.message:String(error)});}},
  syncSession:async id=>{try{const [rawConversations,rawMessages,rawTasks]=await Promise.all([window.nexo.listConversations(),window.nexo.conversationMessages(id),window.nexo.listActiveTasks()]);const conversations=rawConversations as ConversationSummary[],messages=rawMessages as ChatMessage[],tasks=rawTasks as BackgroundTask[];const conversation=conversations.find((item:ConversationSummary)=>item.id===id);if(!conversation)return;set(state=>({sessions:state.sessions.map(item=>item.id===id?buildSession(conversation,messages,tasks,item):item),tasks,error:null}));}catch(error){set({error:error instanceof Error?error.message:String(error)});}},
  createSession:async()=>{if(get().sessions.length>=MAX_CHAT_SESSIONS){set({error:`Máximo de ${MAX_CHAT_SESSIONS} chats simultâneos.`});return;}try{const conversation=await window.nexo.createConversation() as ConversationSummary;set(state=>({sessions:[...state.sessions,{id:conversation.id,title:conversation.title,createdAt:conversation.createdAt,updatedAt:conversation.updatedAt,messages:[],attachments:[],status:"idle"}],activeSessionId:conversation.id,error:null}));return conversation.id;}catch(error){set({error:error instanceof Error?error.message:String(error)});}},
  closeSession:async id=>{const session=get().sessions.find(item=>item.id===id);if(!session||get().isStreaming(id)){set({error:"Pare a tarefa deste chat antes de fechá-lo."});return false;}try{await window.nexo.deleteConversation(id);set(state=>{const sessions=state.sessions.filter(item=>item.id!==id);return{sessions,activeSessionId:state.activeSessionId===id?sessions[0]?.id??"":state.activeSessionId,error:null};});if(!get().sessions.length)await get().createSession();return true;}catch(error){set({error:error instanceof Error?error.message:String(error)});return false;}},
  renameSession:async(id,title)=>{try{const conversation=await window.nexo.renameConversation(id,title) as ConversationSummary;set(state=>({sessions:state.sessions.map(item=>item.id===id?{...item,title:conversation.title,updatedAt:conversation.updatedAt}:item)}));}catch(error){set({error:error instanceof Error?error.message:String(error)});}},
  selectSession:id=>set(state=>state.sessions.some(item=>item.id===id)?{activeSessionId:id}:{}),
  isStreaming:id=>{const session=get().sessions.find(item=>item.id===id);return Boolean(session?.activeTaskId&&["running","waiting_approval"].includes(session.status));},
  handleTaskEvent:value=>{if(!value||typeof value!=="object")return;const event=value as TaskEvent;if(typeof event.taskId!=="string")return;if(event.kind==="token"&&typeof event.token==="string"){set(state=>({tasks:state.tasks.map(task=>task.id===event.taskId?{...task,progressText:(task.progressText??"")+event.token}:task)}));return;}if(event.task){set(state=>{const active=["queued","running","waiting_approval"].includes(event.task!.status),tasks=active?[...state.tasks.filter(task=>task.id!==event.taskId),event.task!]:state.tasks.filter(task=>task.id!==event.taskId),conversationId=event.task!.conversationId;return{tasks,sessions:state.sessions.map(session=>session.id===conversationId?{...session,activeTaskId:active?event.taskId:undefined,agentId:event.task!.agentId??session.agentId,runId:event.task!.runId??session.runId,status:taskStatus(event.task)}:session)};});}if(["completed","failed","cancelled"].includes(event.kind)){const id=event.task?.conversationId;if(id)void get().syncSession(id);else void get().sync();}},
  syncAttachments:async sessionId=>{const sessions=sessionId?get().sessions.filter(item=>item.id===sessionId):get().sessions,pending=sessions.flatMap(session=>session.attachments.filter(item=>item.status==="indexing").map(item=>({sessionId:session.id,item})));if(!pending.length)return;const tasks=(await Promise.all(pending.map(entry=>window.nexo.getTask(entry.item.taskId)))) as Array<BackgroundTask|undefined>;set(state=>({sessions:state.sessions.map(session=>({...session,attachments:session.attachments.map(item=>{const task=tasks.find((candidate:BackgroundTask|undefined)=>candidate?.id===item.taskId);if(task?.status==="completed"){const document=task.result as DocumentRecord;return{...item,name:document.name,status:"ready" as const,documentId:document.id};}return task?.status==="failed"?{...item,status:"failed" as const}:item;})}))}));},
  send:async(sessionId,text)=>{const value=text.trim(),state=get(),session=state.sessions.find(item=>item.id===sessionId);if(!session||!value||state.isStreaming(sessionId)||session.attachments.some(item=>item.status!=="ready"))return false;try{set({error:null});const task=await window.nexo.startChatTask(sessionId,value,session.attachments.flatMap(item=>item.documentId?[item.documentId]:[])) as BackgroundTask;set(current=>({sessions:current.sessions.map(item=>item.id===sessionId?{...item,attachments:[],activeTaskId:task.id,agentId:task.agentId,runId:task.runId,status:"running"}:item),tasks:[...current.tasks.filter(item=>item.id!==task.id),task]}));await get().syncSession(sessionId);return true;}catch(error){set({error:error instanceof Error?error.message:String(error)});return false;}},
  cancel:async sessionId=>{const session=get().sessions.find(item=>item.id===sessionId),task=session?.activeTaskId?get().tasks.find(item=>item.id===session.activeTaskId):undefined;if(!task)return;await window.nexo.cancelTask(task.id);await get().syncSession(sessionId);},
  attach:async sessionId=>{const task=await window.nexo.chooseDocument() as BackgroundTask|undefined;if(task)set(state=>({sessions:state.sessions.map(session=>session.id===sessionId?{...session,attachments:[...session.attachments,{taskId:task.id,name:"Documento selecionado",status:"indexing"}]}:session)}));},
  removeAttachment:(sessionId,id)=>set(state=>({sessions:state.sessions.map(session=>session.id===sessionId?{...session,attachments:session.attachments.filter(item=>item.taskId!==id)}:session)})),setFollowing:isFollowing=>set({isFollowing})
}));
