import { create } from "zustand";
import type { DashboardGadgetId, DashboardGadgetInstance, GadgetDefinition, GadgetSize } from "@nexo/shared";
type GadgetData={data:any;fetchedAt:string;stale:boolean;error?:string;loading?:boolean};
type DashboardState={layout:DashboardGadgetInstance[];catalog:GadgetDefinition[];data:Record<string,GadgetData>;loading:boolean;error?:string;editing:boolean;load:()=>Promise<void>;refresh:(instance:DashboardGadgetInstance,force?:boolean)=>Promise<void>;add:(id:DashboardGadgetId,configuration?:Record<string,unknown>)=>Promise<void>;remove:(id:string)=>Promise<void>;configure:(item:DashboardGadgetInstance,configuration:Record<string,unknown>)=>Promise<void>;resize:(id:string,size:GadgetSize)=>Promise<void>;reorder:(from:string,to:string)=>Promise<void>;setEditing:(value:boolean)=>void};
const api=()=>window.nexo.dashboard;
const refreshSequence=new Map<string,number>();
export const useDashboardStore=create<DashboardState>((set,get)=>({layout:[],catalog:[],data:{},loading:true,editing:false,
  async load(){set({loading:true,error:undefined});try{const [layout,catalog]=await Promise.all([api().getLayout(),api().getCatalog()]) as [DashboardGadgetInstance[],GadgetDefinition[]];set({layout,catalog,loading:false});for(const item of layout.filter(value=>value.enabled))void get().refresh(item);}catch(error){set({loading:false,error:error instanceof Error?error.message:"Não foi possível carregar o dashboard."});}},
  async refresh(instance,force=false){const id=instance.instanceId,request=(refreshSequence.get(id)??0)+1;refreshSequence.set(id,request);set(state=>{const current=state.data[id]??{data:undefined,fetchedAt:"",stale:false};return{data:{...state.data,[id]:{...current,loading:true,error:undefined}}};});try{const response=await (force?api().refreshGadget(instance.gadgetId,instance.configuration):api().getGadgetData(instance.gadgetId,instance.configuration)) as GadgetData;if(refreshSequence.get(id)!==request)return;set(state=>({data:{...state.data,[id]:{...response,loading:false}}}));}catch(error){if(refreshSequence.get(id)!==request)return;set(state=>{const current=state.data[id];return{data:{...state.data,[id]:{data:current?.data,fetchedAt:current?.fetchedAt??"",stale:Boolean(current?.fetchedAt)||Boolean(current?.stale),loading:false,error:error instanceof Error?error.message:"Gadget indisponível."}}};});}},
  async add(id,configuration={}){const item=await api().addGadget(id,configuration) as DashboardGadgetInstance;set(state=>({layout:[...state.layout,item]}));await get().refresh(item);},
  async remove(id){const layout=await api().removeGadget(id) as DashboardGadgetInstance[];set(state=>{const data={...state.data};delete data[id];return{layout,data};});},
  async configure(item,configuration){const updated=await api().configureGadget(item.instanceId,configuration,item.size) as DashboardGadgetInstance;set(state=>({layout:state.layout.map(value=>value.instanceId===item.instanceId?updated:value)}));await get().refresh(updated,true);},
  async resize(id,size){const item=get().layout.find(value=>value.instanceId===id);if(!item)return;await api().configureGadget(id,item.configuration,size);const layout=get().layout.map(value=>value.instanceId===id?{...value,size}:value);set({layout});await api().saveLayout(layout.map((value,position)=>({instanceId:value.instanceId,size:value.size,position})));},
  async reorder(from,to){const previous=[...get().layout],layout=[...previous],a=layout.findIndex(item=>item.instanceId===from),b=layout.findIndex(item=>item.instanceId===to);if(a<0||b<0||a===b)return;const [item]=layout.splice(a,1);layout.splice(b,0,item);set({layout});try{await api().saveLayout(layout.map((value,position)=>({instanceId:value.instanceId,size:value.size,position})));}catch(error){set({layout:previous,error:error instanceof Error?error.message:"Não foi possível salvar a ordem."});}},
  setEditing(value){set({editing:value});}
}));
