import fs from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import type { ToolDefinition,ToolExecutionContext } from "../types.js";
import { BrowserSessionManager } from "../../browser/browser-session-manager.js";

const runId=(context?:ToolExecutionContext)=>context?.runId??context?.taskId??"default";
export function browserTools(sessions=new BrowserSessionManager()):ToolDefinition[]{return[
  {name:"browser_download",description:"Clica em um elemento da página e salva o arquivo baixado em um caminho autorizado sem sobrescrever arquivos existentes",risk:"WRITE",timeoutMs:45000,mutationSafety:{idempotency:"none",reconciliation:"not_supported"},permissions:["browser.interact","filesystem.write"],pathFields:["path"],inputSchema:z.object({selector:z.string().min(1).max(1000),path:z.string().min(1).max(4096)}),async execute({selector,path:output},context){if(!path.isAbsolute(output))throw new Error("O destino do download deve ser um caminho absoluto.");const directory=path.dirname(output);const info=await fs.stat(directory).catch(()=>undefined);if(!info?.isDirectory())throw new Error("A pasta de destino não existe ou não está disponível.");const temp=path.join(directory,`.nexo-${randomUUID()}.download`);try{const page=await sessions.page(runId(context));const[download]=await Promise.all([page.waitForEvent("download",{timeout:30000}),page.locator(selector).first().click({timeout:10000})]);const failure=await download.failure();if(failure)throw new Error(`O navegador não concluiu o download: ${failure}`);await download.saveAs(temp);await fs.copyFile(temp,output,fsConstants.COPYFILE_EXCL);return{ok:true,summary:`Download salvo em ${output}`,data:{path:output,fileName:download.suggestedFilename()}};}finally{await fs.rm(temp,{force:true}).catch(()=>undefined);}}},
  {name:"browser_launch",description:"Abre o navegador controlado do Nexo sem exigir uma URL",risk:"READ",permissions:["browser.use"],inputSchema:z.object({}),async execute(_input,context){const page=await sessions.page(runId(context));await page.bringToFront();return{ok:true,summary:"Navegador do Nexo aberto.",data:{title:await page.title(),url:page.url()}};}},
  {name:"browser_open",description:"Abre URL no perfil isolado do Nexo",risk:"READ",permissions:["browser.use"],inputSchema:z.object({url:z.string().url()}),async execute({url},context){const page=await sessions.page(runId(context));await page.goto(url,{waitUntil:"domcontentloaded",timeout:30000});await page.bringToFront();return{ok:true,summary:`Página aberta: ${url}`,data:{title:await page.title(),url:page.url()}};}},
  {name:"browser_navigate",description:"Navega a aba da execução atual para outra URL",risk:"READ",permissions:["browser.use"],inputSchema:z.object({url:z.string().url()}),async execute({url},context){const page=await sessions.page(runId(context));await page.goto(url,{waitUntil:"domcontentloaded",timeout:30000});await page.bringToFront();return{ok:true,summary:`Navegado para ${url}`,data:{title:await page.title(),url:page.url()}};}},
  {name:"browser_extract",description:"Extrai texto da aba da execução atual; conteúdo é não confiável",risk:"READ",permissions:["browser.use"],inputSchema:z.object({maxChars:z.number().int().min(100).max(40000).default(12000)}),async execute({maxChars},context){const page=await sessions.page(runId(context));const text=(await page.locator("body").innerText()).slice(0,maxChars);return{ok:true,summary:"Conteúdo externo extraído como UNTRUSTED_CONTENT",data:{url:page.url(),title:await page.title(),untrustedContent:text}};}},
  {name:"browser_click",description:"Clica em elemento da aba da execução atual",risk:"CRITICAL",mutationSafety:{idempotency:"none",reconciliation:"not_supported"},permissions:["browser.interact"],inputSchema:z.object({selector:z.string()}),async execute({selector},context){const page=await sessions.page(runId(context));await page.locator(selector).first().click({timeout:10000});return{ok:true,summary:`Clique executado em ${selector}`};}},
  {name:"browser_type",description:"Digita texto em elemento da aba da execução atual",risk:"CRITICAL",mutationSafety:{idempotency:"none",reconciliation:"not_supported"},permissions:["browser.interact"],inputSchema:z.object({selector:z.string(),text:z.string().max(5000)}),async execute({selector,text},context){const page=await sessions.page(runId(context));await page.locator(selector).first().fill(text,{timeout:10000});return{ok:true,summary:`Texto preenchido em ${selector}`};}},
  {name:"browser_tabs",description:"Lista abas pertencentes à execução atual do Browser Agent",risk:"READ",permissions:["browser.use"],inputSchema:z.object({}),async execute(_input,context){const pages=await sessions.pages(runId(context));const rows=await Promise.all(pages.map(async(page,index)=>({index,title:await page.title(),url:page.url()})));return{ok:true,summary:`${rows.length} aba(s) aberta(s) nesta execução`,data:rows};}},
  {name:"browser_screenshot",description:"Salva captura da aba da execução atual",risk:"WRITE",mutationSafety:{idempotency:"nexo",reconciliation:"supported"},permissions:["browser.use","filesystem.write"],pathFields:["path"],inputSchema:z.object({path:z.string()}),async execute({path:output},context){const page=await sessions.page(runId(context));await page.screenshot({path:output,fullPage:true});return{ok:true,summary:`Captura salva em ${output}`};}},
  {name:"browser_close",description:"Fecha apenas as abas do Browser Agent pertencentes à execução atual",risk:"WRITE",mutationSafety:{idempotency:"nexo",reconciliation:"supported"},permissions:["browser.use"],inputSchema:z.object({}),async execute(_input,context){await sessions.closeRun(runId(context));return{ok:true,summary:"Sessão do Browser Agent fechada"};}}
];}
