import type { RiskLevel, ToolResult } from "@nexo/shared";
import type { NexoDatabase } from "../../database/db.js";
import type { ActionExecutionStatus, PreparedAction } from "./types.js";

export type ExecutionRecord = { executionId: string; runId?: string; toolName: string; fingerprint: string; idempotencyKey?: string; mutatesState: boolean; risk: RiskLevel; status: ActionExecutionStatus; input: Record<string, unknown>; result?: ToolResult; error?: string; createdAt: string; dispatchStartedAt?: string; completedAt?: string; reconciliation?: unknown; reconciledAt?: string };
export class ExecutionRecordRepository {
  constructor(private readonly db: NexoDatabase) {}
  prepare(action: PreparedAction, runId?: string) { const existing = this.get(action.executionId); if (existing) {if(existing.toolName!==action.toolName||existing.fingerprint!==action.fingerprint||JSON.stringify(existing.input)!==JSON.stringify(action.input))throw new Error("executionId já pertence a outra ação.");return existing;} const now = new Date().toISOString(); this.db.run("INSERT INTO execution_records(execution_id,run_id,tool_name,fingerprint,idempotency_key,mutates_state,risk,status,input_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)", [action.executionId, runId ?? null, action.toolName, action.fingerprint, action.idempotencyKey ?? null, action.mutatesState ? 1 : 0, action.risk, "PREPARED", JSON.stringify(action.input), now]); return this.getRequired(action.executionId); }
  markDispatching(executionId: string) { this.transition(executionId, "DISPATCHING", { dispatchStartedAt: new Date().toISOString() }); }
  complete(executionId: string, status: "SUCCEEDED" | "FAILED" | "RESULT_UNKNOWN", values: { result?: ToolResult; error?: string } = {}) { this.transition(executionId, status, { ...values, completedAt: new Date().toISOString() }); }
  reconcile(executionId: string, status: "RECONCILED_SUCCESS" | "RECONCILED_FAILURE" | "UNRESOLVED", reconciliation: unknown) { this.transition(executionId, status, { reconciliation, reconciledAt: new Date().toISOString() }); }
  markReconciling(executionId:string){this.transition(executionId,"RECONCILING",{});}
  pendingReconciliation(){return this.db.all<Row>("SELECT * FROM execution_records WHERE status IN ('DISPATCHING','RESULT_UNKNOWN','RECONCILING','UNRESOLVED') ORDER BY created_at").map(map);}
  get(executionId: string) { const row = this.db.get<Row>("SELECT * FROM execution_records WHERE execution_id=?", [executionId]); return row && map(row); }
  getRequired(executionId: string) { const record = this.get(executionId); if (!record) throw new Error(`Registro de execução não encontrado: ${executionId}`); return record; }
  private transition(executionId: string, status: ExecutionRecord["status"], values: Partial<Pick<ExecutionRecord, "result" | "error" | "dispatchStartedAt" | "completedAt" | "reconciliation" | "reconciledAt">>) { const record = this.getRequired(executionId); this.db.run("UPDATE execution_records SET status=?,result_json=?,error=?,dispatch_started_at=?,completed_at=?,reconciliation_json=?,reconciled_at=? WHERE execution_id=?", [status, values.result === undefined ? json(record.result) : json(values.result), values.error ?? record.error ?? null, values.dispatchStartedAt ?? record.dispatchStartedAt ?? null, values.completedAt ?? record.completedAt ?? null, values.reconciliation === undefined ? json(record.reconciliation) : json(values.reconciliation), values.reconciledAt ?? record.reconciledAt ?? null, executionId]); }
}
type Row = { execution_id: string; run_id: string | null; tool_name: string; fingerprint: string; idempotency_key: string | null; mutates_state: number; risk: RiskLevel; status: ExecutionRecord["status"]; input_json: string; result_json: string | null; error: string | null; created_at: string; dispatch_started_at: string | null; completed_at: string | null; reconciliation_json: string | null; reconciled_at: string | null };
function map(row: Row): ExecutionRecord { return { executionId: row.execution_id, ...(row.run_id ? { runId: row.run_id } : {}), toolName: row.tool_name, fingerprint: row.fingerprint, ...(row.idempotency_key ? { idempotencyKey: row.idempotency_key } : {}), mutatesState: Boolean(row.mutates_state), risk: row.risk, status: row.status, input: JSON.parse(row.input_json), ...(row.result_json ? { result: JSON.parse(row.result_json) } : {}), ...(row.error ? { error: row.error } : {}), createdAt: row.created_at, ...(row.dispatch_started_at ? { dispatchStartedAt: row.dispatch_started_at } : {}), ...(row.completed_at ? { completedAt: row.completed_at } : {}), ...(row.reconciliation_json ? { reconciliation: JSON.parse(row.reconciliation_json) } : {}), ...(row.reconciled_at ? { reconciledAt: row.reconciled_at } : {}) }; }
function json(value: unknown) { return value === undefined ? null : JSON.stringify(value); }
