import type { PreparedAction } from "../execution/types.js";
import type { AgentResourceContext, AgentTaskState } from "../goal/goal-types.js";
import type {GoalOutcome} from "../outcome/types.js";
import type {GoalProgressState} from "../outcome/goal-progress-state.js";

export type AgentLoopStatus = "DECIDING" | "PREFLIGHT" | "WAITING_APPROVAL" | "WAITING_RESOURCE" | "EXECUTING" | "OBSERVING" | "RECONCILING" | "WAITING_EXTERNAL_PROGRESS" | "RESULT_UNKNOWN" | "COMPLETED" | "FAILED" | "CANCELLED";
export type AgentMessageTrust = "TRUSTED_LOCAL" | "UNTRUSTED_CONTENT" | "SENSITIVE_LOCAL";
export type AgentToolCall = { id: string; name: string; arguments: Record<string, unknown> };
export type AgentModelMessage = { role: "system" | "user" | "assistant" | "tool"; content: string; trust?: AgentMessageTrust; toolCallId?: string; toolName?: string; toolCalls?: AgentToolCall[] };
export type AgentToolSchema = { name: string; description: string; parameters?: unknown; polling?: {allowed:true;minIntervalMs:number;maxDurationMs:number;maxAttempts:number;progressFields?:string[]} };
export type AgentModelTurn = { content?: string; toolCalls: AgentToolCall[] };
export type AgentTurnRequest = { messages: AgentModelMessage[]; tools: AgentToolSchema[]; model?: string };

export interface PendingAgentAction { callId: string; toolName: string; input: Record<string, unknown>; fingerprint: string; executionId: string; idempotencyKey?: string; iteration: number; mutatesState: boolean; risk:PreparedAction["risk"];requiresApproval:boolean;approvalId?: string; }
export type AgentReference = { kind: "id" | "path" | "url" | "message_id" | "event_id" | "thread_id" | "file_id" | "process_id"; value: string; label?: string };
export interface AgentObservation { toolCallId: string; toolName: string; ok: boolean; summary: string; data?: unknown; references?: AgentReference[]; trust: AgentMessageTrust; truncated: boolean; originalBytes?: number; encodedBytes?: number; progress?: { key?: string; value?: string | number }; }
export interface AgentLoopState { version: 2; runId: string; conversationId?: string; taskId?: string; userRequest: string; messages: AgentModelMessage[]; observations: AgentObservation[]; pendingAction?: PendingAgentAction; iteration: number; toolCallCount: number; consecutiveFailures: number; protocolRepairCount: number; actionFingerprints: string[]; observationFingerprints: string[]; activeToolNames:string[];model?:string;resources?:AgentResourceContext;taskState?:AgentTaskState;startedAt: string; updatedAt: string; deadlineAt: string; status: AgentLoopStatus; executionSafetyState?:"NO_ACTION"|"READ_ONLY_EXECUTED"|"PREFLIGHT_MUTATION"|"WAITING_APPROVAL"|"DISPATCHING"|"MUTATION_COMPLETED"|"RESULT_UNKNOWN"; finalResponse?: string; goalOutcome?:GoalOutcome;goalProgress?:GoalProgressState;correctionRounds?:number;lastVerifiedObservationIndex?:number; }

export type AgentLoopLimits = { maxIterations: number; maxToolCalls: number; maxExecutionMs: number; maxProtocolRepairAttempts: number; maxSchemaRepairAttempts: number; maxConsecutiveFailures: number; maxSameActionRepeats: number; maxSameObservationRepeats: number; maxObservationBytes: number; maxTotalObservationBytes: number; maxToolResultReferences: number; };
export const DEFAULT_AGENT_LOOP_LIMITS: AgentLoopLimits = { maxIterations: 10, maxToolCalls: 15, maxExecutionMs: 120_000, maxProtocolRepairAttempts: 2, maxSchemaRepairAttempts: 2, maxConsecutiveFailures: 3, maxSameActionRepeats: 2, maxSameObservationRepeats: 2, maxObservationBytes: 64_000, maxTotalObservationBytes: 256_000, maxToolResultReferences: 100 };
export interface AgentLoopPersistence { save(state: AgentLoopState): Promise<void>; }
export type AgentExecutionContext = { runId: string; userRequest: string; conversationId?: string; taskId?: string; signal?: AbortSignal };
export type AgentLoopDependencies = { agentTurn(request: AgentTurnRequest, signal?: AbortSignal): Promise<AgentModelTurn>; tools?(): AgentToolSchema[];toolsForTurn?(state:AgentLoopState):Promise<AgentToolSchema[]>;preflight(name: string, input: Record<string, unknown>, context: AgentExecutionContext): Promise<import("../execution/types.js").ActionPreflightResult>; execute(action: PreparedAction, context: AgentExecutionContext): Promise<import("../execution/types.js").ActionExecutionResult>; reconcileRun?(state:AgentLoopState,executionId:string,signal?:AbortSignal):Promise<AgentLoopState>; observe(result: import("../execution/types.js").ActionExecutionResult, callId: string): AgentObservation; onObservation?(state:AgentLoopState,observation:AgentObservation):Promise<void>|void; persistence?: AgentLoopPersistence; metric?(name:string,value?:number,labels?:Record<string,string|number|boolean>):void; };
