import { contextBridge, ipcRenderer } from "electron";

const api = {
  chat: (text: string) => ipcRenderer.invoke("nexo:chat", text),
  startChatTask: (text: string, attachmentIds: string[] = []) => ipcRenderer.invoke("nexo:chat:start", text, attachmentIds),
  listConnections: () => ipcRenderer.invoke("nexo:connections:list"),
  connect: (provider: "google" | "microsoft", capabilities: string[]) => ipcRenderer.invoke("nexo:connections:connect", provider, capabilities),
  disconnect: (id: string) => ipcRenderer.invoke("nexo:connections:disconnect", id),
  testConnection: (id: string) => ipcRenderer.invoke("nexo:connections:test", id),
  addConnectionCapabilities: (id: string, capabilities: string[]) => ipcRenderer.invoke("nexo:connections:add-capabilities", id, capabilities),
  chooseDocument: () => ipcRenderer.invoke("nexo:documents:choose"),
  listRecentDocuments: () => ipcRenderer.invoke("nexo:documents:list-recent"),
  getDocument: (id: string) => ipcRenderer.invoke("nexo:documents:get", id),
  previewDocument: (id: string) => ipcRenderer.invoke("nexo:documents:preview", id),
  documentPreviewData: (id: string) => ipcRenderer.invoke("nexo:documents:preview-data", id),
  exportDocument: (id: string) => ipcRenderer.invoke("nexo:documents:export", id),
  editDocument: (id: string, plan: unknown) => ipcRenderer.invoke("nexo:documents:edit", id, plan),
  chatHistory: () => ipcRenderer.invoke("nexo:chat:history"),
  listTasks: (limit = 50) => ipcRenderer.invoke("nexo:tasks:list", limit),
  listActiveTasks: () => ipcRenderer.invoke("nexo:tasks:active"),
  getTask: (id: string) => ipcRenderer.invoke("nexo:task:get", id),
  status: () => ipcRenderer.invoke("nexo:status"),
  getSettings: () => ipcRenderer.invoke("nexo:settings:get"),
  updateSettings: (patch: any) => ipcRenderer.invoke("nexo:settings:update", patch),
  listApprovals: () => ipcRenderer.invoke("nexo:approvals:list"),
  resolveApproval: (id: string, approved: boolean) => ipcRenderer.invoke("nexo:approvals:resolve", id, approved),
  listAudit: () => ipcRenderer.invoke("nexo:audit:list"),
  listMemories: () => ipcRenderer.invoke("nexo:memory:list"),
  addMemory: (key: string, value: string, category?: string) => ipcRenderer.invoke("nexo:memory:add", key, value, category),
  searchMemory: (query: string) => ipcRenderer.invoke("nexo:memory:search", query),
  removeMemory: (key: string) => ipcRenderer.invoke("nexo:memory:remove", key),
  clearMemory: () => ipcRenderer.invoke("nexo:memory:clear"),
  listAutomations: () => ipcRenderer.invoke("nexo:automation:list"),
  createAutomation: (data: any) => ipcRenderer.invoke("nexo:automation:create", data),
  toggleAutomation: (id: string, enabled: boolean) => ipcRenderer.invoke("nexo:automation:toggle", id, enabled),
  removeAutomation: (id: string) => ipcRenderer.invoke("nexo:automation:remove", id),
  chooseFolder: () => ipcRenderer.invoke("nexo:choose-folder"),
  openPath: (path: string) => ipcRenderer.invoke("nexo:open-path", path),
  openExternal: (url: string) => ipcRenderer.invoke("nexo:open-external", url),
  trashItem: (path: string) => ipcRenderer.invoke("nexo:trash-item", path),
  backup: () => ipcRenderer.invoke("nexo:backup")
};

contextBridge.exposeInMainWorld("nexo", api);
export type NexoDesktopApi = typeof api;
