import { Container,Text,Texture } from "pixi.js";
import type { AgentVisualEvent,OfficeStationId } from "@nexo/shared";
import { AgentSprite } from "./AgentSprite";import { AgentMovement } from "./AgentMovement";import { AgentActionQueue,type AgentAction,STATE_DURATION } from "./AgentActionQueue";import { IdleMovementController } from "./IdleMovementController";import { Grid } from "../navigation/Grid";import { findPath } from "../navigation/AStar";import { smoothPath } from "../navigation/PathSmoothing";import { IDLE_WANDER_POINTS,slotFor,type WorldPoint } from "../data/office-layout";import type { OctopusAnimation } from "../data/sprite-manifest";
export class OfficeAgent extends Container{readonly id:string;readonly sprite:AgentSprite;readonly movement=new AgentMovement();readonly queue=new AgentActionQueue();readonly idle:IdleMovementController;station:OfficeStationId="central-desk";activeRunId?:string;conversationId?:string;taskId?:string;private current?:AgentAction;private currentSince=0;private wandering=false;private statusLabel:Text;private tooltip:Text;private chatTitle="Livre";private lastStatus="Livre";private runStartedAt=0;navigationMs=0;navigationFailures=0;
constructor(id:string,sheet:Texture,private grid:Grid,spawn:WorldPoint,onClick:(agent:OfficeAgent)=>void){super();this.id=id;this.position.set(spawn.x,spawn.y);this.sprite=new AgentSprite(sheet);this.addChild(this.sprite);this.statusLabel=new Text({text:"",style:{fontFamily:"monospace",fontSize:17,fill:"#ffffff",align:"center",stroke:{color:"#121827",width:5}}});this.statusLabel.anchor.set(.5,1);this.statusLabel.position.set(0,-92);this.statusLabel.zIndex=5;this.addChild(this.statusLabel);this.tooltip=new Text({text:"",style:{fontFamily:"monospace",fontSize:14,fill:"#e8ecf6",align:"left",wordWrap:true,wordWrapWidth:230,stroke:{color:"#0b1020",width:5}}});this.tooltip.anchor.set(.5,1);this.tooltip.position.set(0,-126);this.tooltip.visible=false;this.tooltip.zIndex=8;this.addChild(this.tooltip);this.eventMode="static";this.cursor="pointer";this.on("pointertap",()=>onClick(this));this.on("pointerover",()=>{this.tooltip.visible=true;});this.on("pointerout",()=>{this.tooltip.visible=false;});this.idle=new IdleMovementController(IDLE_WANDER_POINTS);this.sprite.play("idle");this.setLabel("Livre");}
consume(event:AgentVisualEvent,reduced=false){if(event.type==="agent.online"||event.type==="agent.offline"){this.cancelWander();this.sprite.play(event.type==="agent.online"?"idle":"offline");this.setLabel(event.type==="agent.online"?"Livre":"Ollama offline");return;}if(this.activeRunId!==event.runId)this.runStartedAt=Date.now();this.activeRunId=event.runId;this.conversationId=event.conversationId??this.conversationId;this.taskId=event.taskId??this.taskId;const title=event.metadata?.chatTitle;if(typeof title==="string"&&title.trim())this.chatTitle=title.trim();this.cancelWander();if(["run.completed","run.failed","run.cancelled"].includes(event.type))this.queue.clear();this.queue.enqueue(event,this.station);if(!this.current)this.startNext(reduced);}
update(delta:number,reduced=false){if(this.current){if(this.current.kind==="move"){if(reduced)this.finishAction(true);else{const result=this.movement.update(this.position,delta);this.sprite.play((`walk${result.direction[0].toUpperCase()}${result.direction.slice(1)}`) as OctopusAnimation);if(result.arrived)this.finishAction(false);}}else{const transient=this.current.state in STATE_DURATION;if(Date.now()-this.currentSince>=this.current.minimumMs&&(transient||this.queue.size()>0))this.finishAction(reduced);}}else if(this.wandering){const result=this.movement.update(this.position,delta);this.sprite.play((`walk${result.direction[0].toUpperCase()}${result.direction.slice(1)}`) as OctopusAnimation);if(result.arrived){this.wandering=false;this.sprite.play("idle");this.setLabel("Livre");this.idle.schedule();}}else{const point=this.idle.next();if(point&&this.route(point)){this.wandering=true;this.setLabel("Passeando");}else this.sprite.play("idle");}this.zIndex=this.y;this.sprite.update(delta);if(this.tooltip.visible)this.refreshTooltip();}
cancelWander(){if(!this.wandering)return;this.wandering=false;this.movement.clear();this.idle.cancel();}
private startNext(reduced:boolean){this.current=this.queue.next();if(!this.current){this.sprite.play("idle");this.setLabel("Livre");this.activeRunId=undefined;this.taskId=undefined;return;}this.currentSince=Date.now();this.setLabel(this.current.label);if(this.current.kind==="move"){const target=slotFor(this.current.stationId,this.id);if(!this.route(target)){this.navigationFailures++;this.current={...this.current,kind:"animate",state:"error",label:"Estação inacessível",minimumMs:1000};this.currentSince=Date.now();this.setLabel("Estação inacessível");this.sprite.play("error");return;}if(reduced){this.position.set(target.x,target.y);this.finishAction(true);}}else this.sprite.play(this.current.state==="walking"||this.current.state==="wander"?"idle":this.current.state as OctopusAnimation);}
private route(target:WorldPoint){const start=this.grid.toGrid(this.x,this.y),started=performance.now(),raw=findPath(this.grid,start,this.grid.toGrid(target.x,target.y));this.navigationMs=performance.now()-started;if(!raw.length)return false;const path=smoothPath(raw).map(point=>this.grid.toWorld(point));path.push({x:target.x,y:target.y});this.movement.setPath(path);return true;}
private finishAction(reduced:boolean){if(this.current?.kind==="move"){const target=slotFor(this.current.stationId,this.id);if(reduced)this.position.set(target.x,target.y);this.station=this.current.stationId;this.queue.completeMove(this.current.stationId);}this.current=undefined;this.startNext(reduced);}
private setLabel(label:string){this.lastStatus=label;const project=this.chatTitle&&this.chatTitle!=="Livre"?this.chatTitle:"Livre";this.statusLabel.text=`${this.id.replace("agent-","🐙 ")} · ${project}\n${label}`;this.refreshTooltip();}
private refreshTooltip(){const elapsed=this.runStartedAt&&this.activeRunId?Math.max(0,Math.floor((Date.now()-this.runStartedAt)/1000)):0;this.tooltip.text=`${this.id.replace("agent-","Agente ")}\nChat: ${this.chatTitle}\nEstado: ${this.lastStatus}${this.activeRunId?`\nTempo: ${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`:""}`;}
debug(){const grid=this.grid.toGrid(this.x,this.y);return{id:this.id,station:this.station,runId:this.activeRunId,conversationId:this.conversationId,x:Math.round(this.x),y:Math.round(this.y),gridX:grid.x,gridY:grid.y,pathNodes:this.movement.path.length,queue:this.queue.size(),wander:this.wandering,navigationMs:this.navigationMs,navigationFailures:this.navigationFailures,distance:Math.round(this.movement.distanceTravelled)};}}
