#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
const args=parseArgs(process.argv.slice(2));
const resolved=resolveModel(args);
const base=String(args.url??process.env.NEXO_OLLAMA_URL??process.env.OLLAMA_HOST??resolved.ollamaUrl??"http://127.0.0.1:11434").replace(/\/$/,"");
const timeoutMs=number(args.timeout??process.env.NEXO_BROWSER_DIAGNOSTIC_TIMEOUT_MS,120_000);
const report={ok:false,timestamp:new Date().toISOString(),model:resolved.model,modelSource:resolved.source,endpoint:new URL(base).origin,connection:{ok:false},version:null,installedModels:{count:0,names:[],selectedInstalled:false},show:null,probes:[]};
try{
  const version=await request(`${base}/api/version`,{signal:AbortSignal.timeout(timeoutMs)});report.connection={ok:true,httpStatus:version.status,latencyMs:version.latencyMs};report.version=typeof version.body?.version==="string"?version.body.version:null;
  const tags=await request(`${base}/api/tags`,{signal:AbortSignal.timeout(timeoutMs)});const names=[...new Set((Array.isArray(tags.body?.models)?tags.body.models:[]).flatMap(item=>[item?.name,item?.model]).filter(item=>typeof item==="string"))].sort();report.installedModels={count:names.length,names,selectedInstalled:names.includes(resolved.model)};
  const show=await request(`${base}/api/show`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:resolved.model}),signal:AbortSignal.timeout(timeoutMs)});report.show={ok:show.ok,httpStatus:show.status,latencyMs:show.latencyMs,capabilities:Array.isArray(show.body?.capabilities)?show.body.capabilities.filter(item=>typeof item==="string"):[],error:show.ok?null:safeMessage(show.body)};
  if(!show.ok||!report.installedModels.selectedInstalled)throw new Error(show.ok?"selected_model_not_installed":"model_show_failed");
  for(const probe of [simpleProbe(),representativeProbe()])for(const think of ["omitted",false,true])report.probes.push(await toolProbe(base,resolved.model,probe,think,timeoutMs));
  report.ok=report.probes.every(item=>item.ok&&item.validToolCall);
}catch(error){report.error=safeError(error);}
console.log(JSON.stringify(report,null,2));process.exitCode=report.ok?0:1;

async function toolProbe(base,model,probe,think,timeoutMs){const body={model,messages:probe.messages,tools:probe.tools,stream:false,options:{temperature:0,num_predict:2048}};if(think!=="omitted")body.think=think;try{const response=await request(`${base}/api/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});const summary=summarize(response.body?.message,new Set(probe.tools.map(tool=>tool.function.name)));return{probe:probe.name,think,ok:response.ok,httpStatus:response.status,latencyMs:response.latencyMs,...summary,error:response.ok?null:safeMessage(response.body)};}catch(error){return{probe:probe.name,think,ok:false,httpStatus:null,latencyMs:timeoutMs,validToolCall:false,contentLength:0,thinkingLength:0,structuredToolCallCount:0,qwenMarkupToolCallCount:0,invalidMarkupCount:0,toolNames:[],error:safeError(error)};}}
function simpleProbe(){return{name:"simple",messages:[{role:"system",content:"Call exactly one provided tool. Do not answer with prose."},{role:"user",content:"Open https://example.com."}],tools:[tool("browser_navigate","Navigate to one URL",{type:"object",properties:{url:{type:"string"}},required:["url"],additionalProperties:false})]};}
function representativeProbe(){return{name:"browser_agent_context",messages:[{role:"system",content:"You are a browser agent. Use one browser tool per turn and finish through the completion tool."},{role:"user",content:"Entre no site InfoMoney e resuma as principais notícias."}],tools:[tool("browser_navigate","Navigate to a URL",{type:"object",properties:{url:{type:"string"}},required:["url"]}),tool("browser_click","Click an element",{type:"object",properties:{index:{type:"number"}},required:["index"]}),tool("browser_extract","Extract visible page facts",{type:"object",properties:{query:{type:"string"}},required:["query"]}),tool("browser_done","Complete the task",{type:"object",properties:{summary:{type:"string"}},required:["summary"]})]};}
function tool(name,description,parameters){return{type:"function",function:{name,description,parameters}};}
function summarize(message,allowed){const content=typeof message?.content==="string"?message.content:"",thinking=typeof message?.thinking==="string"?message.thinking:"";const names=[],valid=[];let structured=0,markup=0,invalid=0;if(Array.isArray(message?.tool_calls))for(const item of message.tool_calls){const name=item?.function?.name;if(typeof name!=="string")continue;structured++;names.push(name);if(allowed.has(name))valid.push(name);}for(const match of content.matchAll(/<tool_call>\s*([\s\S]*?)\s*<\/tool_call>/gi)){try{const parsed=JSON.parse(match[1]);const name=parsed?.function?.name??parsed?.name;if(typeof name!=="string"||!allowed.has(name)){invalid++;continue;}markup++;names.push(name);valid.push(name);}catch{invalid++;}}return{validToolCall:valid.length>0,contentLength:content.length,thinkingLength:thinking.length,structuredToolCallCount:structured,qwenMarkupToolCallCount:markup,invalidMarkupCount:invalid,toolNames:[...new Set(names)].sort()};}
async function request(url,init){const started=Date.now();let response;try{response=await fetch(url,init);}catch(error){throw new Error(`endpoint_unavailable:${safeError(error)}`);}let body;try{body=await response.json();}catch{body={error:"invalid_json"};}return{ok:response.ok,status:response.status,latencyMs:Date.now()-started,body};}
function resolveModel(args){if(args.model)return{model:String(args.model).trim(),source:"cli:--model"};if(process.env.NEXO_BROWSER_AGENT_MODEL?.trim())return{model:process.env.NEXO_BROWSER_AGENT_MODEL.trim(),source:"environment:NEXO_BROWSER_AGENT_MODEL"};const persisted=readPersistedGlobalSettings();if(persisted?.model)return{model:persisted.model,ollamaUrl:persisted.ollamaUrl,source:"global_setting"};if(process.env.NEXO_MODEL?.trim())return{model:process.env.NEXO_MODEL.trim(),source:"environment:NEXO_MODEL"};if(process.env.OLLAMA_MODEL?.trim())return{model:process.env.OLLAMA_MODEL.trim(),source:"environment:OLLAMA_MODEL"};return{model:"qwen3:4b",source:"doctor_default"};}
function readPersistedGlobalSettings(){try{const appData=process.env.APPDATA;if(!appData)return null;const file=path.join(appData,"NexoAI","nexo.db");const text=fs.readFileSync(file).toString("utf8");const match=text.match(/"model":"([A-Za-z0-9._:/-]+)","ollamaUrl":"(https?:[^"\\]+)"/);return match?{model:match[1],ollamaUrl:match[2]}:null;}catch{return null;}}
function safeMessage(body){const value=typeof body?.error==="string"?body.error:typeof body?.message==="string"?body.message:"unknown_error";return value.replace(/[\u0000-\u001f\u007f]+/g," ").replace(/\s+/g," ").trim().slice(0,240);}
function safeError(error){return error instanceof Error?`${error.name}:${error.message}`.slice(0,300):String(error).slice(0,300);}
function number(value,fallback){const parsed=Number(value??fallback);return Number.isFinite(parsed)&&parsed>=1000?parsed:fallback;}
function parseArgs(values){const result={};for(let index=0;index<values.length;index++){if(values[index]==="--model")result.model=values[++index];else if(values[index]==="--url")result.url=values[++index];else if(values[index]==="--timeout")result.timeout=values[++index];}return result;}
