export type AutomationActionRisk = "read" | "write" | "critical";
export type AutomationActionField = { key:string;label:string;type:"text"|"number"|"select"|"connection"|"path"|"boolean";required?:boolean;options?:Array<{value:string;label:string}>;placeholder?:string };
export type AutomationActionCatalogItem = { id:string;title:string;description:string;category:"email"|"calendar"|"filesystem"|"system"|"browser"|"web"|"apps"|"ai"|"output"|"nexo";icon:string;requiredCapabilities:string[];risk:AutomationActionRisk;fields:AutomationActionField[] };

export const AUTOMATION_ACTION_CATALOG: AutomationActionCatalogItem[] = [
  { id:"nexo.command",title:"Pedir ao Nexo",description:"Executa uma tarefa usando o agente somente quando uma ação estruturada não for suficiente.",category:"nexo",icon:"sparkles",requiredCapabilities:[],risk:"read",fields:[{key:"command",label:"O que o Nexo deve fazer?",type:"text",required:true}] },
  { id:"system.open_application",title:"Abrir aplicativo",description:"Abre um aplicativo permitido pelo Nexo.",category:"apps",icon:"monitor",requiredCapabilities:[],risk:"write",fields:[{key:"application",label:"Aplicativo",type:"text",required:true,placeholder:"chrome, vscode, edge…"}] },
  { id:"filesystem.open_path",title:"Abrir arquivo ou pasta",description:"Abre um caminho autorizado no aplicativo padrão.",category:"filesystem",icon:"folder-open",requiredCapabilities:[],risk:"write",fields:[{key:"path",label:"Caminho",type:"path",required:true}] },
  { id:"filesystem.copy",title:"Copiar arquivo",description:"Copia um arquivo entre pastas autorizadas.",category:"filesystem",icon:"copy",requiredCapabilities:[],risk:"write",fields:[{key:"source",label:"Origem",type:"path",required:true},{key:"destination",label:"Destino",type:"path",required:true}] },
  { id:"filesystem.rename",title:"Renomear arquivo",description:"Renomeia um arquivo para outro caminho autorizado.",category:"filesystem",icon:"file-pen",requiredCapabilities:[],risk:"write",fields:[{key:"path",label:"Caminho atual",type:"path",required:true},{key:"newPath",label:"Novo caminho",type:"path",required:true}] },
  { id:"filesystem.create_folder",title:"Criar pasta",description:"Cria uma pasta em um local autorizado.",category:"filesystem",icon:"folder-plus",requiredCapabilities:[],risk:"write",fields:[{key:"path",label:"Caminho da pasta",type:"path",required:true}] },
  { id:"browser.open_url",title:"Abrir URL",description:"Abre uma página no navegador padrão.",category:"apps",icon:"globe",requiredCapabilities:[],risk:"write",fields:[{key:"url",label:"URL",type:"text",required:true,placeholder:"https://…"}] },
  { id:"browser.download",title:"Baixar arquivo pelo navegador",description:"Clica em um elemento da página e salva o download em uma pasta permitida, sem substituir arquivos existentes. Requer automação de navegador ativada.",category:"browser",icon:"download",requiredCapabilities:["browser.interact","filesystem.write"],risk:"write",fields:[{key:"selector",label:"Seletor do botão ou link",type:"text",required:true,placeholder:"#download"},{key:"path",label:"Caminho completo do arquivo",type:"path",required:true}] },
  { id:"browser.click",title:"Clicar no navegador",description:"Clica em um elemento da aba controlada do Nexo. Requer automação de navegador ativada.",category:"browser",icon:"pointer",requiredCapabilities:["browser.interact"],risk:"critical",fields:[{key:"selector",label:"Seletor do elemento",type:"text",required:true,placeholder:"#continuar ou button[type=submit]"}] },
  { id:"browser.input",title:"Preencher campo no navegador",description:"Preenche um campo da aba controlada do Nexo. Requer automação de navegador ativada.",category:"browser",icon:"keyboard",requiredCapabilities:["browser.interact"],risk:"critical",fields:[{key:"selector",label:"Seletor do campo",type:"text",required:true,placeholder:"input[name=email]"},{key:"text",label:"Texto",type:"text",required:true}] },
  { id:"web.search",title:"Pesquisar na web",description:"Pesquisa conteúdo público sem abrir o navegador.",category:"web",icon:"search",requiredCapabilities:[],risk:"read",fields:[{key:"query",label:"O que pesquisar?",type:"text",required:true}] },
  { id:"web.fetch",title:"Ler página web",description:"Extrai o texto principal de uma página pública sem abrir o navegador.",category:"web",icon:"globe",requiredCapabilities:[],risk:"read",fields:[{key:"url",label:"URL da página",type:"text",required:true,placeholder:"https://…"}] },
  { id:"system.wait",title:"Aguardar",description:"Aguarda antes de executar a próxima etapa (máximo de 5 minutos).",category:"system",icon:"clock",requiredCapabilities:[],risk:"read",fields:[{key:"seconds",label:"Segundos",type:"number",required:true}] },
  { id:"email.summary",title:"Resumir e-mail",description:"Resume a mensagem recebida pelo gatilho.",category:"email",icon:"mail",requiredCapabilities:["email.read"],risk:"read",fields:[] },
  { id:"email.mark_read",title:"Marcar como lido",description:"Marca a mensagem do gatilho como lida.",category:"email",icon:"mail-check",requiredCapabilities:["email.modify"],risk:"write",fields:[] },
  { id:"email.archive",title:"Arquivar e-mail",description:"Arquiva a mensagem selecionada após aprovação quando aplicável.",category:"email",icon:"archive",requiredCapabilities:["email.modify"],risk:"write",fields:[] },
  { id:"calendar.summary",title:"Resumir agenda",description:"Gera um resumo dos compromissos do período.",category:"calendar",icon:"calendar",requiredCapabilities:["calendar.read"],risk:"read",fields:[{key:"period",label:"Período",type:"select",required:true,options:[{value:"today",label:"Hoje"},{value:"tomorrow",label:"Amanhã"},{value:"week",label:"Próximos 7 dias"}]}] },
  { id:"filesystem.list",title:"Listar arquivos",description:"Lista arquivos de uma pasta permitida.",category:"filesystem",icon:"folder",requiredCapabilities:[],risk:"read",fields:[{key:"path",label:"Pasta",type:"path",required:true}] },
  { id:"filesystem.move",title:"Mover arquivo",description:"Move um arquivo com as mesmas permissões e aprovações do Nexo.",category:"filesystem",icon:"folder-input",requiredCapabilities:[],risk:"write",fields:[{key:"source",label:"Origem",type:"path",required:true},{key:"destination",label:"Destino",type:"path",required:true}] },
  { id:"system.snapshot",title:"Resumo do computador",description:"Coleta disco, memória e processos para análise.",category:"system",icon:"monitor",requiredCapabilities:[],risk:"read",fields:[] },
  { id:"browser.open",title:"Abrir página",description:"Abre uma URL permitida no Browser Agent.",category:"browser",icon:"globe",requiredCapabilities:[],risk:"read",fields:[{key:"url",label:"URL",type:"text",required:true}] },
  { id:"ai.summarize",title:"Resumir conteúdo",description:"Usa a IA local para resumir o resultado de uma etapa anterior.",category:"ai",icon:"sparkles",requiredCapabilities:[],risk:"read",fields:[{key:"source",label:"Fonte",type:"text",required:true,placeholder:"$trigger.data"}] },
  { id:"ai.classify",title:"Classificar",description:"Classifica conteúdo usando a IA local.",category:"ai",icon:"tags",requiredCapabilities:[],risk:"read",fields:[{key:"source",label:"Fonte",type:"text",required:true}] },
  { id:"notification.show",title:"Mostrar notificação",description:"Exibe uma notificação do sistema e registra o resultado no histórico.",category:"output",icon:"bell",requiredCapabilities:[],risk:"read",fields:[{key:"title",label:"Título",type:"text",required:true},{key:"content",label:"Conteúdo",type:"text",required:true,placeholder:"$actions.resumo.output"}] }
];
