export type AutomationActionRisk = "read" | "write" | "sensitive";
export type AutomationActionField = { key:string;label:string;type:"text"|"number"|"select"|"connection"|"path"|"boolean";required?:boolean;options?:Array<{value:string;label:string}>;placeholder?:string };
export type AutomationActionCatalogItem = { id:string;title:string;description:string;category:"email"|"calendar"|"filesystem"|"system"|"browser"|"apps"|"ai"|"output"|"nexo";icon:string;requiredCapabilities:string[];risk:AutomationActionRisk;fields:AutomationActionField[] };

export const AUTOMATION_ACTION_CATALOG: AutomationActionCatalogItem[] = [
  { id:"nexo.command",title:"Pedir ao Nexo",description:"Executa uma tarefa usando o agente somente quando uma ação estruturada não for suficiente.",category:"nexo",icon:"sparkles",requiredCapabilities:[],risk:"read",fields:[{key:"command",label:"O que o Nexo deve fazer?",type:"text",required:true}] },
  { id:"email.summary",title:"Resumir e-mail",description:"Resume a mensagem recebida pelo gatilho.",category:"email",icon:"mail",requiredCapabilities:["email.read"],risk:"read",fields:[] },
  { id:"email.mark_read",title:"Marcar como lido",description:"Marca a mensagem do gatilho como lida.",category:"email",icon:"mail-check",requiredCapabilities:["email.modify"],risk:"write",fields:[] },
  { id:"email.archive",title:"Arquivar e-mail",description:"Arquiva a mensagem selecionada após aprovação quando aplicável.",category:"email",icon:"archive",requiredCapabilities:["email.modify"],risk:"write",fields:[] },
  { id:"calendar.summary",title:"Resumir agenda",description:"Gera um resumo dos compromissos do período.",category:"calendar",icon:"calendar",requiredCapabilities:["calendar.read"],risk:"read",fields:[{key:"period",label:"Período",type:"select",required:true,options:[{value:"today",label:"Hoje"},{value:"tomorrow",label:"Amanhã"},{value:"week",label:"Próximos 7 dias"}]}] },
  { id:"filesystem.list",title:"Listar arquivos",description:"Lista arquivos de uma pasta permitida.",category:"filesystem",icon:"folder",requiredCapabilities:[],risk:"read",fields:[{key:"path",label:"Pasta",type:"path",required:true}] },
  { id:"filesystem.move",title:"Mover arquivo",description:"Move um arquivo com as mesmas permissões e aprovações do Nexo.",category:"filesystem",icon:"folder-input",requiredCapabilities:[],risk:"write",fields:[{key:"source",label:"Origem",type:"path",required:true},{key:"destination",label:"Destino",type:"path",required:true}] },
  { id:"system.snapshot",title:"Resumo do computador",description:"Coleta disco, memória e processos para análise.",category:"system",icon:"monitor",requiredCapabilities:[],risk:"read",fields:[] },
  { id:"browser.open",title:"Abrir página",description:"Abre uma URL permitida no Browser Agent.",category:"browser",icon:"globe",requiredCapabilities:[],risk:"read",fields:[{key:"url",label:"URL",type:"text",required:true}] },
  { id:"browser.extract",title:"Extrair conteúdo",description:"Extrai o conteúdo principal de uma página.",category:"browser",icon:"scan-text",requiredCapabilities:[],risk:"read",fields:[{key:"url",label:"URL",type:"text",required:true}] },
  { id:"ai.summarize",title:"Resumir conteúdo",description:"Usa a IA local para resumir o resultado de uma etapa anterior.",category:"ai",icon:"sparkles",requiredCapabilities:[],risk:"read",fields:[{key:"source",label:"Fonte",type:"text",required:true,placeholder:"$trigger.data"}] },
  { id:"ai.classify",title:"Classificar",description:"Classifica conteúdo usando a IA local.",category:"ai",icon:"tags",requiredCapabilities:[],risk:"read",fields:[{key:"source",label:"Fonte",type:"text",required:true}] },
  { id:"notification.show",title:"Mostrar notificação",description:"Mostra o resultado no Nexo e registra no histórico.",category:"output",icon:"bell",requiredCapabilities:[],risk:"read",fields:[{key:"title",label:"Título",type:"text",required:true},{key:"content",label:"Conteúdo",type:"text",required:true,placeholder:"$actions.resumo.output"}] }
];
