import { describe, expect, it } from "vitest";
import { AgentLoop } from "../../packages/core/src/agent/loop/agent-loop.js";
import { encodeObservation } from "../../packages/core/src/agent/loop/observation-encoder.js";
import type { AgentLoopDependencies } from "../../packages/core/src/agent/loop/types.js";
import type { PreparedAction } from "../../packages/core/src/agent/execution/types.js";

const action: PreparedAction = { executionId: "execution-1", toolName: "lookup", input: { id: "42" }, fingerprint: "f", mutatesState: false, risk: "READ", requiresApproval: false, status: "PREPARED" };
function deps(turns: Array<{ content?: string; toolCalls: Array<{ id: string; name: string; arguments: Record<string, unknown> }> }>): AgentLoopDependencies { let cursor = 0; return { agentTurn: async () => turns[cursor++], tools: () => [{ name: "lookup", description: "Lookup" }], preflight: async () => ({ ok: true, action }), execute: async () => ({ status: "SUCCEEDED", action, result: { ok: true, summary: "Found", data: { id: "42" } } }), observe: (result, id) => encodeObservation(id, "lookup", result.result!, "UNTRUSTED_CONTENT") }; }
describe("AgentLoop protocol", () => {
  it("executes exactly one tool then completes", async () => { const loop = new AgentLoop(deps([{ toolCalls: [{ id: "call-1", name: "lookup", arguments: { id: "42" } }] }, { content: "Done", toolCalls: [] }])); const state = await loop.run("find 42"); expect(state.status).toBe("COMPLETED"); expect(state.toolCallCount).toBe(1); expect(state.finalResponse).toBe("Done"); });
  it("never executes a multi-tool turn and fails after the repair limit", async () => { let executions = 0; const source = deps([{ toolCalls: [{ id: "a", name: "lookup", arguments: {} }, { id: "b", name: "lookup", arguments: {} }] }, { toolCalls: [{ id: "a", name: "lookup", arguments: {} }, { id: "b", name: "lookup", arguments: {} }] }, { toolCalls: [{ id: "a", name: "lookup", arguments: {} }, { id: "b", name: "lookup", arguments: {} }] }]); const loop = new AgentLoop({ ...source, execute: async prepared => { executions++; return { status: "SUCCEEDED", action: prepared, result: { ok: true, summary: "unexpected" } }; } }); const state = await loop.run("do two things"); expect(state.status).toBe("FAILED"); expect(state.protocolRepairCount).toBe(3); expect(state.finalResponse).toContain("PROTOCOL_ERROR"); expect(executions).toBe(0); });
  it("persists every security-relevant transition",async()=>{const statuses:string[]=[];const loop=new AgentLoop({...deps([{toolCalls:[{id:"call-1",name:"lookup",arguments:{id:"42"}}]},{content:"Done",toolCalls:[]}]),persistence:{save:async state=>{statuses.push(state.status);}}});await loop.run("find 42");expect(statuses).toEqual(expect.arrayContaining(["DECIDING","PREFLIGHT","EXECUTING","OBSERVING","COMPLETED"]));});
  it("permits bounded polling only for a tool that declares progress semantics",async()=>{let turn=0,execution=0;const statuses:string[]=[];const loop=new AgentLoop({agentTurn:async()=>turn++<2?{toolCalls:[{id:`poll-${turn}`,name:"poll_status",arguments:{jobId:"j"}}]}:{content:"Done",toolCalls:[]},tools:()=>[{name:"poll_status",description:"Poll",polling:{allowed:true,minIntervalMs:0,maxDurationMs:1000,maxAttempts:3,progressFields:["status"]}}],preflight:async()=>({ok:true,action:{...action,toolName:"poll_status",input:{jobId:"j"},fingerprint:"same"}}),execute:async prepared=>({status:"SUCCEEDED",action:prepared,result:{ok:true,summary:"status",data:{status:++execution===1?"running":"completed"}}}),observe:(result,id)=>encodeObservation(id,"poll_status",result.result!,"TRUSTED_LOCAL"),persistence:{save:async state=>{statuses.push(state.status);}}});const state=await loop.run("wait");expect(state.status).toBe("COMPLETED");expect(execution).toBe(2);expect(statuses).toContain("WAITING_EXTERNAL_PROGRESS");});
});
