import{describe,expect,it}from"vitest";import{z}from"zod";import fs from"node:fs/promises";import os from"node:os";import path from"node:path";
import{migrateSettings}from"../../packages/core/src/config/settings-migrations.js";import{deterministicFilesystemIntent}from"../../packages/core/src/agent/orchestrator/filesystem-intent-enricher.js";import{deterministicEmailReadIntent}from"../../packages/core/src/agent/orchestrator/email-intent-enricher.js";import{parseAgentIntentV1}from"../../packages/core/src/agent/orchestrator/schemas/intent-v1.js";import{responsePolicy}from"../../packages/core/src/chat/presentation/response-policy.js";import{ToolRegistry}from"../../packages/core/src/tools/registry.js";import{ActionExecutor}from"../../packages/core/src/agent/execution/action-executor.js";import{PermissionEngine}from"../../packages/core/src/permissions/policy.js";import{AuditService}from"../../packages/core/src/audit/audit.js";import{NexoDatabase}from"../../packages/core/src/database/db.js";import{canFallbackToLegacy}from"../../packages/core/src/agent/fallback/agent-fallback-policy.js";
const defaults={agentLoopMode:"full",oauth:{googleClientId:"",microsoftClientId:"",microsoftTenant:"common"}}as any;
describe("fechamento v0.6.5",()=>{
  it("migra para o Agent Loop full no refinamento V2 e preserva escolha explícita",()=>{expect(migrateSettings({agentLoopMode:"full"},defaults).agentLoopMode).toBe("full");expect(migrateSettings({agentLoopMode:"full",agentLoopModeExplicitlySelected:true},defaults).agentLoopMode).toBe("full");});
  it("interpreta quantidade, recentes, pastas e criação de pasta",()=>{expect(deterministicFilesystemIntent("Liste os arquivos da pasta Downloads")?.entities.kind).toBeUndefined();expect(deterministicFilesystemIntent("Liste os 5 arquivos mais recentes da pasta Downloads")?.entities).toMatchObject({kind:"file",sortBy:"modifiedAt",sortDirection:"desc",limit:5});expect(deterministicFilesystemIntent("Quais pastas existem em Downloads?")?.entities).toMatchObject({kind:"directory"});expect(deterministicFilesystemIntent("Crie uma pasta chamada TesteAgente dentro de Downloads")?.operation).toBe("create_folder");});
  it("interpreta email latest/quantidade e síntese",()=>{expect(deterministicEmailReadIntent("Qual foi o último e-mail que recebi?")?.operation).toBe("latest");expect(deterministicEmailReadIntent("Mostre meus últimos 5 e-mails")?.entities.maxResults).toBe(5);const intent=deterministicEmailReadIntent("Resuma meus últimos 5 e-mails")!;expect(responsePolicy(["email_search"],intent)).toEqual({mode:"synthesize",appendText:true});});
  it("repara clarification sem missing sem expor erro técnico",()=>{const parsed=parseAgentIntentV1({schemaVersion:1,status:"needs_clarification",domain:"general",intent:"answer",operation:"answer",entities:{},referencesPreviousResult:false,requiresDataLookup:false,requiresConfirmation:false,confidence:.5,missing:[]});expect(parsed.missing).toEqual(["details"]);expect(parsed.question).toBe("Preciso de mais detalhes para continuar.");});
  it("não habilita fallback depois de qualquer efeito",()=>{expect(canFallbackToLegacy("NO_ACTION")).toBe(true);for(const state of["READ_ONLY_EXECUTED","PREFLIGHT_MUTATION","WAITING_APPROVAL","DISPATCHING","MUTATION_COMPLETED","RESULT_UNKNOWN"]as const)expect(canFallbackToLegacy(state)).toBe(false);});
  it("não inventa mutationSafety e bloqueia mutation em pedido de leitura",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"nexo-v065-"));try{const db=new NexoDatabase(dir);await db.ready();const registry=new ToolRegistry().register({name:"unsafe_mutation",description:"test",risk:"WRITE",permissions:[],mutatesState:true,inputSchema:z.object({}),execute:async()=>({ok:true,summary:"no"})});expect(registry.get("unsafe_mutation")?.mutationSafety).toBeUndefined();const executor=new ActionExecutor(registry,new PermissionEngine(()=>({allowedRoots:[dir],autonomy:"balanced"}as any)),new AuditService(db));const result=await executor.preflight("unsafe_mutation",{},{userRequest:"Resuma meus emails"});expect(result).toMatchObject({ok:false,code:"SECURITY_DENIED"});}finally{await fs.rm(dir,{recursive:true,force:true});}});
});
