import { Container, Graphics, Rectangle, Sprite, Text, Texture } from "pixi.js";
import type { AgentVisualEvent, OfficeStationId } from "@nexo/shared";
import { AgentSprite } from "../agent/AgentSprite";
import { AgentMovement } from "../agent/AgentMovement";
import { AgentActionQueue, type AgentAction, STATE_DURATION } from "../agent/AgentActionQueue";
import { Grid } from "../navigation/Grid";
import { findPath } from "../navigation/AStar";
import { smoothPath } from "../navigation/PathSmoothing";
import { OFFICE_STATIONS } from "../data/office-layout";
import type { OctopusAnimation } from "../data/sprite-manifest";
import { createStationEffects } from "../effects/StationEffects";

type NavigationFailure={fromStation:OfficeStationId;targetStation:OfficeStationId;gridX:number;gridY:number};
export class OfficeScene extends Container {
  readonly agent:AgentSprite; private grid=new Grid(); private movement=new AgentMovement(); private queue=new AgentActionQueue();
  private stationEffects=createStationEffects();private debugLayer=new Graphics();private developerMode=false;
  private current?:AgentAction; private currentSince=0; private station:OfficeStationId="central-desk"; private navigationFailure?:NavigationFailure;
  private navigationMs=0;private navigationFailures=0;
  private statusLabel=new Text({text:"Disponível",style:{fontFamily:"monospace",fontSize:22,fill:"#ffffff",stroke:{color:"#121827",width:5}}});
  constructor(map:Texture,sheet:Texture,onAgent:()=>void,onStation:(station:OfficeStationId)=>void,foreground?:Texture){super();this.sortableChildren=true;this.eventMode="static";this.hitArea=new Rectangle(0,0,map.width,map.height);this.on("pointertap",event=>{if(!this.developerMode||!event.ctrlKey)return;const local=this.toLocal(event.global);this.grid.toggle(this.grid.toGrid(local.x,local.y));this.redrawDebug();});const background=new Sprite(map);background.zIndex=0;this.addChild(background);for(const station of Object.values(OFFICE_STATIONS)){const hit=new Graphics().circle(0,0,34).fill({color:0x7c5cff,alpha:.001});hit.position.set(station.x,station.y);hit.eventMode="static";hit.cursor="pointer";hit.on("pointertap",()=>onStation(station.id));hit.zIndex=station.y-1;this.addChild(hit);}for(const effect of this.stationEffects.values())this.addChild(effect);this.agent=new AgentSprite(sheet);this.agent.position.set(OFFICE_STATIONS[this.station].x,OFFICE_STATIONS[this.station].y);this.agent.zIndex=this.agent.y;this.agent.on("pointertap",onAgent);this.addChild(this.agent);if(foreground){const layer=new Sprite(foreground);layer.zIndex=2500;this.addChild(layer);}this.statusLabel.anchor.set(.5,1);this.statusLabel.position.set(this.agent.x,this.agent.y-92);this.statusLabel.zIndex=4000;this.addChild(this.statusLabel);this.debugLayer.zIndex=5000;this.addChild(this.debugLayer);}
  consume(event:AgentVisualEvent,reducedMotion=false){if(["run.completed","run.failed","run.cancelled"].includes(event.type))this.queue.clear();if(event.stationId){const effect=this.stationEffects.get(event.stationId);if(effect)effect.visible=event.type==="tool.started"||event.type==="tool.progress"||event.type==="approval.requested";}if(["tool.completed","run.failed","run.cancelled"].includes(event.type))for(const effect of this.stationEffects.values())effect.visible=false;this.queue.enqueue(event,this.station);if(!this.current)this.startNext(reducedMotion);}
  update(delta:number,reducedMotion=false){for(const effect of this.stationEffects.values())effect.update(delta);if(!this.current){this.agent.update(delta);return;}if(this.current.kind==="move"){if(reducedMotion){const target=OFFICE_STATIONS[this.current.stationId];this.agent.position.set(target.x,target.y);this.finishAction(reducedMotion);}else{const result=this.movement.update(this.agent.position,delta);this.agent.play((`walk${result.direction[0].toUpperCase()}${result.direction.slice(1)}`) as OctopusAnimation);if(result.arrived)this.finishAction(reducedMotion);}}else{const transient=this.current.state in STATE_DURATION;if(Date.now()-this.currentSince>=this.current.minimumMs&&(transient||this.queue.size()>0))this.finishAction(reducedMotion);}this.agent.zIndex=this.agent.y;this.statusLabel.position.set(this.agent.x,this.agent.y-92);this.agent.update(delta);}
  private startNext(reducedMotion:boolean){this.current=this.queue.next();if(!this.current){this.agent.play("idle");this.statusLabel.text="Disponível";return;}this.currentSince=Date.now();this.statusLabel.text=this.current.label;if(this.current.kind==="move"){const target=OFFICE_STATIONS[this.current.stationId];const start=this.grid.toGrid(this.agent.x,this.agent.y);const navigationStarted=performance.now();const raw=findPath(this.grid,start,this.grid.toGrid(target.x,target.y));this.navigationMs=performance.now()-navigationStarted;if(!raw.length){this.navigationFailures+=1;this.navigationFailure={fromStation:this.station,targetStation:this.current.stationId,gridX:start.x,gridY:start.y};this.current={...this.current,kind:"animate",state:"error",label:"Não foi possível alcançar a estação",minimumMs:1000};this.currentSince=Date.now();this.statusLabel.text=this.current.label;this.agent.play("error");return;}this.navigationFailure=undefined;const path=smoothPath(raw).map(point=>this.grid.toWorld(point));path.push({x:target.x,y:target.y});this.movement.setPath(path);if(reducedMotion){this.agent.position.set(target.x,target.y);this.finishAction(true);}}else this.agent.play(this.current.state==="walking"?"idle":this.current.state as OctopusAnimation);}
  private finishAction(reducedMotion:boolean){if(this.current?.kind==="move"){this.station=this.current.stationId;this.queue.completeMove(this.current.stationId);}this.current=undefined;this.startNext(reducedMotion);}
  setDeveloperMode(value:boolean){this.developerMode=value;this.redrawDebug();}
  exportGrid(){return JSON.stringify({cellSize:this.grid.cellSize,width:this.grid.width,height:this.grid.height,blocked:this.grid.blockedCells().map(({x,y})=>[x,y])},null,2);}
  private redrawDebug(){this.debugLayer.clear();if(!this.developerMode)return;for(let x=0;x<=this.grid.width;x++)this.debugLayer.moveTo(x*this.grid.cellSize,0).lineTo(x*this.grid.cellSize,this.grid.height*this.grid.cellSize).stroke({color:0x70b7ff,alpha:.18,width:1});for(let y=0;y<=this.grid.height;y++)this.debugLayer.moveTo(0,y*this.grid.cellSize).lineTo(this.grid.width*this.grid.cellSize,y*this.grid.cellSize).stroke({color:0x70b7ff,alpha:.18,width:1});for(const cell of this.grid.blockedCells())this.debugLayer.rect(cell.x*this.grid.cellSize,cell.y*this.grid.cellSize,this.grid.cellSize,this.grid.cellSize).fill({color:0xff5577,alpha:.16});for(const station of Object.values(OFFICE_STATIONS))this.debugLayer.circle(station.x,station.y,15).stroke({color:0xffd166,width:3});this.debugLayer.rect(this.agent.x-35,this.agent.y-70,70,70).stroke({color:0x66ffb3,width:2});}
  getDebug(){const grid=this.grid.toGrid(this.agent.x,this.agent.y);return{station:this.station,target:this.current?.stationId,x:Math.round(this.agent.x),y:Math.round(this.agent.y),gridX:grid.x,gridY:grid.y,pathNodes:this.movement.path.length,queue:this.queue.size(),navigationMs:this.navigationMs,navigationFailures:this.navigationFailures,...this.queue.debug(),navigationFailure:this.navigationFailure};}
}
