import { Application,Assets,Container,TextureStyle,type Texture } from "pixi.js";
import type { AgentVisualEvent,OfficeStationId } from "@nexo/shared";
import { OfficeCamera,type OfficeZoom } from "./OfficeCamera";
import { OfficeScene } from "./OfficeScene";
import { OfficeHud } from "./OfficeHud";
import { OFFICE_STATIONS } from "../data/office-layout";
import mapUrl from "../../assets/pixel-office/maps/nexo-office-personal.png";
import spriteUrl from "../../assets/pixel-office/sprites/nexo-octopus-colors.png";
import { loadSpriteAtlas } from "../render/SpriteAtlas";
export class OfficeEngine{
  private sheet?:Texture;private app=new Application();private world=new Container();private hud=new OfficeHud();private camera=new OfficeCamera();private scene?:OfficeScene;private observer?:ResizeObserver;private visible=true;private initialized=false;private destroyed=false;private autoFocus=true;private zoom:OfficeZoom="fit";private lastAutoFrame=0;private interactionCleanup?:()=>void;reducedMotion=false;
  async mount(host:HTMLElement,onAgent:(agentId:string,conversationId?:string)=>void,onStation:(station:OfficeStationId)=>void){TextureStyle.defaultOptions.scaleMode="nearest";const started=performance.now(),resolution=Math.min(Math.max(globalThis.devicePixelRatio||1,1),2);await this.app.init({resizeTo:host,antialias:false,autoDensity:true,resolution,background:0x090d18,backgroundAlpha:1,powerPreference:"high-performance"});this.initialized=true;if(this.destroyed){this.app.destroy(true,{children:true,texture:false});return;}host.appendChild(this.app.canvas);const[map,sheet]=await Promise.all([Assets.load(mapUrl),loadSpriteAtlas(spriteUrl)]);if(this.destroyed){sheet.destroy(true);return;}this.sheet=sheet;this.scene=new OfficeScene(map,sheet,onAgent,station=>{const focus=OFFICE_STATIONS[station].cameraFocus;this.camera.focusPoint({x:focus.x,y:focus.y},focus.zoom);onStation(station);});this.world.addChild(this.scene);this.world.zIndex=0;this.hud.zIndex=100000;this.app.stage.sortableChildren=true;this.app.stage.addChild(this.world,this.hud);this.observer=new ResizeObserver(()=>this.resize(host,this.zoom));this.observer.observe(host);this.camera.setAutoFocus(this.autoFocus);this.camera.resize(this.world,host.clientWidth,host.clientHeight,this.zoom,true);this.interactionCleanup=this.bindCameraControls(this.app.canvas);this.app.ticker.add(ticker=>{if(!this.visible||!this.scene)return;const delta=ticker.deltaMS/1000;this.scene.update(delta,this.reducedMotion);if(this.autoFocus&&performance.now()-this.lastAutoFrame>220){this.camera.frameActive(this.scene.activeAgentPoints());this.lastAutoFrame=performance.now();}this.camera.update(this.world,delta);this.hud.update(this.scene,this.app.screen.width,this.app.screen.height,delta,this.reducedMotion);});if(!this.visible)this.app.ticker.stop();performance.measure("pixel_office.init_ms",{start:started,end:performance.now()});}
  setReducedMotion(value:boolean){this.reducedMotion=value;}setDeveloperMode(value:boolean){this.scene?.setDeveloperMode(value);}setAutoFocus(value:boolean){this.autoFocus=value;this.camera.setAutoFocus(value);}exportGrid(){return this.scene?.exportGrid();}
  setVisible(value:boolean){this.visible=value;if(!this.initialized)return;if(value)this.app.ticker.start();else this.app.ticker.stop();}
  setZoom(host:HTMLElement,zoom:OfficeZoom){this.zoom=zoom;if(this.initialized)this.camera.setZoom(this.world,host.clientWidth,host.clientHeight,zoom);}
  consume(event:AgentVisualEvent){this.scene?.consume(event,this.reducedMotion);}restore(events:AgentVisualEvent[]){this.scene?.restore(events,this.reducedMotion);}debug(){return{fps:this.initialized?Math.round(this.app.ticker.FPS):0,...this.scene?.getDebug()};}
  destroy(){if(this.destroyed)return;this.destroyed=true;this.observer?.disconnect();this.interactionCleanup?.();if(this.initialized)this.app.destroy(true,{children:true,texture:false});this.sheet?.destroy(true);}
  private resize(host:HTMLElement,zoom:OfficeZoom){this.camera.resize(this.world,host.clientWidth,host.clientHeight,zoom);}
  private bindCameraControls(canvas:HTMLCanvasElement){let dragging=false,lastX=0,lastY=0;const pointerDown=(event:PointerEvent)=>{if(!(event.button===1||(event.button===0&&event.shiftKey)))return;dragging=true;lastX=event.clientX;lastY=event.clientY;canvas.setPointerCapture?.(event.pointerId);event.preventDefault();};const pointerMove=(event:PointerEvent)=>{if(!dragging)return;const dx=event.clientX-lastX,dy=event.clientY-lastY;lastX=event.clientX;lastY=event.clientY;this.camera.panBy(dx,dy);event.preventDefault();};const pointerUp=(event:PointerEvent)=>{if(!dragging)return;dragging=false;canvas.releasePointerCapture?.(event.pointerId);};const wheel=(event:WheelEvent)=>{this.camera.manualZoom(event.deltaY<0?1.08:.92);event.preventDefault();};canvas.addEventListener("pointerdown",pointerDown);canvas.addEventListener("pointermove",pointerMove);canvas.addEventListener("pointerup",pointerUp);canvas.addEventListener("pointercancel",pointerUp);canvas.addEventListener("wheel",wheel,{passive:false});return()=>{canvas.removeEventListener("pointerdown",pointerDown);canvas.removeEventListener("pointermove",pointerMove);canvas.removeEventListener("pointerup",pointerUp);canvas.removeEventListener("pointercancel",pointerUp);canvas.removeEventListener("wheel",wheel);};}
}

